name: bmagic_magic086_03
sha1: 166422f3fe178604016cf73801abe0ec7a86a64e
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic086_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic086/03.bin
  asm_path: out/splat/emi/bmagic/magic086/03/asm
  src_path: src/emi/bmagic/magic086/03
  ld_script_path: out/splat/emi/bmagic/magic086/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1480
        - asm
        - func_801EF1C8
      - - 2084
        - asm
        - func_801EF424
      - - 3552
        - asm
        - func_801EF9E0
      - - 5544
        - asm
        - func_801F01A8
  - - 0x1790
