name: etc_commu00_00
sha1: 9194f952f747f67935b44048690ee954d50f4daa
options:
  platform: psx
  compiler: psyq
  basename: etc_commu00_00
  base_path: ../../../../..
  target_path: out/binaries/emi/etc/commu00/00.bin
  asm_path: out/splat/emi/etc/commu00/00/asm
  src_path: src/emi/etc/commu00/00
  ld_script_path: out/splat/emi/etc/commu00/00/linker.ld
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/targets/emi/etc/commu00/00/psx.txt
  - config/targets/emi/etc/commu00/00/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 8104
  vram: 2149518248
  subsegments:
  - - 8104
    - asm
    - func_801F0BA8
  - - 8180
    - asm
    - func_801F0BF4
  - - 8300
    - asm
    - func_801F0C6C
  - - 8508
    - asm
    - func_801F0D3C
  - - 8732
    - asm
    - func_801F0E1C
  - - 8904
    - asm
    - func_801F0EC8
  - - 8968
    - asm
    - func_801F0F08
  - - 9148
    - asm
    - func_801F0FBC
  - - 9316
    - asm
    - func_801F1064
  - - 9488
    - asm
    - func_801F1110
  - - 9732
    - asm
    - func_801F1204
  - - 9812
    - asm
    - func_801F1254
  - - 9876
    - asm
    - func_801F1294
  - - 9928
    - asm
    - func_801F12C8
  - - 10008
    - asm
    - func_801F1318
  - - 10168
    - asm
    - func_801F13B8
  - - 10308
    - asm
    - func_801F1444
  - - 10372
    - asm
    - func_801F1484
  - - 10436
    - asm
    - func_801F14C4
  - - 10488
    - asm
    - func_801F14F8
  - - 10552
    - asm
    - func_801F1538
  - - 10616
    - asm
    - func_801F1578
  - - 10680
    - asm
    - func_801F15B8
  - - 10744
    - asm
    - func_801F15F8
  - - 10808
    - asm
    - func_801F1638
  - - 10884
    - asm
    - func_801F1684
  - - 10940
    - asm
    - func_801F16BC
  - - 11000
    - asm
    - func_801F16F8
  - - 11120
    - asm
    - func_801F1770
  - - 11172
    - asm
    - func_801F17A4
  - - 11300
    - asm
    - func_801F1824
  - - 11380
    - asm
    - func_801F1874
  - - 11452
    - asm
    - func_801F18BC
  - - 11512
    - asm
    - func_801F18F8
  - - 12028
    - asm
    - func_801F1AFC
  - - 12080
    - asm
    - func_801F1B30
  - - 12172
    - asm
    - func_801F1B8C
  - - 12232
    - asm
    - func_801F1BC8
  - - 12916
    - asm
    - func_801F1E74
  - - 12976
    - asm
    - func_801F1EB0
  - - 13072
    - asm
    - func_801F1F10
  - - 13132
    - asm
    - func_801F1F4C
  - - 13212
    - asm
    - func_801F1F9C
  - - 13272
    - asm
    - func_801F1FD8
  - - 13344
    - asm
    - func_801F2020
  - - 13404
    - asm
    - func_801F205C
  - - 13868
    - asm
    - func_801F222C
  - - 13964
    - asm
    - func_801F228C
  - - 14024
    - asm
    - func_801F22C8
  - - 14172
    - asm
    - func_801F235C
  - - 14244
    - asm
    - func_801F23A4
  - - 14588
    - asm
    - T_801F24FC
- - 15696
  - bin
  - data
- - 15696
