name: world02_area100_13
sha1: 3beeb58053ff09e7e7b1d7ea380100d786fb7208
options:
  platform: psx
  compiler: psyq
  basename: world02_area100_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world02/area100/13.bin
  asm_path: out/splat/emi/world02/area100/13/asm
  src_path: src/emi/world02/area100/13
  ld_script_path: out/splat/emi/world02/area100/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 352
        - asm
        - func_801F2D60
      - - 1512
        - asm
        - func_801F31E8
      - - 4464
        - asm
        - func_801F3D70
  - - 0x2370
