name: world03_area143_13
sha1: cef52d7ecfd6027c0e5628e0d84746a4cc870694
options:
  platform: psx
  compiler: psyq
  basename: world03_area143_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world03/area143/13.bin
  asm_path: out/splat/emi/world03/area143/13/asm
  src_path: src/emi/world03/area143/13
  ld_script_path: out/splat/emi/world03/area143/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 0
        - asm
        - func_801F2C00
      - - 316
        - asm
        - func_801F2D3C
      - - 380
        - asm
        - func_801F2D7C
      - - 440
        - asm
        - func_801F2DB8
      - - 752
        - asm
        - func_801F2EF0
      - - 992
        - asm
        - func_801F2FE0
      - - 1184
        - asm
        - func_801F30A0
      - - 2436
        - asm
        - func_801F3584
      - - 5084
        - asm
        - func_801F3FDC
  - - 0x2714
