name: bmagic_magic060_00
sha1: c4b7436afa7ce2d88b43cd98e626c8b1b72094a4
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic060_00
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic060/00.bin
  asm_path: out/splat/emi/bmagic/magic060/00/asm
  src_path: src/emi/bmagic/magic060/00
  ld_script_path: out/splat/emi/bmagic/magic060/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 848
        - asm
        - func_801EEF50
      - - 1208
        - asm
        - func_801EF0B8
      - - 1304
        - asm
        - func_801EF118
      - - 1396
        - asm
        - func_801EF174
      - - 1756
        - asm
        - func_801EF2DC
      - - 2160
        - asm
        - func_801EF470
      - - 2448
        - asm
        - func_801EF590
      - - 2924
        - asm
        - func_801EF76C
      - - 3364
        - asm
        - func_801EF924
      - - 3840
        - asm
        - func_801EFB00
      - - 5420
        - asm
        - func_801F012C
      - - 6184
        - asm
        - func_801F0428
  - - 0x1fe8
