name: bmagic_magic166_03
sha1: b45412882ce83b767f62a53eb319116656c7368e
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic166_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic166/03.bin
  asm_path: out/splat/emi/bmagic/magic166/03/asm
  src_path: src/emi/bmagic/magic166/03
  ld_script_path: out/splat/emi/bmagic/magic166/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 0
        - asm
        - func_801EEC00
      - - 752
        - asm
        - func_801EEEF0
      - - 1668
        - asm
        - func_801EF284
      - - 1920
        - asm
        - func_801EF380
      - - 2716
        - asm
        - func_801EF69C
  - - 0x2924
