schema = "harness.target/v2"
id = "emi/world00/area008/13"
disc_id = "BIN/WORLD00/AREA008.EMI#13"
kind = "emi"
source_dir = "src/emi/world00/area008/13"
binary = "out/binaries/emi/world00/area008/13.bin"
splat = "config/targets/emi/world00/area008/13/splat.yaml"
load_address = 0x801f2c00
