name: world03_area135_14
sha1: 9f78885d37d4a12b79a76c65b55658d2b3fed7c4
options:
  platform: psx
  compiler: psyq
  basename: world03_area135_14
  base_path: ../../../../..
  target_path: out/binaries/emi/world03/area135/14.bin
  asm_path: out/splat/emi/world03/area135/14/asm
  src_path: src/emi/world03/area135/14
  ld_script_path: out/splat/emi/world03/area135/14/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 1028
        - asm
        - func_801F3004
      - - 1696
        - asm
        - func_801F32A0
      - - 1800
        - asm
        - func_801F3308
      - - 3012
        - asm
        - func_801F37C4
      - - 3120
        - asm
        - func_801F3830
      - - 4264
        - asm
        - func_801F3CA8
      - - 12236
        - asm
        - func_801F5BCC
      - - 12384
        - asm
        - func_801F5C60
      - - 12572
        - asm
        - func_801F5D1C
      - - 12696
        - asm
        - func_801F5D98
      - - 13096
        - asm
        - func_801F5F28
      - - 13372
        - asm
        - func_801F603C
      - - 13536
        - asm
        - func_801F60E0
      - - 13672
        - asm
        - func_801F6168
      - - 13736
        - asm
        - func_801F61A8
  - - 0x3fc4
