name: scenario_scena09_00
sha1: a78c52578edf92de2bdc101d3fa63beb18d2e7b8
options:
  platform: psx
  compiler: psyq
  basename: scenario_scena09_00
  base_path: ../../../../..
  target_path: out/binaries/emi/scenario/scena09/00.bin
  asm_path: out/splat/emi/scenario/scena09/00/asm
  src_path: src/emi/scenario/scena09/00
  ld_script_path: out/splat/emi/scenario/scena09/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149542912
    subsegments:
      - - 2084
        - asm
        - func_801F7424
      - - 2420
        - asm
        - func_801F7574
      - - 2492
        - asm
        - func_801F75BC
      - - 2768
        - asm
        - func_801F76D0
  - - 0x7958
