name: bmagic_magic113_03
sha1: 64de77beff5f4532b8a8fa83eced9245e4ce2b42
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic113_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic113/03.bin
  asm_path: out/splat/emi/bmagic/magic113/03/asm
  src_path: src/emi/bmagic/magic113/03
  ld_script_path: out/splat/emi/bmagic/magic113/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 2112
        - asm
        - func_801EF440
      - - 2288
        - asm
        - func_801EF4F0
      - - 3396
        - asm
        - func_801EF944
      - - 4512
        - asm
        - func_801EFDA0
      - - 5836
        - asm
        - func_801F02CC
  - - 0x1fe4
