name: world03_area132_13
sha1: 3f35e0d1447a3db0817a70b430f8a79bdd658897
options:
  platform: psx
  compiler: psyq
  basename: world03_area132_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world03/area132/13.bin
  asm_path: out/splat/emi/world03/area132/13/asm
  src_path: src/emi/world03/area132/13
  ld_script_path: out/splat/emi/world03/area132/13/linker.ld
  undefined_funcs_auto_path: out/splat/emi/world03/area132/13/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/world03/area132/13/undefined_syms_auto.txt
  cache_path: out/splat/emi/world03/area132/13/.splache
  asset_path: out/splat/emi/world03/area132/13/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world03/area132/13/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149526532
  subsegments:
  - - 4
    - asm
    - func_801F2C04
  - - 72
    - asm
    - func_801F2C48
  - - 108
    - asm
    - func_801F2C6C
  - - 424
    - c
    - noopHandlerWorld03Area13213_801F2DA8
  - - 432
    - asm
    - func_801F2DB0
  - - 500
    - asm
    - func_801F2DF4
  - - 568
    - asm
    - func_801F2E38
  - - 648
    - asm
    - func_801F2E88
  - - 800
    - asm
    - func_801F2F20
  - - 852
    - asm
    - func_801F2F54
  - - 920
    - asm
    - func_801F2F98
  - - 1096
    - asm
    - func_801F3048
  - - 1148
    - asm
    - func_801F307C
  - - 1216
    - asm
    - func_801F30C0
  - - 1324
    - asm
    - func_801F312C
  - - 1516
    - asm
    - func_801F31EC
  - - 1640
    - asm
    - func_801F3268
  - - 2400
    - asm
    - func_801F3560
  - - 2980
    - asm
    - func_801F37A4
  - - 3072
    - asm
    - func_801F3800
  - - 3164
    - asm
    - func_801F385C
  - - 3248
    - asm
    - func_801F38B0
  - - 3620
    - asm
    - func_801F3A24
  - - 3684
    - asm
    - func_801F3A64
  - - 3820
    - asm
    - func_801F3AEC
  - - 4124
    - asm
    - func_801F3C1C
  - - 4256
    - asm
    - func_801F3CA0
  - - 4272
    - asm
    - func_801F3CB0
  - - 4568
    - asm
    - func_801F3DD8
- - 7824
