name: world01_area057_13
sha1: e79f4036854d7365d7ecaa79e00d5bf945852985
options:
  platform: psx
  compiler: psyq
  basename: world01_area057_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world01/area057/13.bin
  asm_path: out/splat/emi/world01/area057/13/asm
  src_path: src/emi/world01/area057/13
  ld_script_path: out/splat/emi/world01/area057/13/linker.ld
  undefined_funcs_auto_path: out/splat/emi/world01/area057/13/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/world01/area057/13/undefined_syms_auto.txt
  cache_path: out/splat/emi/world01/area057/13/.splache
  asset_path: out/splat/emi/world01/area057/13/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world01/area057/13/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149526532
  subsegments:
  - - 4
    - asm
    - func_801F2C04
  - - 48
    - asm
    - func_801F2C30
  - - 176
    - asm
    - func_801F2CB0
  - - 304
    - asm
    - func_801F2D30
  - - 344
    - asm
    - func_801F2D58
- - 384
  - bin
  - tail
- - 7959
