name: bmagic_magic067_03
sha1: b502453e52e342dd646ada330fed3e6863411773
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic067_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic067/03.bin
  asm_path: out/splat/emi/bmagic/magic067/03/asm
  src_path: src/emi/bmagic/magic067/03
  ld_script_path: out/splat/emi/bmagic/magic067/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 2696
        - asm
        - func_801EF688
      - - 2972
        - asm
        - func_801EF79C
      - - 5316
        - asm
        - func_801F00C4
  - - 0x18f0
