name: world01_area049_13
sha1: c4a5082a78e8a3061b71729b1af5c5bc3396662a
options:
  platform: psx
  compiler: psyq
  basename: world01_area049_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world01/area049/13.bin
  asm_path: out/splat/emi/world01/area049/13/asm
  src_path: src/emi/world01/area049/13
  ld_script_path: out/splat/emi/world01/area049/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2148626432
    subsegments:
      - - 216
        - asm
        - func_801170D8
      - - 720
        - asm
        - func_801172D0
      - - 1040
        - asm
        - func_80117410
      - - 2148
        - asm
        - func_80117864
      - - 2244
        - asm
        - func_801178C4
      - - 2304
        - asm
        - func_80117900
      - - 2912
        - asm
        - func_80117B60
      - - 3704
        - asm
        - func_80117E78
  - - 0x11e0
