#include "internal.h"

/* does: finalizes one current enemy scratch event, updates shared counters,
 * clears ownership/state bits, and runs the follow-up ranking/event helpers.
 * @source: 0x801e54ec FUN_801e54ec
 */
void func_801e54ec(void) {
  BATTLE_ENEMY_SCRATCH_PTR->unk_00 |= 0x40u;
  BATTLE_GLOBAL_WORD_632C +=
      BATTLE_ENEMY_HALF_A0(BATTLE_CURRENT_ENEMY_PTR);
  BATTLE_GLOBAL_WORD_6330 +=
      BATTLE_ENEMY_HALF_94(BATTLE_CURRENT_ENEMY_PTR);
  BATTLE_ENEMY_HALF_94(BATTLE_CURRENT_ENEMY_PTR) = 0u;
  BATTLE_ENEMY_FLAGS_82(BATTLE_CURRENT_ENEMY_PTR) |= 0x4000u;
  func_801dd14c(BATTLE_ENEMY_BYTE_05(BATTLE_ENEMY_SCRATCH_PTR));
  func_801e531c();
  BATTLE_GLOBAL_BYTE_62F3 -= 1u;
  if (BATTLE_GLOBAL_BYTE_62F3 == 0u) {
    BATTLE_GLOBAL_BYTE_6328 |= 2u;
  }
  if (((BATTLE_GLOBAL_HALF_62E8 & 0x4000u) != 0u) &&
      (BATTLE_GLOBAL_BYTE_63CA ==
       BATTLE_ENEMY_BYTE_05(BATTLE_ENEMY_SCRATCH_PTR))) {
    BATTLE_GLOBAL_HALF_62E8 &= 0xbfffu;
  }
  func_800ad074(BATTLE_ENEMY_BYTE_7C(BATTLE_CURRENT_ENEMY_PTR));
  func_80196718((void*)BATTLE_ENEMY_SCRATCH_PTR);
  BATTLE_ENEMY_WORD_100(BATTLE_CURRENT_ENEMY_PTR) &= 0xffffff8fu;
  func_801de1b0(BATTLE_ENEMY_BYTE_05(BATTLE_ENEMY_SCRATCH_PTR));
  BATTLE_ENEMY_SCRATCH_PTR->unk_01 = 2u;
  BATTLE_ENEMY_BYTE_02(BATTLE_ENEMY_SCRATCH_PTR) = 0u;
  BATTLE_ENEMY_BYTE_03(BATTLE_ENEMY_SCRATCH_PTR) = 0u;
}
