from __future__ import annotations

from .checks import (
    DoctorCheck,
    build_checks,
    detect_disk_inputs,
    extract_project_xml_path,
    extract_sentinels,
    ghidra_checks,
    inventory_db_check,
    missing_paths,
    newest_mtime,
    oldest_mtime,
    resolve_command_path,
    run_smoke,
    tool_check,
    unpack_input_sentinels,
    workflow_check,
)
from .constants import (
    EXTRACT_PROJECT_XML_CANDIDATES,
    EXTRACT_STATUS,
    INVENTORY_DB,
    INVENTORY_REQUIRED_TABLES,
    INVENTORY_SENTINELS,
    INVENTORY_STATUS,
    OPTIONAL_GHIDRA_PROJECT,
    PSX_TOOLCHAIN_NAMES,
    ROOT,
    UNPACK_SENTINELS,
    UNPACK_STATUS,
    WORKFLOW_STATUS_DIR,
)
from .parser import _build_doctor_parser, build_parser, main, parse_args
from .render import render_checks, render_checks_payload
from .service import DEFAULT_DOCTOR_SERVICE, DoctorService, _execute_args

__all__ = [
    "DEFAULT_DOCTOR_SERVICE",
    "DoctorCheck",
    "DoctorService",
    "EXTRACT_PROJECT_XML_CANDIDATES",
    "EXTRACT_STATUS",
    "INVENTORY_DB",
    "INVENTORY_REQUIRED_TABLES",
    "INVENTORY_SENTINELS",
    "INVENTORY_STATUS",
    "OPTIONAL_GHIDRA_PROJECT",
    "PSX_TOOLCHAIN_NAMES",
    "ROOT",
    "UNPACK_SENTINELS",
    "UNPACK_STATUS",
    "WORKFLOW_STATUS_DIR",
    "_build_doctor_parser",
    "_execute_args",
    "build_checks",
    "build_parser",
    "detect_disk_inputs",
    "extract_project_xml_path",
    "extract_sentinels",
    "ghidra_checks",
    "inventory_db_check",
    "main",
    "missing_paths",
    "newest_mtime",
    "oldest_mtime",
    "parse_args",
    "render_checks",
    "render_checks_payload",
    "resolve_command_path",
    "run_smoke",
    "tool_check",
    "unpack_input_sentinels",
    "workflow_check",
]
