name: battle_batl_ovr_00
sha1: e3c94ee01969e242b77482ec8c11e978c3c5d0f3
options:
  platform: psx
  compiler: psyq
  basename: battle_batl_ovr_00
  base_path: ../../../../..
  target_path: out/binaries/emi/battle/batl_ovr/00.bin
  asm_path: out/splat/emi/battle/batl_ovr/00/asm
  src_path: src/emi/battle/batl_ovr/00
  ld_script_path: out/splat/emi/battle/batl_ovr/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 0
        - asm
        - func_801EEC00
      - - 1408
        - asm
        - func_801EF180
      - - 1816
        - asm
        - func_801EF318
      - - 1972
        - asm
        - func_801EF3B4
      - - 2172
        - asm
        - func_801EF47C
  - - 0xa54
