name: etc_commu03_06
sha1: 2e7f17b5060076dccd2f93188485ba404d175eb0
options:
  platform: psx
  compiler: psyq
  basename: etc_commu03_06
  base_path: ../../../../../..
  target_path: out/binaries/emi/etc/commu03/06.bin
  asm_path: out/splat/emi/etc/commu03/06/asm
  src_path: src/emi/etc/commu03/06
  ld_script_path: out/splat/emi/etc/commu03/06/linker.ld
  undefined_funcs_auto_path: out/splat/emi/etc/commu03/06/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/etc/commu03/06/undefined_syms_auto.txt
  cache_path: out/splat/emi/etc/commu03/06/.splache
  asset_path: out/splat/emi/etc/commu03/06/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/etc/commu03/06/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149387268
  subsegments:
  - - 4
    - asm
    - D_801D0C04
  - - 1616
    - asm
    - func_801D1250
  - - 2836
    - asm
    - func_801D1714
- - 3404
