-- Native-library checks with synthetic protobufs; run as a bounded harness mission.
local m = require 'support'
m.begin('', function()
    PCSX.pauseEmulator()
    local snapshot, diff, pb = require 'snapshot', require 'difference', require 'pb'
    local checks = m.array()
    local function check(name, callback)
        callback()
        checks[#checks + 1] = name
    end
    local function reject(pattern, callback)
        local ok, error = pcall(callback)
        assert(not ok and tostring(error):find(pattern, 1, true), tostring(error))
    end
    local function state(extra)
        local value = extra or {}
        value.save_state_info = {version = 4}
        return pb.encode('SaveState', value)
    end
    local function compare(a, b, path, options)
        local left, kind, array = snapshot.select(snapshot.decode(a, true), path or '', true)
        local right = snapshot.select(snapshot.decode(b, true), path or '', true)
        return diff.compare(left, right, kind, array, path or '', options)
    end
    check('native full state equality', function()
        local bytes = tostring(PCSX.createSaveState())
        local result = compare(bytes, bytes)
        assert(result.equal and result.complete and result.compared_bytes > 20000000)
    end)
    check('scalar and repeated paths', function()
        local a = state({registers = {pc = 16, gpr = {1, 2, 3}}})
        local b = state({registers = {pc = 20, gpr = {1, 9, 3, 4}}})
        local result = compare(a, b, 'registers')
        assert(not result.equal and result.difference_count == 3)
        assert(result.differences[1].path == 'registers.gpr[2]')
        assert(result.differences[2].path == 'registers.gpr[4]')
        assert(result.differences[2].before.present == false)
        assert(result.differences[3].path == 'registers.pc')
        assert(result.differences[3].after.value == 20)
    end)
    check('encoded absence differs from explicit zero and false', function()
        pb.option('encode_default_values')
        local explicit = state({registers = {pc = 0, in_isr = false}})
        pb.option('no_encode_default_values')
        local absent = state({registers = {pc = 4}})
        local result = compare(absent, explicit, 'registers.in_isr')
        assert(result.difference_count == 1 and not result.before_present and result.after_present)
        assert(result.differences[1].after.value == false)
        result = compare(state(), explicit, 'registers.pc')
        assert(result.differences[1].after.value == 0)
    end)
    check('large integers stay exact', function()
        local a = state({registers = {cycle = '#18446744073709551614'}})
        local b = state({registers = {cycle = '#18446744073709551615'}})
        local result = compare(a, b, 'registers.cycle')
        assert(result.differences[1].before.value == '#18446744073709551614')
        assert(result.differences[1].after.value == '#18446744073709551615')
    end)
    check('contiguous byte changes cross chunk boundaries and unequal lengths', function()
        local a = state({memory = {ram = string.rep('a', 8200)}})
        local b = state({memory = {ram = string.rep('a', 4094) .. 'BCDE' .. string.rep('a', 4102) .. 'Z'}})
        local result = compare(a, b, 'memory.ram')
        assert(result.changed_bytes == 5 and result.difference_count == 2)
        assert(result.differences[1].offset == 4094 and result.differences[1].length == 4)
        assert(result.differences[2].offset == 8200 and result.differences[2].before_hex == '')
    end)
    check('byte preview truncation never truncates comparison', function()
        local result = compare(state({memory = {ram = string.rep('a', 100)}}),
            state({memory = {ram = string.rep('b', 100)}}), 'memory.ram')
        assert(result.changed_bytes == 100 and result.differences[1].length == 100)
        assert(result.differences[1].preview_truncated and #result.differences[1].before_hex == 64)
    end)
    check('explicit limits reject incomplete comparisons', function()
        local a, b = state({registers = {pc = 4, code = 1}}), state({registers = {pc = 8, code = 2}})
        reject('difference limit', function() compare(a, b, '', {limit = 1}) end)
        reject('depth exceeded', function() compare(a, b, '', {depth = 0}) end)
        reject('node limit', function() compare(a, b, '', {nodes = 1}) end)
        reject('byte limit', function() compare(state({memory = {ram = 'ab'}}), state({memory = {ram = 'ab'}}), '', {bytes = 1}) end)
    end)
    check('unknown paths and invalid indices reject', function()
        reject('unknown schema field', function() compare(state(), state(), 'registers.missing') end)
        reject('invalid state index', function() compare(state(), state(), 'registers.gpr[0]') end)
        local result = compare(state(), state(), 'registers.pc')
        assert(result.equal and not result.before_present and not result.after_present)
    end)
    check('unknown wire fields reject before native decode discards them', function()
        reject('unknown encoded field', function() snapshot.decode(state() .. '\248\127\1', true) end)
        reject('unknown encoded field', function()
            local buffer = require('pb.buffer').new()
            local _, number = pb.field('SaveState', 'registers')
            buffer:pack('vs', number * 8 + 2, '\248\127\1')
            snapshot.decode(state() .. buffer:result(), true)
        end)
    end)
    check('incompatible wire types and versions reject', function()
        local _, number = pb.field('SaveState', 'registers')
        local buffer = require('pb.buffer').new()
        buffer:pack('vv', number * 8, 0)
        reject('incompatible wire type', function() snapshot.decode(state() .. buffer:result(), true) end)
        reject('unsupported/missing state version', function()
            snapshot.decode(pb.encode('SaveState', {save_state_info = {version = 3}}), true)
        end)
        reject('duplicate singular field', function() snapshot.decode(state() .. state(), true) end)
    end)
    check('truncated messages reject', function()
        local bytes = state({memory = {ram = '12345678'}})
        local ok = pcall(snapshot.decode, bytes:sub(1, -2), true)
        assert(not ok, 'truncated field accepted')
    end)
    local function registerWire(body)
        local _, number = pb.field('SaveState', 'registers')
        return state() .. require('pb.buffer').new():pack('vs', number * 8 + 2, body):result()
    end
    check('overflowing varints reject in every wire position', function()
        local overflow = string.rep('\255', 9) .. '\3'
        reject('varint overflow', function() snapshot.decode(registerWire('\56' .. overflow), true) end)
        reject('varint overflow', function() snapshot.decode(registerWire('\138\1\10' .. overflow), true) end)
        reject('varint overflow', function() snapshot.decode(state() .. overflow, true) end)
        reject('varint overflow', function() snapshot.decode(registerWire('\10' .. overflow), true) end)
    end)
    check('narrow scalar overflow rejects', function()
        reject('32-bit varint overflow', function()
            snapshot.decode(registerWire('\40\128\128\128\128\16'), true)
        end)
        reject('invalid encoded boolean', function() snapshot.decode(registerWire('\144\1\2'), true) end)
    end)
    check('packed elements are bounded before decoding', function()
        local packed = require('pb.buffer').new():pack('vs', 10, string.rep('\1', 100001)):result()
        reject('encoded value limit', function() snapshot.decode(registerWire(packed), true) end)
    end)
    m.report('checks.json', {schema = 'psx.skill-checks/v1', checks = checks, passed = #checks})
    m.finish()
end)
