name: world04_area174_13
sha1: 36261e7ef80d1a3080d60851dd6e1be0cf427fe9
options:
  platform: psx
  compiler: psyq
  basename: world04_area174_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world04/area174/13.bin
  asm_path: out/splat/emi/world04/area174/13/asm
  src_path: src/emi/world04/area174/13
  ld_script_path: out/splat/emi/world04/area174/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 604
        - asm
        - func_801F2E5C
      - - 648
        - asm
        - func_801F2E88
      - - 708
        - asm
        - func_801F2EC4
      - - 1004
        - asm
        - func_801F2FEC
      - - 1824
        - asm
        - func_801F3320
      - - 1912
        - asm
        - func_801F3378
      - - 3416
        - asm
        - func_801F3958
      - - 7772
        - asm
        - func_801F4A5C
  - - 0x3b64
