from __future__ import annotations

import argparse
from pathlib import Path

from ..paths import repo_layout
from ..source_status import (
    analyze_all_ghidra_function_statuses,
    analyze_ghidra_programs,
    analyze_source_status,
    render_complex_table,
    render_details,
    render_function_table,
    render_function_rows,
    render_ghidra_program_table,
    render_json,
    render_module_table,
    top_complex_functions,
)
from ._common import run_main


def run_report(args: argparse.Namespace) -> int:
    include_programs = args.ghidra_programs or args.full
    include_functions = args.functions or args.full
    include_details = args.details or args.full
    layout = repo_layout()
    modules = analyze_source_status(
        layout,
        module_filter=args.module,
        asm_root=args.asm_root,
        ghidra_function_index_tsv=args.ghidra_function_index,
    )
    ghidra_programs = analyze_ghidra_programs(
        layout,
        module_filter=args.module,
        ghidra_function_index_tsv=args.ghidra_function_index,
    )
    all_ghidra_functions = (
        analyze_all_ghidra_function_statuses(
            layout,
            modules,
            ghidra_function_index_tsv=args.ghidra_function_index,
        )
        if args.all_ghidra_functions or args.full
        else []
    )
    if args.module and all_ghidra_functions:
        allowed_sources = {program.source_hint for program in ghidra_programs}
        all_ghidra_functions = [
            status
            for status in all_ghidra_functions
            if status.source_hint in allowed_sources
        ]
    complex_functions = top_complex_functions(modules, limit=args.top_complex)

    if args.format == "json":
        output = render_json(modules, complex_functions, ghidra_programs)
    else:
        parts = [render_module_table(modules)]
        if include_programs:
            parts.extend(
                ["\nghidra programs:\n", render_ghidra_program_table(ghidra_programs)]
            )
        if include_functions:
            function_rows = (
                render_function_rows(all_ghidra_functions)
                if args.all_ghidra_functions or args.full
                else render_function_table(modules)
            )
            parts.extend(["\nfunctions:\n", function_rows])
        if args.top_complex > 0:
            parts.extend(
                ["\ncomplex candidates:\n", render_complex_table(complex_functions)]
            )
        if include_details:
            parts.extend(["\ndetails:\n", render_details(modules)])
        output = "".join(parts)

    if args.output is None:
        print(output, end="")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output, encoding="utf-8")
        print(f"report: {args.output}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    layout = repo_layout()
    parser = argparse.ArgumentParser(prog="source-status")
    parser.add_argument(
        "--module",
        help="only include modules whose bof3/src-relative path contains this text",
    )
    parser.add_argument(
        "--asm-root",
        type=Path,
        default=layout.out_dir / "asm-diff",
        help="directory containing out/asm-diff-style summary.json files",
    )
    parser.add_argument(
        "--ghidra-function-index",
        type=Path,
        default=layout.inventory_ghidra_function_index_tsv_path,
        help="Ghidra function index TSV generated by inventory-import-ghidra-symbols",
    )
    parser.add_argument(
        "--ghidra-programs",
        action="store_true",
        help="include a table of all deduped Ghidra functions grouped by source program",
    )
    parser.add_argument(
        "--functions",
        action="store_true",
        help="include every merged Ghidra/source function with lifted status and match percent",
    )
    parser.add_argument(
        "--all-ghidra-functions",
        action="store_true",
        help="make --functions include every deduped Ghidra function from every code-bearing bin",
    )
    parser.add_argument(
        "--full",
        action="store_true",
        help="include Ghidra program totals, every function row, and details",
    )
    parser.add_argument(
        "--top-complex",
        type=int,
        default=10,
        help="number of high-complexity function candidates to list",
    )
    parser.add_argument(
        "--details",
        action="store_true",
        help="include variable, struct, and per-function status details",
    )
    parser.add_argument(
        "--format",
        choices=("table", "json"),
        default="table",
        help="report format",
    )
    parser.add_argument("--output", type=Path, help="write report to this path")
    parser.set_defaults(handler=run_report)
    return parser


def main(argv: list[str] | None = None) -> int:
    return run_main(build_parser, argv)


if __name__ == "__main__":
    raise SystemExit(main())
