name: scenario_scena07_00
sha1: e93b90bcf6b42f104e319428227deb8337878b89
options:
  platform: psx
  compiler: psyq
  basename: scenario_scena07_00
  base_path: ../../../../..
  target_path: out/binaries/emi/scenario/scena07/00.bin
  asm_path: out/splat/emi/scenario/scena07/00/asm
  src_path: src/emi/scenario/scena07/00
  ld_script_path: out/splat/emi/scenario/scena07/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149542912
    subsegments:
      - - 0
        - asm
        - func_801F6C00
      - - 5588
        - asm
        - func_801F81D4
      - - 5976
        - asm
        - func_801F8358
      - - 6036
        - asm
        - func_801F8394
      - - 6096
        - asm
        - func_801F83D0
      - - 6264
        - asm
        - func_801F8478
      - - 6616
        - asm
        - func_801F85D8
      - - 7352
        - asm
        - func_801F88B8
      - - 8168
        - asm
        - func_801F8BE8
      - - 9024
        - asm
        - func_801F8F40
      - - 9104
        - asm
        - func_801F8F90
      - - 9460
        - asm
        - func_801F90F4
      - - 10032
        - asm
        - func_801F9330
      - - 11232
        - asm
        - func_801F97E0
      - - 11904
        - asm
        - func_801F9A80
      - - 12252
        - asm
        - func_801F9BDC
      - - 12712
        - asm
        - func_801F9DA8
      - - 12756
        - asm
        - func_801F9DD4
      - - 12816
        - asm
        - func_801F9E10
      - - 13052
        - asm
        - func_801F9EFC
      - - 13340
        - asm
        - func_801FA01C
      - - 14220
        - asm
        - func_801FA38C
      - - 21652
        - asm
        - func_801FC094
      - - 25524
        - asm
        - func_801FCFB4
      - - 25600
        - asm
        - func_801FD000
      - - 27152
        - asm
        - func_801FD610
      - - 28212
        - asm
        - func_801FDA34
  - - 0x73cc
