name: bmagic_magic162_03
sha1: 88429b30eeebbdc1531897852fc50306f977ea05
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic162_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic162/03.bin
  asm_path: out/splat/emi/bmagic/magic162/03/asm
  src_path: src/emi/bmagic/magic162/03
  ld_script_path: out/splat/emi/bmagic/magic162/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1848
        - asm
        - func_801EF338
      - - 3084
        - asm
        - func_801EF80C
      - - 3648
        - asm
        - func_801EFA40
      - - 4312
        - asm
        - func_801EFCD8
      - - 5116
        - asm
        - func_801EFFFC
      - - 5224
        - asm
        - func_801F0068
  - - 0x2bb4
