name: world01_area041_13
sha1: 5b2e6f3cc14b743564e5a5faeb2364a4318561c0
options:
  platform: psx
  compiler: psyq
  basename: world01_area041_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world01/area041/13.bin
  asm_path: out/splat/emi/world01/area041/13/asm
  src_path: src/emi/world01/area041/13
  ld_script_path: out/splat/emi/world01/area041/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 764
        - asm
        - func_801F2EFC
      - - 1124
        - asm
        - func_801F3064
      - - 2820
        - asm
        - func_801F3704
      - - 3196
        - asm
        - func_801F387C
      - - 5400
        - asm
        - func_801F4118
      - - 6372
        - asm
        - func_801F44E4
  - - 0x2a8e
