name: world00_area020_13
sha1: f4ff8ac0a94553ab9eda50c099bd610c513c99a4
options:
  platform: psx
  compiler: psyq
  basename: world00_area020_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world00/area020/13.bin
  asm_path: out/splat/emi/world00/area020/13/asm
  src_path: src/emi/world00/area020/13
  ld_script_path: out/splat/emi/world00/area020/13/linker.ld
  undefined_funcs_auto_path: out/splat/emi/world00/area020/13/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/world00/area020/13/undefined_syms_auto.txt
  cache_path: out/splat/emi/world00/area020/13/.splache
  asset_path: out/splat/emi/world00/area020/13/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world00/area020/13/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149526532
  subsegments:
  - - 4
    - asm
    - func_801F2C04
  - - 300
    - c
    - invokeHelperWorld00Area02013_801F2D2C
  - - 332
    - asm
    - D_801F2D4C
- - 540
