name: bmagic_magic043_03
sha1: b6224bb1f71bdef008b4b677081e395feeee2ba0
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic043_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic043/03.bin
  asm_path: out/splat/emi/bmagic/magic043/03/asm
  src_path: src/emi/bmagic/magic043/03
  ld_script_path: out/splat/emi/bmagic/magic043/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic043/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic043/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic043/03/.splache
  asset_path: out/splat/emi/bmagic/magic043/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic043/03/symbols.txt
segments:
- - 0
  - bin
  - header
- - 4
  - bin
  - tabledata
- name: main
  type: code
  start: 24
  vram: 2149510168
  subsegments:
  - - 24
    - asm
    - func_801EEC18
  - - 304
    - asm
    - func_801EED30
  - - 752
    - asm
    - func_801EEEF0
  - - 920
    - asm
    - func_801EEF98
  - - 1204
    - asm
    - func_801EF0B4
  - - 1792
    - asm
    - func_801EF300
  - - 1888
    - asm
    - func_801EF360
  - - 1956
    - asm
    - func_801EF3A4
  - - 2092
    - asm
    - func_801EF42C
  - - 2396
    - asm
    - func_801EF55C
  - - 2528
    - asm
    - func_801EF5E0
  - - 2636
    - asm
    - func_801EF64C
  - - 2860
    - asm
    - func_801EF72C
  - - 3064
    - asm
    - func_801EF7F8
  - - 4132
    - asm
    - func_801EFC24
  - - 4232
    - asm
    - func_801EFC88
- - 11940
