schema = "harness.target/v2"
id = "emi/scenario/scena06/00"
disc_id = "BIN/SCENARIO/SCENA06.EMI#0"
kind = "emi"
source_dir = "src/emi/scenario/scena06/00"
binary = "out/binaries/emi/scenario/scena06/00.bin"
splat = "config/targets/emi/scenario/scena06/00/splat.yaml"
load_address = 0x801F6C00

sources = []
support_sources = [
    "src/bof3/scenario/invokeHelperArgScenarioScena0600_801FE13C.c",
    "src/bof3/scenario/invokeHelperArgScenarioScena0600_801FE11C.c",
    "src/bof3/scenario/noopHandlerScenarioScena0600_801FDE2C.c",
    "src/bof3/scenario/zeroResultScenarioScena0600_801FD294.c",
    "src/bof3/scenario/noopHandlerScenarioScena0600_801FCE10.c",
    "src/bof3/scenario/noopHandlerScenarioScena0600_801F7A3C.c",
    "src/bof3/support/scena06_00_psyq.c",
    "src/bof3/scenario/invokeHelperArgThenHelperScenarioScena0600_801FE30C.c",
    "src/bof3/scenario/invokeHelperArgThenHelperScenarioScena0600_801FE2E4.c",
    "src/bof3/scenario/setScenarioFlagBit0CScenarioScena0600_801FCF98.c",
    "src/bof3/scenario/seedSharedFieldsThenAdvanceStateScenarioScena0600_801F72D4.c",
    "src/bof3/scenario/invokeHelperArgThenHelperScenarioScena0600_801FE364.c",
    "src/bof3/scenario/invokeHelperTwiceThenHelperScenarioScena0600_801FE254.c",
    "src/bof3/scenario/invokeHelperTwiceThenHelperScenarioScena0600_801FE284.c",
    "src/bof3/scenario/invokeHelperTwiceThenHelperScenarioScena0600_801FE2B4.c",
    "src/bof3/scenario/invokeHelperTwiceThenHelperScenarioScena0600_801FE38C.c",
    "src/bof3/scenario/dispatchScenarioStateHandlerScenarioScena0600_801F7298.c",
    "src/bof3/scenario/dispatchPrimaryStateHandlerScenarioScena0600_801F7A00.c",
    "src/bof3/scenario/armEffectGroupThenInvokeTwoHelpersScenarioScena0600_801FE15C.c",
    "src/bof3/scenario/armEffectGroupThenInvokeTwoHelpersScenarioScena0600_801FE1D4.c",
    "src/bof3/scenario/dispatchRecordCallbackScenarioScena0600_801FCDD0.c",
    "src/bof3/scenario/armEffectGroupThenInvokeThreeHelpersScenarioScena0600_801FE048.c",
    "src/bof3/scenario/armEffectGroupThenInvokeThreeHelpersScenarioScena0600_801FE08C.c",
    "src/bof3/scenario/armEffectGroupThenInvokeThreeHelpersScenarioScena0600_801FE210.c",
]
psyq_source = "src/bof3/support/scena06_00_psyq.c"
