schema = "harness.target/v2"
id = "emi/world01/area049/13"
disc_id = "BIN/WORLD01/AREA049.EMI#13"
kind = "emi"
source_dir = "src/emi/world01/area049/13"
binary = "out/binaries/emi/world01/area049/13.bin"
splat = "config/splat/emi/world01/area049/13.yaml"
load_address = 0x80117000
profile = "compat/capcom97"
