name: bmagic_magic046_05
sha1: 58c9841b3164468a9be45fd5a536732e9145b713
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic046_05
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic046/05.bin
  asm_path: out/splat/emi/bmagic/magic046/05/asm
  src_path: src/emi/bmagic/magic046/05
  ld_script_path: out/splat/emi/bmagic/magic046/05/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2147707904
    subsegments:
      - - 0
        - asm
        - func_80036C00
  - - 0x200
