name: bmagic_magic151_03
sha1: 02fb1416bf57c5218edd3c18de5c0923fb9530d8
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic151_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic151/03.bin
  asm_path: out/splat/emi/bmagic/magic151/03/asm
  src_path: src/emi/bmagic/magic151/03
  ld_script_path: out/splat/emi/bmagic/magic151/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 5564
        - asm
        - func_801F01BC
      - - 5740
        - asm
        - func_801F026C
      - - 6728
        - asm
        - func_801F0648
      - - 8460
        - asm
        - func_801F0D0C
      - - 10248
        - asm
        - func_801F1408
      - - 10448
        - asm
        - func_801F14D0
      - - 12736
        - asm
        - func_801F1DC0
      - - 12912
        - asm
        - func_801F1E70
      - - 13704
        - asm
        - func_801F2188
  - - 0x3918
