name: world00_area033_13
sha1: 31dfb702e30e858bbc50a18d871be8c76d46733b
options:
  platform: psx
  compiler: psyq
  basename: world00_area033_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world00/area033/13.bin
  asm_path: out/splat/emi/world00/area033/13/asm
  src_path: src/emi/world00/area033/13
  ld_script_path: out/splat/emi/world00/area033/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 0
        - asm
        - func_801F2C00
      - - 1844
        - asm
        - func_801F3334
      - - 2044
        - asm
        - func_801F33FC
      - - 2284
        - asm
        - func_801F34EC
      - - 2496
        - asm
        - func_801F35C0
      - - 3340
        - asm
        - func_801F390C
      - - 3636
        - asm
        - func_801F3A34
      - - 4608
        - asm
        - func_801F3E00
      - - 5112
        - asm
        - func_801F3FF8
  - - 0x2446
