name: bmagic_magic118_03
sha1: 7c36da24924485be0845883a1ddd8a1383bd30a8
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic118_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic118/03.bin
  asm_path: out/splat/emi/bmagic/magic118/03/asm
  src_path: src/emi/bmagic/magic118/03
  ld_script_path: out/splat/emi/bmagic/magic118/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1428
        - asm
        - func_801EF194
      - - 2572
        - asm
        - func_801EF60C
      - - 2748
        - asm
        - func_801EF6BC
      - - 3612
        - asm
        - func_801EFA1C
  - - 0x10e0
