name: bmagic_magic094_03
sha1: 5975376eb0a5dc109ae04f7315ec3a11669161d5
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic094_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic094/03.bin
  asm_path: out/splat/emi/bmagic/magic094/03/asm
  src_path: src/emi/bmagic/magic094/03
  ld_script_path: out/splat/emi/bmagic/magic094/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 0
        - asm
        - func_801EEC00
      - - 1356
        - asm
        - func_801EF14C
      - - 2644
        - asm
        - func_801EF654
      - - 2832
        - asm
        - func_801EF710
  - - 0xd98
