name: etc_shisu_00
sha1: eb2a6029344350bec1c180d45df95e226243c9a5
options:
  platform: psx
  compiler: psyq
  basename: etc_shisu_00
  base_path: ../../../../..
  target_path: out/binaries/emi/etc/shisu/00.bin
  asm_path: out/splat/emi/etc/shisu/00/asm
  src_path: src/emi/etc/shisu/00
  ld_script_path: out/splat/emi/etc/shisu/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149387264
    subsegments:
      - - 0
        - asm
        - func_801D0C00
      - - 4260
        - asm
        - func_801D1CA4
      - - 4380
        - asm
        - func_801D1D1C
      - - 4660
        - asm
        - func_801D1E34
      - - 4704
        - asm
        - func_801D1E60
      - - 4840
        - asm
        - func_801D1EE8
      - - 5896
        - asm
        - func_801D2308
      - - 7100
        - asm
        - func_801D27BC
      - - 7544
        - asm
        - func_801D2978
      - - 7900
        - asm
        - func_801D2ADC
      - - 8204
        - asm
        - func_801D2C0C
      - - 8264
        - asm
        - func_801D2C48
      - - 8616
        - asm
        - func_801D2DA8
      - - 8676
        - asm
        - func_801D2DE4
      - - 10016
        - asm
        - func_801D3320
      - - 14528
        - asm
        - func_801D44C0
      - - 14860
        - asm
        - func_801D460C
      - - 15188
        - asm
        - func_801D4754
      - - 16116
        - asm
        - func_801D4AF4
      - - 18700
        - asm
        - func_801D550C
      - - 18976
        - asm
        - func_801D5620
      - - 19160
        - asm
        - func_801D56D8
      - - 20604
        - asm
        - func_801D5C7C
      - - 21368
        - asm
        - func_801D5F78
      - - 21648
        - asm
        - func_801D6090
      - - 26148
        - asm
        - func_801D7224
      - - 26648
        - asm
        - func_801D7418
  - - 0x9534
