schema = "harness.target/v2"
id = "emi/etc/bate/00"
disc_id = "BIN/ETC/BATE.EMI#0"
kind = "emi"
source_dir = "src/emi/etc/bate/00"
binary = "out/binaries/emi/etc/bate/00.bin"
splat = "config/targets/emi/etc/bate/00/splat.yaml"
load_address = 0x801D0C00

sources = []
support_sources = [
    "src/bof3/support/bate_00_psyq.c",
]
psyq_source = "src/bof3/support/bate_00_psyq.c"
