name: world00_area024_14
sha1: 499bf9c285ef340ddfa63c8699997020d92cd829
options:
  platform: psx
  compiler: psyq
  basename: world00_area024_14
  base_path: ../../../../..
  target_path: out/binaries/emi/world00/area024/14.bin
  asm_path: out/splat/emi/world00/area024/14/asm
  src_path: src/emi/world00/area024/14
  ld_script_path: out/splat/emi/world00/area024/14/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - [0x0, bin]
  - [0x2F04]
