name: world02_area110_13
sha1: 03b2d9578fe1d5022fb3fe2bfcb802b719c2f681
options:
  platform: psx
  compiler: psyq
  basename: world02_area110_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world02/area110/13.bin
  asm_path: out/splat/emi/world02/area110/13/asm
  src_path: src/emi/world02/area110/13
  ld_script_path: out/splat/emi/world02/area110/13/linker.ld
  undefined_funcs_auto_path: out/splat/emi/world02/area110/13/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/world02/area110/13/undefined_syms_auto.txt
  cache_path: out/splat/emi/world02/area110/13/.splache
  asset_path: out/splat/emi/world02/area110/13/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world02/area110/13/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149526532
  subsegments:
  - - 4
    - asm
    - func_801F2C04
  - - 300
    - c
    - invokeHelperWorld02Area11013_801F2D2C
  - - 332
    - asm
    - func_801F2D4C
- - 536
