name: boss_boss055_16
sha1: 12e2e5bdb3d65f7312672b86651a674e6bda4998
options:
  platform: psx
  compiler: psyq
  basename: boss_boss055_16
  base_path: ../../../../../..
  target_path: out/binaries/emi/boss/boss055/16.bin
  asm_path: out/splat/emi/boss/boss055/16/asm
  src_path: src/emi/boss/boss055/16
  ld_script_path: out/splat/emi/boss/boss055/16/linker.ld
  undefined_funcs_auto_path: out/splat/emi/boss/boss055/16/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/boss/boss055/16/undefined_syms_auto.txt
  cache_path: out/splat/emi/boss/boss055/16/.splache
  asset_path: out/splat/emi/boss/boss055/16/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/boss/boss055/16/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2148276228
  subsegments:
  - - 4
    - asm
    - func_800C1804
  - - 2124
    - asm
    - func_800C204C
  - - 2212
    - asm
    - func_800C20A4
  - - 2336
    - asm
    - func_800C2120
  - - 2392
    - asm
    - func_800C2158
  - - 2532
    - asm
    - func_800C21E4
  - - 2612
    - c
    - getAndClearBossBoss05516_800C2234
  - - 2628
    - asm
    - func_800C2244
  - - 2684
    - asm
    - func_800C227C
  - - 2800
    - asm
    - func_800C22F0
  - - 2856
    - c
    - noopHandlerBossBoss05516_800C2328
  - - 2864
    - c
    - noopHandlerBossBoss05516_800C2330
  - - 2872
    - c
    - noopHandlerBossBoss05516_800C2338
  - - 2880
    - asm
    - func_800C2340
  - - 2956
    - asm
    - func_800C238C
  - - 3232
    - asm
    - func_800C24A0
  - - 3288
    - c
    - zeroResultBossBoss05516_800C24D8
  - - 3296
    - asm
    - func_800C24E0
  - - 3764
    - c
    - invokeZeroArgBossBoss05516_800C26B4
  - - 3796
    - asm
    - func_800C26D4
  - - 3880
    - asm
    - func_800C2728
  - - 3968
    - asm
    - func_800C2780
  - - 4072
    - asm
    - func_800C27E8
  - - 4232
    - asm
    - func_800C2888
  - - 4320
    - asm
    - func_800C28E0
  - - 4424
    - asm
    - func_800C2948
  - - 4584
    - asm
    - func_800C29E8
  - - 4672
    - asm
    - func_800C2A40
  - - 4776
    - asm
    - func_800C2AA8
  - - 4936
    - asm
    - func_800C2B48
  - - 5024
    - asm
    - func_800C2BA0
  - - 5240
    - asm
    - func_800C2C78
  - - 5332
    - asm
    - func_800C2CD4
  - - 5420
    - asm
    - func_800C2D2C
  - - 5636
    - asm
    - func_800C2E04
  - - 5748
    - asm
    - func_800C2E74
  - - 5836
    - asm
    - func_800C2ECC
  - - 6052
    - asm
    - func_800C2FA4
  - - 6140
    - asm
    - func_800C2FFC
  - - 6236
    - asm
    - func_800C305C
  - - 6452
    - asm
    - func_800C3134
  - - 6640
    - asm
    - func_800C31F0
  - - 6740
    - asm
    - func_800C3254
  - - 6788
    - asm
    - func_800C3284
  - - 7380
    - asm
    - func_800C34D4
- - 7700
