schema = "harness.target/v2"
id = "emi/world02/area100/13"
disc_id = "BIN/WORLD02/AREA100.EMI#13"
kind = "emi"
source_dir = "src/emi/world02/area100/13"
binary = "out/binaries/emi/world02/area100/13.bin"
splat = "config/targets/emi/world02/area100/13/splat.yaml"
load_address = 0x801F2C00

sources = []
support_sources = [
    "src/bof3/world02/setTwoWorld02Area10013_801F3680.c",
    "src/bof3/world02/noopHandlerWorld02Area10013_801F2C74.c",
    "src/bof3/world02/advanceCounter2By4World02Area10013_801F3630.c",
    "src/bof3/world02/retreatCounter2By4World02Area10013_801F3658.c",
    "src/bof3/support/area100_13_psyq.c",
]
psyq_source = "src/bof3/support/area100_13_psyq.c"
