name: bmagic_magic082_03
sha1: 45861e989cdfdf1ca62234f68be274b9f8c68548
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic082_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic082/03.bin
  asm_path: out/splat/emi/bmagic/magic082/03/asm
  src_path: src/emi/bmagic/magic082/03
  ld_script_path: out/splat/emi/bmagic/magic082/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic082/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic082/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic082/03/.splache
  asset_path: out/splat/emi/bmagic/magic082/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic082/03/symbols.txt
segments:
- - 0
  - bin
  - header
- - 4
  - bin
  - tabledata
- name: main
  type: code
  start: 28
  vram: 2149510172
  subsegments:
  - - 28
    - asm
    - func_801EEC1C
  - - 148
    - asm
    - func_801EEC94
  - - 780
    - asm
    - func_801EEF0C
  - - 948
    - asm
    - func_801EEFB4
  - - 1220
    - asm
    - func_801EF0C4
  - - 1292
    - asm
    - func_801EF10C
  - - 1876
    - asm
    - func_801EF354
  - - 1952
    - asm
    - func_801EF3A0
  - - 2236
    - asm
    - func_801EF4BC
  - - 2412
    - asm
    - func_801EF56C
  - - 2480
    - asm
    - func_801EF5B0
  - - 2608
    - asm
    - func_801EF630
  - - 2688
    - asm
    - func_801EF680
  - - 2756
    - asm
    - func_801EF6C4
  - - 2848
    - asm
    - func_801EF720
  - - 3584
    - asm
    - func_801EFA00
  - - 4400
    - asm
    - func_801EFD30
  - - 4468
    - asm
    - func_801EFD74
  - - 4544
    - asm
    - func_801EFDC0
  - - 4852
    - asm
    - func_801EFEF4
  - - 5096
    - asm
    - func_801EFFE8
  - - 5340
    - asm
    - func_801F00DC
  - - 5728
    - asm
    - func_801F0260
  - - 6112
    - asm
    - func_801F03E0
  - - 7812
    - asm
    - func_801F0A84
  - - 8348
    - asm
    - D_801F0C9C
- - 8512
