name: world01_area044_13
sha1: 12a6e3f549ad0b1d93dc1f99c048062f4808d0e0
options:
  platform: psx
  compiler: psyq
  basename: world01_area044_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world01/area044/13.bin
  asm_path: out/splat/emi/world01/area044/13/asm
  src_path: src/emi/world01/area044/13
  ld_script_path: out/splat/emi/world01/area044/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 500
        - asm
        - func_801F2DF4
      - - 1420
        - asm
        - func_801F318C
  - - 0x13d8
