"""m2c decompiler integration: toolchain wrapper and input preparation."""

from __future__ import annotations

import re
from pathlib import Path

from ..domain import FunctionId
from ..analysis.type_context import type_context
from ..domain.claims import (
    manifest_header_paths,
    resolve_manifest_source_for_address,
)
from ..domain.manifests import TargetManifest
from ..domain.symbols import load_target_symbols
from ..io import repo_layout
from .base import PythonScriptSubmoduleToolchain

_FUNC = re.compile(r"^func_[0-9a-fA-F]{8}$")


class M2cToolchain(PythonScriptSubmoduleToolchain):
    label = "m2c"
    submodule = "third_party/m2c"
    script = "m2c.py"


def splat_assembly(manifest: TargetManifest, address: int) -> Path:
    """Return the Splat assembly file for one function, or fail loudly."""
    root = repo_layout().root
    directory = root / "out" / "splat" / manifest.id.value / "asm"
    expected = directory / f"func_{address:08X}.s"
    if expected.is_file():
        return expected
    for symbol in load_target_symbols(root, manifest.id.value):
        if symbol.address == address:
            named = directory / f"{symbol.name}.s"
            if named.is_file():
                return named
            break
    raise FileNotFoundError(
        f"Splat assembly not found: {expected}; run the target's Splat split first"
    )


def context_path(function: FunctionId) -> Path:
    """Return the deterministic m2c context destination for one function."""
    return (
        repo_layout().out_dir
        / "m2ctx"
        / function.target.value
        / f"{function.address:08X}.c"
    )


def render_context(function: FunctionId, manifest: TargetManifest) -> str:
    """Render the minimal deterministic m2c context owned by one target.

    m2c consumes declarations rather than a preprocessor configuration.  The
    generated context therefore records the target-owned headers and emits
    conservative old-style declarations for target-map symbols.  It never
    imports another target's source or map.
    """

    root = repo_layout().root
    symbols = load_target_symbols(root, manifest.id.value)
    base_context = type_context(
        root,
        manifest.id.value,
        "u8 " + " ".join(symbol.name for symbol in symbols),
    )
    lines = [
        "/* Generated by bin/m2ctx; do not edit. */",
        f"/* target: {manifest.id.value}; function: 0x{function.address:08X} */",
        *base_context.rstrip().splitlines(),
        "",
    ]
    resolve_manifest_source_for_address(root, manifest, function.address)
    headers = manifest_header_paths(root, manifest)
    context_header = root / "include" / "bof3" / "context.h"
    if context_header not in headers:
        headers.append(context_header)
    for header in headers:
        if header.is_file():
            try:
                relative = header.relative_to(root).as_posix()
            except ValueError:
                relative = str(header)
            lines.append(f"/* owning declaration source: {relative} */")
    if headers:
        lines.append("")
    for symbol in symbols:
        if symbol.name.startswith("func_") or _FUNC.fullmatch(symbol.name):
            lines.append(f"extern void {symbol.name}();")
        elif symbol.name.startswith("D_"):
            lines.append(f"extern u8 {symbol.name}[];")
    return "\n".join(lines) + "\n"


def asm_label(path: Path) -> str:
    """Return the first glabel of a Splat assembly file."""
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = re.match(r"\s*glabel\s+(\S+)", line)
        if match:
            return match.group(1)
    raise ValueError(f"no glabel found in {path}")
