name: bmagic_magic124_03
sha1: bc980807eff0843ade3bcce00b4c3351e44709ce
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic124_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic124/03.bin
  asm_path: out/splat/emi/bmagic/magic124/03/asm
  src_path: src/emi/bmagic/magic124/03
  ld_script_path: out/splat/emi/bmagic/magic124/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic124/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic124/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic124/03/.splache
  asset_path: out/splat/emi/bmagic/magic124/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic124/03/symbols.txt
segments:
- - 0
  - bin
  - header
- - 4
  - bin
  - tabledata
- name: main
  type: code
  start: 20
  vram: 2149510164
  subsegments:
  - - 20
    - asm
    - func_801EEC14
  - - 472
    - asm
    - func_801EEDD8
  - - 904
    - asm
    - func_801EEF88
  - - 1008
    - asm
    - func_801EEFF0
  - - 1104
    - asm
    - func_801EF050
  - - 1200
    - asm
    - func_801EF0B0
  - - 1640
    - c
    - noopHandlerBmagicMagic12403_801EF268
  - - 1648
    - asm
    - func_801EF270
  - - 1716
    - asm
    - func_801EF2B4
  - - 2044
    - asm
    - func_801EF3FC
  - - 2440
    - asm
    - func_801EF588
  - - 2520
    - asm
    - func_801EF5D8
  - - 2644
    - asm
    - func_801EF654
  - - 2792
    - asm
    - func_801EF6E8
  - - 5644
    - asm
    - func_801F020C
  - - 5772
    - asm
    - func_801F028C
  - - 5884
    - asm
    - func_801F02FC
  - - 5992
    - asm
    - func_801F0368
  - - 6112
    - asm
    - func_801F03E0
  - - 6580
    - asm
    - func_801F05B4
  - - 7208
    - asm
    - func_801F0828
  - - 7308
    - asm
    - func_801F088C
  - - 7388
    - asm
    - func_801F08DC
- - 15104
