name: world03_area118_13
sha1: 14e066605d33f4d4c30e3ccbe5689da220d91be6
options:
  platform: psx
  compiler: psyq
  basename: world03_area118_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world03/area118/13.bin
  asm_path: out/splat/emi/world03/area118/13/asm
  src_path: src/emi/world03/area118/13
  ld_script_path: out/splat/emi/world03/area118/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 1956
        - asm
        - func_801F33A4
      - - 3100
        - asm
        - func_801F381C
      - - 5752
        - asm
        - func_801F4278
      - - 6140
        - asm
        - func_801F43FC
      - - 6708
        - asm
        - func_801F4634
      - - 7392
        - asm
        - func_801F48E0
      - - 8200
        - asm
        - func_801F4C08
  - - 0x2df0
