name: bmagic_magic144_03
sha1: ee0b0e3e5e013ca292d46af26087f2b35298f288
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic144_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic144/03.bin
  asm_path: out/splat/emi/bmagic/magic144/03/asm
  src_path: src/emi/bmagic/magic144/03
  ld_script_path: out/splat/emi/bmagic/magic144/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1508
        - asm
        - func_801EF1E4
      - - 1684
        - asm
        - func_801EF294
      - - 2320
        - asm
        - func_801EF510
      - - 3096
        - asm
        - func_801EF818
      - - 5584
        - asm
        - func_801F01D0
      - - 6252
        - asm
        - func_801F046C
  - - 0x2f8c
