name: world02_area111_13
sha1: 03973d69ae75c74379b85e2a0ad91eb99fb5da5a
options:
  platform: psx
  compiler: psyq
  basename: world02_area111_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world02/area111/13.bin
  asm_path: out/splat/emi/world02/area111/13/asm
  src_path: src/emi/world02/area111/13
  ld_script_path: out/splat/emi/world02/area111/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 416
        - asm
        - func_801F2DA0
      - - 1604
        - asm
        - func_801F3244
      - - 6416
        - asm
        - func_801F4510
      - - 6660
        - asm
        - func_801F4604
  - - 0x3034
