name: bmagic_magic103_03
sha1: 532ac25aed3bc1dab9b46e5a5174a95017ec0591
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic103_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic103/03.bin
  asm_path: out/splat/emi/bmagic/magic103/03/asm
  src_path: src/emi/bmagic/magic103/03
  ld_script_path: out/splat/emi/bmagic/magic103/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1320
        - asm
        - func_801EF128
      - - 1496
        - asm
        - func_801EF1D8
      - - 4640
        - asm
        - func_801EFE20
      - - 6368
        - asm
        - func_801F04E0
  - - 0x1be4
