name: boss_boss015_16
sha1: d901bab020d4366d2251d646382624ddd7bf9ad3
options:
  platform: psx
  compiler: psyq
  basename: boss_boss015_16
  base_path: ../../../../../..
  target_path: out/binaries/emi/boss/boss015/16.bin
  asm_path: out/splat/emi/boss/boss015/16/asm
  src_path: src/emi/boss/boss015/16
  ld_script_path: out/splat/emi/boss/boss015/16/linker.ld
  undefined_funcs_auto_path: out/splat/emi/boss/boss015/16/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/boss/boss015/16/undefined_syms_auto.txt
  cache_path: out/splat/emi/boss/boss015/16/.splache
  asset_path: out/splat/emi/boss/boss015/16/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/boss/boss015/16/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2148276228
  subsegments:
  - - 4
    - asm
    - func_800C1804
  - - 72
    - asm
    - func_800C1848
  - - 160
    - asm
    - func_800C18A0
  - - 216
    - c
    - noopHandlerBoss015_800C18D8
  - - 224
    - c
    - noopHandlerBoss015_800C18E0
  - - 232
    - c
    - noopHandlerBoss015_800C18E8
  - - 240
    - asm
    - func_800C18F0
  - - 296
    - c
    - zeroResultBoss015_800C1928
  - - 304
    - asm
    - func_800C1930
  - - 380
    - c
    - invokeHelperArgBossBoss01516_800C197C
  - - 412
    - asm
    - D_800C199C
- - 492
