"""Canonical target-local symbol maps and generated weak bindings.

The map format deliberately stays Splat's small ``name = 0xADDRESS;`` syntax.
This module is the single parser so command-line tools, Rizin replay, C context,
and link bindings cannot each grow a subtly different spelling rule.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re


_ENTRY = re.compile(
    r"^\s*(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*"
    r"(?P<address>0x[0-9A-Fa-f]{1,8})\s*;\s*(?://.*)?$"
)
_RAW_FUNCTION = re.compile(r"^func_[0-9A-F]{8}$")
_RAW_DATA = re.compile(r"^(?:D|DAT)_[0-9A-F]{8}$")


@dataclass(frozen=True, order=True)
class Symbol:
    address: int
    name: str

    @property
    def canonical_name(self) -> str:
        if self.name.startswith("DAT_"):
            return "D_" + self.name[4:].upper()
        if self.name.startswith("D_"):
            return "D_" + self.name[2:].upper()
        if self.name.startswith("func_"):
            return "func_" + self.name[5:].upper()
        return self.name

    @property
    def is_raw(self) -> bool:
        name = self.canonical_name
        return bool(_RAW_FUNCTION.fullmatch(name) or _RAW_DATA.fullmatch(name))


def parse_map(text: str, *, source: str = "map") -> list[Symbol]:
    """Parse one Splat map and reject malformed, ambiguous entries."""

    result: list[Symbol] = []
    for line_number, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith("//") or stripped.startswith("#"):
            continue
        match = _ENTRY.match(line)
        if match is None:
            raise ValueError(f"{source}:{line_number}: expected 'name = 0xADDRESS;'")
        result.append(Symbol(int(match.group("address"), 16), match.group("name")))
    validate_symbols(result, source=source)
    return sorted((Symbol(row.address, row.canonical_name) for row in result))


def validate_symbols(symbols: list[Symbol], *, source: str = "map") -> None:
    names: dict[str, Symbol] = {}
    folded: dict[str, Symbol] = {}
    addresses: dict[int, Symbol] = {}
    for symbol in symbols:
        name = symbol.canonical_name
        if name in names:
            raise ValueError(f"{source}: duplicate symbol name: {name}")
        if name.casefold() in folded:
            other = folded[name.casefold()]
            raise ValueError(f"{source}: case-only collision: {other.name} and {name}")
        if (
            symbol.address in addresses
            and addresses[symbol.address].canonical_name != name
        ):
            other = addresses[symbol.address]
            raise ValueError(
                f"{source}: address collision 0x{symbol.address:08X}: "
                f"{other.name} and {name}"
            )
        names[name] = symbol
        folded[name.casefold()] = symbol
        addresses[symbol.address] = symbol


def load_map(path: Path) -> list[Symbol]:
    if not path.is_file():
        return []
    return parse_map(path.read_text(encoding="utf-8"), source=str(path))


def format_map(symbols: list[Symbol]) -> str:
    validate_symbols(symbols)
    return "".join(
        f"{symbol.canonical_name} = 0x{symbol.address:08X};\n"
        for symbol in sorted(symbols)
    )


def map_path(root: Path, target: str) -> Path:
    return root / "config" / "targets" / target / "symbols.txt"


def shared_map_path(root: Path) -> Path:
    return root / "config" / "targets" / "shared" / "symbols.txt"


def sdk_map_path(root: Path, space: str) -> Path:
    return root / "config" / "sdk" / f"psyq-{space}.txt"


def load_target_symbols(root: Path, target: str) -> list[Symbol]:
    """Compose shared base + PSX SDK (by target space) + target-local symbols.

    Local wins on conflict.
    """
    from .domain import load_target_manifests  # local import avoids a module cycle

    manifests = load_target_manifests(root)
    space = manifests[target].psyq_space if target in manifests else "slus"
    shared = load_map(shared_map_path(root))
    sdk = load_map(sdk_map_path(root, space))
    local = load_map(map_path(root, target))
    by_addr: dict[int, Symbol] = {s.address: s for s in shared}
    for s in sdk:
        by_addr[s.address] = s
    for s in local:
        by_addr[s.address] = s
    return sorted(by_addr.values())


def write_map(path: Path, symbols: list[Symbol]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(format_map(symbols), encoding="utf-8")


def weak_bindings_c(symbols: list[Symbol]) -> str:
    """Render disposable bindings; normal C definitions override these symbols."""

    validate_symbols(symbols)
    lines = [
        "/* Generated by bin/symbols; do not edit. */",
        '#include "bof3/symbols.h"',
        "",
    ]
    lines.extend(
        f"WEAK_SYMBOL_AT({symbol.canonical_name}, 0x{symbol.address:08X});"
        for symbol in sorted(symbols)
    )
    return "\n".join(lines) + "\n"
