"""Target-qualified, reproducible Rizin project recipes.

The generated ``project.rzdb`` file is deliberately a replay script, rather
than a user-home Rizin project.  Keeping it beside the target snapshot makes a
project reproducible from the target manifest, the map, and reviewed replay.
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path

from .analyzer import EngineIdentity, build_snapshot, find_engine
from .binaries import SPLAT_FUNCTION_SUBSEGMENT_RE
from .canonical import Symbol, load_map, map_path
from .domain import load_target_manifests, normalize_target_id
from .snapshot import snapshot_path, write_snapshot


SCHEMA = "bof3.rizin-project/v1"


@dataclass(frozen=True)
class RizinProject:
    target: str
    binary: Path
    load_address: int
    project_path: Path
    metadata_path: Path
    snapshot: Path
    replay: Path


def _atomic_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        Path(temporary).replace(path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise


def _project_dir(root: Path, target: str) -> Path:
    return root / "out" / "rizin" / target


def _reviewed_addresses(root: Path, splat: Path, load_address: int) -> set[int]:
    if not splat.is_file():
        return set()
    addresses: set[int] = set()
    for line in splat.read_text(encoding="utf-8").splitlines():
        match = SPLAT_FUNCTION_SUBSEGMENT_RE.match(line)
        if match is not None:
            addresses.add(load_address + int(match.group("offset"), 0))
    return addresses


def _rizin_replay(symbols: list[Symbol], reviewed: set[int]) -> str:
    """Return the portable, generated portion of a target replay script."""

    lines = [
        "# Generated by bin/rz-project; do not edit.",
        "e asm.arch=mips",
        "e asm.bits=32",
        "e cfg.bigendian=false",
        "e scr.color=0",
        "fs bof3",
    ]
    for address in sorted(reviewed):
        lines.append(f"af @ 0x{address:08X}")
    for symbol in symbols:
        if symbol.canonical_name.startswith("func_"):
            lines.extend(
                [
                    f"af @ 0x{symbol.address:08X}",
                    f"afn {symbol.canonical_name} 0x{symbol.address:08X}",
                ]
            )
        else:
            lines.append(f"f {symbol.canonical_name} 4 @ 0x{symbol.address:08X}")
    return "\n".join(lines) + "\n"


def prepare_project(root: Path, target_id: str) -> RizinProject:
    """Materialize deterministic replay and metadata without analyzing bytes."""

    target = normalize_target_id(target_id).value
    manifest = load_target_manifests(root).get(target)
    if manifest is None:
        raise ValueError(f"unknown target: {target_id}")
    binary = root / manifest.binary
    if not binary.is_file():
        raise FileNotFoundError(f"target binary not found: {manifest.binary}")
    directory = _project_dir(root, target)
    project_path = directory / "project.rzdb"
    metadata_path = directory / "project.json"
    reviewed = _reviewed_addresses(root, root / manifest.splat, manifest.load_address)
    symbols = load_map(map_path(root, target))
    tracked_replay = root / "config" / "analysis" / target / "reviewed.rz"
    # Once exported, the tracked replay is already the complete canonical
    # recipe.  Before then, use a generated recipe from the map and Splat.
    replay = (
        tracked_replay.read_text(encoding="utf-8")
        if tracked_replay.is_file()
        else _rizin_replay(symbols, reviewed)
    )
    _atomic_text(project_path, replay)
    metadata = {
        "schema": SCHEMA,
        "target": target,
        "binary": manifest.binary,
        "binary_sha256": hashlib.sha256(binary.read_bytes()).hexdigest(),
        "load_address": manifest.load_address,
        "architecture": "mips",
        "bits": 32,
        "big_endian": False,
        "map": map_path(root, target).relative_to(root).as_posix(),
        "reviewed_replay": (
            tracked_replay.relative_to(root).as_posix() if tracked_replay.is_file() else None
        ),
    }
    _atomic_text(metadata_path, json.dumps(metadata, indent=2, sort_keys=True) + "\n")
    return RizinProject(
        target=target,
        binary=binary,
        load_address=manifest.load_address,
        project_path=project_path,
        metadata_path=metadata_path,
        snapshot=snapshot_path(root, target),
        replay=tracked_replay,
    )


def analyze_project(root: Path, target_id: str, *, deep: bool = False, timeout: int = 120) -> RizinProject:
    """Rebuild one generated snapshot with Rizin only.

    ``deep`` is intentionally metadata-only for now: the reviewed boundaries
    remain authoritative, while broad discoveries stay in the generated
    snapshot and are never written back automatically.
    """

    project = prepare_project(root, target_id)
    manifest = load_target_manifests(root)[project.target]
    engine = find_engine("rizin")
    snapshot = build_snapshot(
        engine,
        project.binary,
        project.load_address,
        project.target,
        reviewed_addresses=_reviewed_addresses(root, root / manifest.splat, project.load_address),
        source_dir=root / manifest.source_dir,
        timeout=timeout if not deep else max(timeout, 240),
    )
    write_snapshot(snapshot, project.snapshot)
    return project


def status(root: Path, target_id: str) -> dict[str, object]:
    project = prepare_project(root, target_id)
    metadata = json.loads(project.metadata_path.read_text(encoding="utf-8"))
    snapshot_exists = project.snapshot.is_file()
    fresh = False
    if snapshot_exists:
        try:
            payload = json.loads(project.snapshot.read_text(encoding="utf-8"))
            fresh = (
                payload.get("target") == project.target
                and payload.get("engine", {}).get("name") == "rizin"
                and payload.get("inputs", {}).get("binary_sha256") == metadata["binary_sha256"]
            )
        except (OSError, ValueError, json.JSONDecodeError):
            fresh = False
    return {
        "target": project.target,
        "project": str(project.project_path.relative_to(root)),
        "snapshot": str(project.snapshot.relative_to(root)),
        "snapshot_exists": snapshot_exists,
        "fresh": fresh,
        "binary_sha256": metadata["binary_sha256"],
    }


def rizin_argv(project: RizinProject, engine: EngineIdentity) -> list[str]:
    """Return a safe argv for an interactive target-isolated Rizin session."""

    return [
        str(engine.executable),
        "-N",
        "-n",
        "-a",
        "mips",
        "-b",
        "32",
        "-e",
        "cfg.bigendian=false",
        "-m",
        f"0x{project.load_address:08X}",
        "-i",
        str(project.project_path),
        str(project.binary),
    ]


def export_patch(root: Path, target_id: str, *, write: bool = False) -> str:
    """Render (and optionally persist) reviewed Rizin replay/map formatting."""

    project = prepare_project(root, target_id)
    manifest = load_target_manifests(root)[project.target]
    symbols = load_map(map_path(root, project.target))
    replay = _rizin_replay(
        symbols, _reviewed_addresses(root, root / manifest.splat, project.load_address)
    )
    if write:
        _atomic_text(project.replay, replay)
        prepare_project(root, project.target)
    patch = [f"--- config/symbols/{project.target}.txt", f"+++ config/analysis/{project.target}/reviewed.rz"]
    patch.extend(f"+{line}" for line in replay.splitlines())
    return "\n".join(patch) + "\n"


__all__ = [
    "RizinProject",
    "analyze_project",
    "export_patch",
    "prepare_project",
    "rizin_argv",
    "status",
]
