name: bmagic_magic001_00
sha1: dc7830222bb6c6c0c58a3c1ab69d84363d20270b
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic001_00
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic001/00.bin
  asm_path: out/splat/emi/bmagic/magic001/00/asm
  src_path: src/emi/bmagic/magic001/00
  ld_script_path: out/splat/emi/bmagic/magic001/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 5452
        - asm
        - func_801F014C
      - - 5688
        - asm
        - func_801F0238
  - - 0x18bc
