name: plchar_plp567_00
sha1: 626b6adf5d09e0fa66d24eea2efde6bfbeaa6fda
options:
  platform: psx
  compiler: psyq
  basename: plchar_plp567_00
  base_path: ../../../../..
  target_path: out/binaries/emi/plchar/plp567/00.bin
  asm_path: out/splat/emi/plchar/plp567/00/asm
  src_path: src/emi/plchar/plp567/00
  ld_script_path: out/splat/emi/plchar/plp567/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149377024
    subsegments:
      - - 0
        - asm
        - func_801CE400
      - - 3620
        - asm
        - func_801CF224
      - - 4144
        - asm
        - func_801CF430
      - - 5024
        - asm
        - func_801CF7A0
      - - 5444
        - asm
        - func_801CF944
      - - 7924
        - asm
        - func_801D02F4
      - - 8428
        - asm
        - func_801D04EC
      - - 8656
        - asm
        - func_801D05D0
  - - 0x2408
