name: bmagic_magic222_03
sha1: 559fb2fe28498452ab814f8e6c9e2e7ee35bb874
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic222_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic222/03.bin
  asm_path: out/splat/emi/bmagic/magic222/03/asm
  src_path: src/emi/bmagic/magic222/03
  ld_script_path: out/splat/emi/bmagic/magic222/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic222/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic222/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic222/03/.splache
  asset_path: out/splat/emi/bmagic/magic222/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic222/03/symbols.txt
segments:
- - 0
  - bin
  - header
- - 4
  - bin
  - tabledata
- name: main
  type: code
  start: 16
  vram: 2149510160
  subsegments:
  - - 16
    - asm
    - func_801EEC10
  - - 112
    - asm
    - func_801EEC70
  - - 544
    - asm
    - func_801EEE20
  - - 640
    - asm
    - func_801EEE80
  - - 736
    - asm
    - func_801EEEE0
  - - 804
    - asm
    - func_801EEF24
  - - 968
    - asm
    - func_801EEFC8
  - - 1352
    - asm
    - func_801EF148
  - - 1652
    - asm
    - func_801EF274
  - - 1828
    - asm
    - func_801EF324
  - - 2120
    - asm
    - func_801EF448
  - - 2288
    - asm
    - func_801EF4F0
  - - 2468
    - asm
    - func_801EF5A4
  - - 2612
    - asm
    - func_801EF634
  - - 2760
    - asm
    - func_801EF6C8
  - - 2852
    - asm
    - func_801EF724
  - - 2928
    - asm
    - func_801EF770
  - - 3020
    - asm
    - func_801EF7CC
  - - 3196
    - asm
    - func_801EF87C
  - - 3788
    - asm
    - func_801EFACC
  - - 4588
    - asm
    - func_801EFDEC
  - - 4724
    - asm
    - func_801EFE74
  - - 4988
    - asm
    - func_801EFF7C
  - - 5232
    - asm
    - func_801F0070
  - - 5480
    - asm
    - func_801F0168
  - - 5656
    - asm
    - func_801F0218
  - - 6404
    - asm
    - func_801F0504
  - - 6532
    - asm
    - func_801F0584
  - - 6684
    - asm
    - func_801F061C
  - - 6764
    - asm
    - func_801F066C
  - - 6856
    - asm
    - func_801F06C8
  - - 6960
    - asm
    - func_801F0730
  - - 7080
    - asm
    - func_801F07A8
  - - 8532
    - asm
    - func_801F0D54
- - 8620
