name: world04_area166_13
sha1: 3ef8110ef74fd99750940179438687118587bd35
options:
  platform: psx
  compiler: psyq
  basename: world04_area166_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world04/area166/13.bin
  asm_path: out/splat/emi/world04/area166/13/asm
  src_path: src/emi/world04/area166/13
  ld_script_path: out/splat/emi/world04/area166/13/linker.ld
  undefined_funcs_auto_path: out/splat/emi/world04/area166/13/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/world04/area166/13/undefined_syms_auto.txt
  cache_path: out/splat/emi/world04/area166/13/.splache
  asset_path: out/splat/emi/world04/area166/13/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world04/area166/13/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149526532
  subsegments:
  - - 4
    - asm
    - func_801F2C04
  - - 72
    - asm
    - func_801F2C48
  - - 440
    - asm
    - func_801F2DB8
  - - 760
    - asm
    - func_801F2EF8
  - - 852
    - asm
    - func_801F2F54
  - - 1124
    - asm
    - func_801F3064
  - - 1236
    - asm
    - func_801F30D4
  - - 2072
    - asm
    - func_801F3418
  - - 2140
    - asm
    - func_801F345C
  - - 2408
    - asm
    - func_801F3568
  - - 2488
    - asm
    - func_801F35B8
  - - 2612
    - asm
    - func_801F3634
  - - 2676
    - asm
    - func_801F3674
  - - 2840
    - asm
    - D_801F3718
  - - 3092
    - asm
    - D_801F3814
- - 3402
