name: bmagic_magic074_03
sha1: 1c29db7f96e2907ba7532f6b3e2bf789b44f34bf
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic074_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic074/03.bin
  asm_path: out/splat/emi/bmagic/magic074/03/asm
  src_path: src/emi/bmagic/magic074/03
  ld_script_path: out/splat/emi/bmagic/magic074/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 0
        - asm
        - func_801EEC00
      - - 2832
        - asm
        - func_801EF710
      - - 4068
        - asm
        - func_801EFBE4
      - - 4632
        - asm
        - func_801EFE18
      - - 5296
        - asm
        - func_801F00B0
      - - 6100
        - asm
        - func_801F03D4
      - - 6208
        - asm
        - func_801F0440
  - - 0x34e0
