name: bmagic_magic222_03
sha1: 559fb2fe28498452ab814f8e6c9e2e7ee35bb874
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic222_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic222/03.bin
  asm_path: out/splat/emi/bmagic/magic222/03/asm
  src_path: src/emi/bmagic/magic222/03
  ld_script_path: out/splat/emi/bmagic/magic222/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 3020
        - asm
        - func_801EF7CC
      - - 3196
        - asm
        - func_801EF87C
      - - 3788
        - asm
        - func_801EFACC
      - - 5480
        - asm
        - func_801F0168
      - - 5656
        - asm
        - func_801F0218
      - - 7080
        - asm
        - func_801F07A8
  - - 0x21ac
