name: bmagic_magic050_03
sha1: b64cd89c8bdfe103bea39e54daaefc00e91d811e
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic050_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic050/03.bin
  asm_path: out/splat/emi/bmagic/magic050/03/asm
  src_path: src/emi/bmagic/magic050/03
  ld_script_path: out/splat/emi/bmagic/magic050/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1456
        - asm
        - func_801EF1B0
      - - 2244
        - asm
        - func_801EF4C4
      - - 3224
        - asm
        - func_801EF898
  - - 0xefc
