name: etc_bate_00
sha1: 89214678b147646e36ab96688077f7dff8ee0320
options:
  platform: psx
  compiler: psyq
  basename: etc_bate_00
  base_path: ../../../../..
  target_path: out/binaries/emi/etc/bate/00.bin
  asm_path: out/splat/emi/etc/bate/00/asm
  src_path: src/emi/etc/bate/00
  ld_script_path: out/splat/emi/etc/bate/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149387264
    subsegments:
      - - 3768
        - asm
        - func_801D1AB8
      - - 4240
        - asm
        - func_801D1C90
      - - 4748
        - asm
        - func_801D1E8C
      - - 5024
        - asm
        - func_801D1FA0
      - - 5892
        - asm
        - func_801D2304
      - - 6556
        - asm
        - func_801D259C
      - - 6880
        - asm
        - func_801D26E0
      - - 10520
        - asm
        - func_801D3518
      - - 10852
        - asm
        - func_801D3664
      - - 11180
        - asm
        - func_801D37AC
      - - 12108
        - asm
        - func_801D3B4C
      - - 14692
        - asm
        - func_801D4564
      - - 14968
        - asm
        - func_801D4678
      - - 15152
        - asm
        - func_801D4730
      - - 17360
        - asm
        - func_801D4FD0
      - - 22140
        - asm
        - func_801D627C
      - - 22640
        - asm
        - func_801D6470
      - - 27816
        - asm
        - func_801D78A8
  - - 0x8448
