name: bmagic_magic067_03
sha1: b502453e52e342dd646ada330fed3e6863411773
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic067_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic067/03.bin
  asm_path: out/splat/emi/bmagic/magic067/03/asm
  src_path: src/emi/bmagic/magic067/03
  ld_script_path: out/splat/emi/bmagic/magic067/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic067/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic067/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic067/03/.splache
  asset_path: out/splat/emi/bmagic/magic067/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic067/03/symbols.txt
segments:
- - 0
  - bin
  - header
- - 4
  - bin
  - tabledata
- name: main
  type: code
  start: 36
  vram: 2149510180
  subsegments:
  - - 36
    - asm
    - func_801EEC24
  - - 148
    - asm
    - func_801EEC94
  - - 828
    - asm
    - func_801EEF3C
  - - 932
    - asm
    - func_801EEFA4
  - - 1040
    - asm
    - func_801EF010
  - - 1668
    - asm
    - func_801EF284
  - - 1744
    - asm
    - func_801EF2D0
  - - 1812
    - asm
    - func_801EF314
  - - 1932
    - asm
    - func_801EF38C
  - - 2124
    - asm
    - func_801EF44C
  - - 2292
    - asm
    - func_801EF4F4
  - - 2460
    - asm
    - func_801EF59C
  - - 2696
    - asm
    - func_801EF688
  - - 2972
    - asm
    - func_801EF79C
  - - 4900
    - asm
    - func_801EFF24
  - - 5004
    - asm
    - func_801EFF8C
  - - 5068
    - asm
    - func_801EFFCC
  - - 5148
    - asm
    - func_801F001C
  - - 5224
    - asm
    - func_801F0068
  - - 5316
    - asm
    - func_801F00C4
  - - 5792
    - asm
    - func_801F02A0
  - - 5860
    - asm
    - func_801F02E4
  - - 5948
    - asm
    - func_801F033C
  - - 6028
    - asm
    - func_801F038C
  - - 6124
    - asm
    - func_801F03EC
  - - 6204
    - asm
    - func_801F043C
  - - 6296
    - c
    - invokeHelperBmagicMagic06703_801F0498
  - - 6328
    - asm
    - func_801F04B8
- - 6384
