name: bmagic_magic041_03
sha1: 6d7996bb62cfa9f0eb8054387efb679d20130d42
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic041_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic041/03.bin
  asm_path: out/splat/emi/bmagic/magic041/03/asm
  src_path: src/emi/bmagic/magic041/03
  ld_script_path: out/splat/emi/bmagic/magic041/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 2496
        - asm
        - func_801EF5C0
      - - 2672
        - asm
        - func_801EF670
      - - 3768
        - asm
        - func_801EFAB8
  - - 0x1194
