name: world02_area108_14
sha1: 0585ea5d348f77d3ef9c09b460c0446f2eb440a8
options:
  platform: psx
  compiler: psyq
  basename: world02_area108_14
  base_path: ../../../../..
  target_path: out/binaries/emi/world02/area108/14.bin
  asm_path: out/splat/emi/world02/area108/14/asm
  src_path: src/emi/world02/area108/14
  ld_script_path: out/splat/emi/world02/area108/14/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 320
        - asm
        - func_801F2D40
      - - 796
        - asm
        - func_801F2F1C
      - - 968
        - asm
        - func_801F2FC8
      - - 1076
        - asm
        - func_801F3034
      - - 1564
        - asm
        - func_801F321C
      - - 2232
        - asm
        - func_801F34B8
      - - 2440
        - asm
        - func_801F3588
      - - 4000
        - asm
        - func_801F3BA0
      - - 4228
        - asm
        - func_801F3C84
      - - 4496
        - asm
        - func_801F3D90
      - - 5472
        - asm
        - func_801F4160
      - - 10736
        - asm
        - func_801F55F0
  - - 0x37f0
