name: world04_area152_13
sha1: d5ae0090be2982f5ce014714b2d83a3c0b4f4ec5
options:
  platform: psx
  compiler: psyq
  basename: world04_area152_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world04/area152/13.bin
  asm_path: out/splat/emi/world04/area152/13/asm
  src_path: src/emi/world04/area152/13
  ld_script_path: out/splat/emi/world04/area152/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 0
        - asm
        - func_801F2C00
      - - 1732
        - asm
        - func_801F32C4
      - - 1932
        - asm
        - func_801F338C
      - - 2172
        - asm
        - func_801F347C
      - - 2384
        - asm
        - func_801F3550
      - - 3228
        - asm
        - func_801F389C
      - - 3524
        - asm
        - func_801F39C4
      - - 4496
        - asm
        - func_801F3D90
      - - 5000
        - asm
        - func_801F3F88
  - - 0x223a
