name: scenario_scena02_00
sha1: bbec938d1ee166622b6b348c0a7fb6659d050f78
options:
  platform: psx
  compiler: psyq
  basename: scenario_scena02_00
  base_path: ../../../../..
  target_path: out/binaries/emi/scenario/scena02/00.bin
  asm_path: out/splat/emi/scenario/scena02/00/asm
  src_path: src/emi/scenario/scena02/00
  ld_script_path: out/splat/emi/scenario/scena02/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149542912
    subsegments:
      - - 21284
        - asm
        - func_801FBF24
      - - 21396
        - asm
        - func_801FBF94
      - - 21572
        - asm
        - func_801FC044
      - - 21748
        - asm
        - func_801FC0F4
      - - 21924
        - asm
        - func_801FC1A4
      - - 22108
        - asm
        - func_801FC25C
      - - 22280
        - asm
        - func_801FC308
      - - 22452
        - asm
        - func_801FC3B4
      - - 22636
        - asm
        - func_801FC46C
      - - 22808
        - asm
        - func_801FC518
      - - 22992
        - asm
        - func_801FC5D0
      - - 23176
        - asm
        - func_801FC688
      - - 23348
        - asm
        - func_801FC734
      - - 23524
        - asm
        - func_801FC7E4
      - - 24012
        - asm
        - func_801FC9CC
      - - 24404
        - asm
        - func_801FCB54
      - - 24540
        - asm
        - func_801FCBDC
      - - 24852
        - asm
        - func_801FCD14
      - - 25292
        - asm
        - func_801FCECC
      - - 27388
        - asm
        - func_801FD6FC
  - - 0x777c
