name: world00_area032_13
sha1: 2c3f913fb3acdb10627e7a98770d038f122430d7
options:
  platform: psx
  compiler: psyq
  basename: world00_area032_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world00/area032/13.bin
  asm_path: out/splat/emi/world00/area032/13/asm
  src_path: src/emi/world00/area032/13
  ld_script_path: out/splat/emi/world00/area032/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - [0x0, bin]
  - [0x1D10]
