name: world02_area087_13
sha1: f8bb5e80dd706eab37ab9845ea7ac9e6dfac3aa4
options:
  platform: psx
  compiler: psyq
  basename: world02_area087_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world02/area087/13.bin
  asm_path: out/splat/emi/world02/area087/13/asm
  src_path: src/emi/world02/area087/13
  ld_script_path: out/splat/emi/world02/area087/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 2100
        - asm
        - func_801F3434
      - - 2300
        - asm
        - func_801F34FC
      - - 2540
        - asm
        - func_801F35EC
      - - 2752
        - asm
        - func_801F36C0
      - - 3596
        - asm
        - func_801F3A0C
      - - 3892
        - asm
        - func_801F3B34
      - - 4864
        - asm
        - func_801F3F00
      - - 5368
        - asm
        - func_801F40F8
  - - 0x2c16
