/* Generated by bin/harness source symbols; do not edit. */
#include "bof3/symbols.h"
/* @source 0x801448EB */
extern s8 D_801448EB;
WEAK_SYMBOL_AT(D_801448EB, 0x801448EB);
/* @source 0x801448EC */
extern s8 D_801448EC;
WEAK_SYMBOL_AT(D_801448EC, 0x801448EC);
/* @source 0x801448ED */
extern s8 D_801448ED;
WEAK_SYMBOL_AT(D_801448ED, 0x801448ED);
WEAK_SYMBOL_AT(func_8015C088, 0x8015C088);
/* @source 0x801F2C44 */
extern u8 area093PackedTable[];
WEAK_SYMBOL_AT(area093PackedTable, 0x801F2C44);
