/* Generated by bin/harness source symbols; do not edit. */
#include "bof3/symbols.h"
/* @source 0x80144F28 */
extern u8 D_80144F28;
WEAK_SYMBOL_AT(D_80144F28, 0x80144F28);
/* @source 0x80145F09 */
extern u8 D_80145F09;
WEAK_SYMBOL_AT(D_80145F09, 0x80145F09);
/* @source 0x80146884 */
extern void* D_80146884;
WEAK_SYMBOL_AT(D_80146884, 0x80146884);
/* @source 0x801F2C74 */
extern u8 area127PackedTable[];
WEAK_SYMBOL_AT(area127PackedTable, 0x801F2C74);
WEAK_SYMBOL_AT(func_8015507C, 0x8015507C);
WEAK_SYMBOL_AT(func_8015B580, 0x8015B580);
