/* Generated by bin/harness source symbols; do not edit. */
#include "bof3/symbols.h"
/* @source 0x801F6DBC */
extern u32 scena19HandlerTable[];
WEAK_SYMBOL_AT(scena19HandlerTable, 0x801F6DBC);
/* @source 0x80145AA8 */
extern u16 D_80145AA8;
WEAK_SYMBOL_AT(D_80145AA8, 0x80145AA8);
/* @source 0x80143FC8 */
extern u8 D_80143FC8[];
WEAK_SYMBOL_AT(D_80143FC8, 0x80143FC8);
/* @source 0x8019601C */
extern s32 func_8019601C(void);
WEAK_SYMBOL_AT(func_8019601C, 0x8019601C);
