schema = "harness.target/v2"
id = "emi/plchar/plp247/00"
disc_id = "BIN/PLCHAR/PLP247.EMI#0"
kind = "emi"
source_dir = "src/emi/plchar/plp247/00"
binary = "out/binaries/emi/plchar/plp247/00.bin"
splat = "config/targets/emi/plchar/plp247/00/splat.yaml"
load_address = 0x801CE400

sources = []
support_sources = [
    "src/bof3/plchar/getAndClearPlcharPlp24700_801CEE08.c",
    "src/bof3/support/plp247_00_psyq.c",
]
psyq_source = "src/bof3/support/plp247_00_psyq.c"
