name: etc_game_01
sha1: 6e2f5de09f183cfa5dc3a030d3dbb6cf2f296c84
options:
  platform: psx
  compiler: psyq
  basename: etc_game_01
  base_path: ../../../../../..
  target_path: out/binaries/emi/etc/game/01.bin
  asm_path: out/splat/emi/etc/game/01/asm
  src_path: src/emi/etc/game/01
  ld_script_path: out/splat/emi/etc/game/01/linker.ld
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/etc/game/01/symbols.txt
segments:
  - [0x0, bin, header]
  - name: main
    type: code
    start: 0x4
    vram: 0x801d0c04
    subsegments:
      - [0x4, c, game_front_main_loop]
      - [0x90, c, game_front_title_setup]
      - [0x15c, c, game_front_arm_fade_delay]
      - [0x194, c, game_front_tick_fade_timer]
      - [0x1f0, c, game_front_open_selection]
      - [0x254, c, game_front_finish_selection]
      - [0x300, c, game_front_handle_menu_input]
      - [0x3b8, c, game_front_update_prompt]
      - [0x400, c, game_front_finalize_exit]
      - [0x44c, c, game_front_pre_dispatch_gate]
      - [0x534, c, game_front_start_selection_fx]
      - [0x584, c, game_front_stop_selection_fx]
      - [0x5e4, c, game_front_draw_prompt]
      - [0x6cc, c, game_front_draw_prompt_panels]
      - [0x90c, c, game_front_draw_label_groups]
      - [0xadc, c, game_front_draw_label_group]
      - [0xbd8, c, game_front_draw_glyph]
      - [0xce8, c, game_front_set_glyph_alpha]
      - [0xcf8, c, game_front_update_banner]
      - [0xf00, c, game_front_update_windows]
  - [0x104c, bin, data]
  - [0x1134]
