name: etc_game_01
sha1: 6e2f5de09f183cfa5dc3a030d3dbb6cf2f296c84
options:
  platform: psx
  compiler: psyq
  basename: etc_game_01
  base_path: ../../../../../..
  target_path: out/binaries/emi/etc/game/01.bin
  asm_path: out/splat/emi/etc/game/01/asm
  src_path: src/emi/etc/game/01
  ld_script_path: out/splat/emi/etc/game/01/linker.ld
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/etc/game/01/symbols.txt
segments:
  - [0x0, bin, header]
  - name: main
    type: code
    start: 0x4
    vram: 0x801d0c04
    subsegments:
      - [0x4, c, func_801D0C04]
      - [0x90, c, func_801D0C90]
      - [0x15c, c, func_801D0D5C]
      - [0x194, c, func_801D0D94]
      - [0x1f0, c, func_801D0DF0]
      - [0x254, c, func_801D0E54]
      - [0x300, c, func_801D0F00]
      - [0x3b8, c, func_801D0FB8]
      - [0x400, c, func_801D1000]
      - [0x44c, c, func_801D104C]
      - [0x534, c, func_801D1134]
      - [0x584, c, func_801D1184]
      - [0x5e4, c, func_801D11E4]
      - [0x6cc, c, func_801D12CC]
      - [0x90c, c, func_801D150C]
      - [0xadc, c, func_801D16DC]
      - [0xbd8, c, func_801D17D8]
      - [0xce8, c, func_801D18E8]
      - [0xcf8, c, func_801D18F8]
      - [0xf00, c, func_801D1B00]
  - [0x104c, bin, data]
  - [0x1134]
