name: world02_area077_14
sha1: 439a49695ec5e0621d35a47f6805b0050c8f82cf
options:
  platform: psx
  compiler: psyq
  basename: world02_area077_14
  base_path: ../../../../..
  target_path: out/binaries/emi/world02/area077/14.bin
  asm_path: out/splat/emi/world02/area077/14/asm
  src_path: src/emi/world02/area077/14
  ld_script_path: out/splat/emi/world02/area077/14/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 1256
        - asm
        - func_801F30E8
      - - 1432
        - asm
        - func_801F3198
      - - 1516
        - asm
        - func_801F31EC
      - - 2528
        - asm
        - func_801F35E0
      - - 2792
        - asm
        - func_801F36E8
      - - 2936
        - asm
        - func_801F3778
      - - 3224
        - asm
        - func_801F3898
      - - 3912
        - asm
        - func_801F3B48
      - - 4036
        - asm
        - func_801F3BC4
      - - 5556
        - asm
        - func_801F41B4
      - - 5664
        - asm
        - func_801F4220
      - - 6088
        - asm
        - func_801F43C8
      - - 6700
        - asm
        - func_801F462C
      - - 7112
        - asm
        - func_801F47C8
      - - 7784
        - asm
        - func_801F4A68
      - - 8064
        - asm
        - func_801F4B80
      - - 9884
        - asm
        - func_801F529C
      - - 10424
        - asm
        - func_801F54B8
      - - 13808
        - asm
        - func_801F61F0
  - - 0x3f78
