name: bmagic_magic065_00
sha1: fc2b012d32f27163b2eaa0825d966778162590cc
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic065_00
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic065/00.bin
  asm_path: out/splat/emi/bmagic/magic065/00/asm
  src_path: src/emi/bmagic/magic065/00
  ld_script_path: out/splat/emi/bmagic/magic065/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 2088
        - asm
        - func_801EF428
  - - 0x914
