name: boss_boss034_16
sha1: 1be7e6c5fd93cfbaf4680c31262a553c1509de1d
options:
  platform: psx
  compiler: psyq
  basename: boss_boss034_16
  base_path: ../../../../..
  target_path: out/binaries/emi/boss/boss034/16.bin
  asm_path: out/splat/emi/boss/boss034/16/asm
  src_path: src/emi/boss/boss034/16
  ld_script_path: out/splat/emi/boss/boss034/16/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2148276224
    subsegments:
      - - 0
        - asm
        - func_800C1800
      - - 3028
        - asm
        - func_800C23D4
  - - 0xf7c
