schema = "harness.target/v2"
id = "emi/world02/area099/13"
disc_id = "BIN/WORLD02/AREA099.EMI#13"
kind = "emi"
source_dir = "src/emi/world02/area099/13"
binary = "out/binaries/emi/world02/area099/13.bin"
splat = "config/targets/emi/world02/area099/13/splat.yaml"
load_address = 0x801F2C00

sources = []
support_sources = [
    "src/bof3/support/area099_13_psyq.c",
]
psyq_source = "src/bof3/support/area099_13_psyq.c"
