name: world00_area012_13
sha1: 57e0afd4523c75ec864f3921c8763ce60a6af0e6
options:
  platform: psx
  compiler: psyq
  basename: world00_area012_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world00/area012/13.bin
  asm_path: out/splat/emi/world00/area012/13/asm
  src_path: src/emi/world00/area012/13
  ld_script_path: out/splat/emi/world00/area012/13/linker.ld
  undefined_funcs_auto_path: out/splat/emi/world00/area012/13/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/world00/area012/13/undefined_syms_auto.txt
  cache_path: out/splat/emi/world00/area012/13/.splache
  asset_path: out/splat/emi/world00/area012/13/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world00/area012/13/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149526532
  subsegments:
  - - 4
    - asm
    - func_801F2C04
  - - 80
    - asm
    - D_801F2C50
- - 956
