"""m2ctx/m2c runner commands and shared function/source resolution."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

from ..canonical import load_target_symbols
from ..domain import FunctionId, parse_function_id
from ..domain.manifests import TargetManifest, load_target_manifests
from ..io import repo_layout
from ..toolchain.m2c import M2cToolchain


_FUNC = re.compile(r"^func_[0-9a-fA-F]{8}$")


def resolve_function(value: str) -> tuple[FunctionId, TargetManifest, Path]:
    """Return one known target and its authored source path.

    Raw lifts live at func_<ADDR>.c; a renamed lift is found through its
    @source metadata tag (the address authority inside renamed files).
    """

    function = parse_function_id(value)
    root = repo_layout().root
    manifests = load_target_manifests(root)
    manifest = manifests.get(function.target.value)
    if manifest is None:
        raise ValueError(f"unknown target: {function.target.value}")
    source = root / manifest.source_dir / f"func_{function.address:08X}.c"
    if source.is_file():
        return function, manifest, source
    from ..match._asm_resolve import collect_source_addresses

    for candidate, address in collect_source_addresses(root / manifest.source_dir):
        if address == function.address:
            return function, manifest, candidate
    return function, manifest, source


def splat_assembly(manifest: TargetManifest, address: int) -> Path:
    root = repo_layout().root
    directory = root / "out" / "splat" / manifest.id.value / "asm"
    expected = directory / f"func_{address:08X}.s"
    if expected.is_file():
        return expected
    from ..canonical import load_target_symbols

    for symbol in load_target_symbols(root, manifest.id.value):
        if symbol.address == address:
            named = directory / f"{symbol.name}.s"
            if named.is_file():
                return named
            break
    raise FileNotFoundError(
        f"Splat assembly not found: {expected}; run the target's Splat split first"
    )


def context_path(function: FunctionId) -> Path:
    return (
        repo_layout().out_dir
        / "m2ctx"
        / function.target.value
        / f"{function.address:08X}.c"
    )


def render_context(function: FunctionId, manifest: TargetManifest) -> str:
    """Render the minimal deterministic m2c context owned by one target.

    m2c consumes declarations rather than a preprocessor configuration.  The
    generated context therefore records the target-owned headers and emits
    conservative old-style declarations for target-map symbols.  It never
    imports another target's source or map.
    """

    root = repo_layout().root
    source_dir = root / manifest.source_dir
    symbols = load_target_symbols(root, manifest.id.value)
    lines = [
        "/* Generated by bin/m2ctx; do not edit. */",
        f"/* target: {manifest.id.value}; function: 0x{function.address:08X} */",
        "typedef unsigned char u8;",
        "typedef unsigned short u16;",
        "typedef unsigned int u32;",
        "typedef signed char s8;",
        "typedef signed short s16;",
        "typedef signed int s32;",
        "",
    ]
    headers = [source_dir / "internal.h", root / "include" / "bof3" / "context.h"]
    headers.extend(sorted((source_dir / "symbols").glob("*.h")))
    for header in headers:
        if header.is_file():
            try:
                relative = header.relative_to(root).as_posix()
            except ValueError:
                relative = str(header)
            lines.append(f"/* owning declaration source: {relative} */")
    if headers:
        lines.append("")
    for symbol in symbols:
        if symbol.name.startswith("func_") or _FUNC.fullmatch(symbol.name):
            lines.append(f"extern void {symbol.name}();")
        elif symbol.name.startswith("D_"):
            lines.append(f"extern u8 {symbol.name}[];")
    return "\n".join(lines) + "\n"


def run_m2ctx(args: argparse.Namespace) -> int:
    function, manifest, _ = resolve_function(args.function)
    destination = Path(args.out) if args.out else context_path(function)
    if not destination.is_absolute():
        destination = repo_layout().root / destination
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render_context(function, manifest), encoding="utf-8")
    if args.json:
        print(
            json.dumps(
                {
                    "target": manifest.id.value,
                    "address": f"0x{function.address:08X}",
                    "context": str(destination),
                },
                sort_keys=True,
            )
        )
    else:
        print(destination)
    return 0


def _asm_label(path: Path) -> str:
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = re.match(r"\s*glabel\s+(\S+)", line)
        if match:
            return match.group(1)
    raise ValueError(f"no glabel found in {path}")


def run_m2c(args: argparse.Namespace) -> int:
    function, manifest, _ = resolve_function(args.function)
    assembly = splat_assembly(manifest, function.address)
    context = context_path(function)
    context.parent.mkdir(parents=True, exist_ok=True)
    context.write_text(render_context(function, manifest), encoding="utf-8")
    root = repo_layout().root
    m2c = M2cToolchain(root)
    arguments: list[str] = [
        "-t",
        "mipsel-gcc-c",
        "-f",
        _asm_label(assembly),
        "--globals",
        "used",
        "--valid-syntax",
        "--knr",
        "--deterministic-vars",
        "--comment-style",
        "multiline",
        "--context",
        str(context),
    ]
    for extra in args.context:
        arguments.extend(("--context", extra))
    if args.void:
        arguments.append("--void")
    arguments.append(str(assembly))
    result = m2c.execute(arguments, capture_output=True, text=True)
    seed = re.sub(
        r"\bfunc_([0-9A-Fa-f]{8})\b",
        lambda match: f"func_{match.group(1).upper()}",
        result.stdout,
    )
    if args.out is not None:
        output = Path(args.out)
        if not output.is_absolute():
            output = root / output
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(seed, encoding="utf-8")
    else:
        print(seed, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    if result.returncode:
        return result.returncode
    return 0
