"""Target-qualified entry points for the one-function lifting loop.

These commands deliberately resolve a ``TARGET@0xADDRESS`` before touching a
source file.  This prevents an identically-addressed function in another EMI
entry from accidentally becoming the build or match target.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import subprocess
import sys

from ..canonical import load_map, map_path, weak_bindings_c
from ..domain import FunctionId, parse_function_id
from ..domain.manifests import TargetManifest, load_target_manifests
from ..io import repo_layout
from ..match.asm_diff import AsmDiffRequest, run_asm_diff_one
from ..match.asm_differ import write_bundle


_FUNC = re.compile(r"^func_[0-9a-fA-F]{8}$")


def _example(command: str) -> str:
    return f"bin/{command} exe/logo@0x801CE758"


def resolve_function(value: str) -> tuple[FunctionId, TargetManifest, Path]:
    """Return one known target and its address-based authored source path."""

    function = parse_function_id(value)
    root = repo_layout().root
    manifests = load_target_manifests(root)
    manifest = manifests.get(function.target.value)
    if manifest is None:
        raise ValueError(f"unknown target: {function.target.value}")
    source = root / manifest.source_dir / f"func_{function.address:08X}.c"
    return function, manifest, source


def splat_assembly(manifest: TargetManifest, address: int) -> Path:
    root = repo_layout().root
    directory = root / "out" / "splat" / manifest.id.value / "asm"
    expected = directory / f"func_{address:08X}.s"
    if expected.is_file():
        return expected
    raise FileNotFoundError(
        f"Splat assembly not found: {expected}; run the target's Splat split first"
    )


def context_path(function: FunctionId) -> Path:
    return (
        repo_layout().out_dir
        / "m2ctx"
        / function.target.value
        / f"{function.address:08X}.c"
    )


def render_context(function: FunctionId, manifest: TargetManifest) -> str:
    """Render the minimal deterministic m2c context owned by one target.

    m2c consumes declarations rather than a preprocessor configuration.  The
    generated context therefore records the target-owned headers and emits
    conservative old-style declarations for target-map symbols.  It never
    imports another target's source or map.
    """

    root = repo_layout().root
    source_dir = root / manifest.source_dir
    symbols = load_map(map_path(root, manifest.id.value))
    lines = [
        "/* Generated by bin/m2ctx; do not edit. */",
        f"/* target: {manifest.id.value}; function: 0x{function.address:08X} */",
        "typedef unsigned char u8;",
        "typedef unsigned short u16;",
        "typedef unsigned int u32;",
        "typedef signed char s8;",
        "typedef signed short s16;",
        "typedef signed int s32;",
        "",
    ]
    headers = [source_dir / "internal.h", root / "include" / "bof3" / "context.h"]
    headers.extend(sorted((source_dir / "symbols").glob("*.h")))
    for header in headers:
        if header.is_file():
            try:
                relative = header.relative_to(root).as_posix()
            except ValueError:
                relative = str(header)
            lines.append(f"/* owning declaration source: {relative} */")
    if headers:
        lines.append("")
    for symbol in symbols:
        if symbol.name.startswith("func_") or _FUNC.fullmatch(symbol.name):
            lines.append(f"extern void {symbol.name}();")
        elif symbol.name.startswith("D_"):
            lines.append(f"extern u8 {symbol.name}[];")
    return "\n".join(lines) + "\n"


def run_m2ctx(args: argparse.Namespace) -> int:
    function, manifest, _ = resolve_function(args.function)
    destination = Path(args.out) if args.out else context_path(function)
    if not destination.is_absolute():
        destination = repo_layout().root / destination
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render_context(function, manifest), encoding="utf-8")
    if args.json:
        print(
            json.dumps(
                {
                    "target": manifest.id.value,
                    "address": f"0x{function.address:08X}",
                    "context": str(destination),
                },
                sort_keys=True,
            )
        )
    else:
        print(destination)
    return 0


def _asm_label(path: Path) -> str:
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        match = re.match(r"\s*glabel\s+(\S+)", line)
        if match:
            return match.group(1)
    raise ValueError(f"no glabel found in {path}")


def run_m2c(args: argparse.Namespace) -> int:
    function, manifest, _ = resolve_function(args.function)
    assembly = splat_assembly(manifest, function.address)
    context = context_path(function)
    context.parent.mkdir(parents=True, exist_ok=True)
    context.write_text(render_context(function, manifest), encoding="utf-8")
    root = repo_layout().root
    command = [
        sys.executable,
        str(root / "third_party" / "m2c" / "m2c.py"),
        "-t",
        "mipsel-gcc-c",
        "-f",
        _asm_label(assembly),
        "--globals",
        "used",
        "--valid-syntax",
        "--knr",
        "--deterministic-vars",
        "--comment-style",
        "multiline",
        "--context",
        str(context),
    ]
    for extra in args.context:
        command.extend(("--context", extra))
    if args.void:
        command.append("--void")
    command.append(str(assembly))
    result = subprocess.run(command, cwd=root, capture_output=True, text=True)
    seed = re.sub(
        r"\bfunc_([0-9A-Fa-f]{8})\b",
        lambda match: f"func_{match.group(1).upper()}",
        result.stdout,
    )
    if args.out is not None:
        output = Path(args.out)
        if not output.is_absolute():
            output = root / output
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(seed, encoding="utf-8")
    else:
        print(seed, end="")
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    if result.returncode:
        return result.returncode
    return 0


def _run_match(function: FunctionId, source: Path) -> dict[str, object]:
    root = repo_layout().root
    manifest = load_target_manifests(root)[function.target.value]
    bindings = root / "out" / "bindings" / function.target.value / "symbols.c"
    bindings.parent.mkdir(parents=True, exist_ok=True)
    bindings.write_text(
        weak_bindings_c(load_map(map_path(root, function.target.value))),
        encoding="utf-8",
    )
    payload = run_asm_diff_one(
        AsmDiffRequest(
            source_path=source,
            address=function.address,
            binary_path=root / manifest.binary,
            load_address=manifest.load_address,
            output_root=root / "out" / "asm-diff",
            symbols_c_path=bindings,
        )
    )
    write_bundle(root, payload, target=function.target.value, profile=manifest.profile)
    return payload


def _print_match(
    payload: dict[str, object], *, json_output: bool, bytes_only: bool
) -> int:
    exact = bool(payload["byte_match"])
    if json_output:
        if bytes_only:
            print(
                json.dumps(
                    {
                        key: payload[key]
                        for key in (
                            "function",
                            "address",
                            "original_size",
                            "current_size",
                            "byte_match",
                            "outputs",
                        )
                    },
                    sort_keys=True,
                )
            )
        else:
            print(json.dumps(payload, indent=2, sort_keys=True))
    elif bytes_only:
        status = "MATCH" if exact else "DIFFER"
        print(f"{status} {payload['function']}@{payload['address']} bytes")
    else:
        status = "MATCH" if exact else "DIFFER"
        print(
            f"{status} {payload['function']}@{payload['address']} {payload['instruction_count']['match_percent']}%"
        )
    return 0 if exact else 1


def run_asm_diff(args: argparse.Namespace) -> int:
    function, _manifest, source = resolve_function(args.function)
    if not source.is_file():
        raise FileNotFoundError(f"lifted source does not exist: {source}")
    return _print_match(
        _run_match(function, source), json_output=args.json, bytes_only=False
    )


def run_byte_match(args: argparse.Namespace) -> int:
    function, _manifest, source = resolve_function(args.function)
    if not source.is_file():
        raise FileNotFoundError(f"lifted source does not exist: {source}")
    return _print_match(
        _run_match(function, source), json_output=args.json, bytes_only=True
    )


def run_promote(args: argparse.Namespace) -> int:
    function, _manifest, source = resolve_function(args.function)
    candidate = Path(args.candidate).resolve()
    if not candidate.is_file():
        raise FileNotFoundError(f"candidate source does not exist: {candidate}")
    # Promotion intentionally never copies a candidate.  Exact matching is
    # target-local, so a candidate must first be installed at its owned path by
    # the maintainer, then this command validates it.
    if candidate != source.resolve():
        raise ValueError(
            "validate-only promotion requires the candidate at its owned source path: "
            f"{source.relative_to(repo_layout().root)}"
        )
    format_check = subprocess.run(
        ["clang-format", "--dry-run", "--Werror", str(candidate)],
        capture_output=True,
        text=True,
    )
    if format_check.returncode:
        raise RuntimeError(
            f"candidate is not clang-format clean: {format_check.stderr}"
        )
    payload = _run_match(function, source)
    result = _print_match(payload, json_output=args.json, bytes_only=False)
    if result == 0 and not args.json:
        print(
            "validated; manually retain the source, Splat boundary, and symbol-map edits"
        )
    return result


def _parser(command: str) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog=f"bin/{command}")
    parser.add_argument(
        "--example", action="store_true", help="print a minimal invocation"
    )
    return parser


def main(command: str, argv: list[str] | None = None) -> int:
    parser = _parser(command)
    if command == "m2ctx":
        parser.add_argument("function", nargs="?")
        parser.add_argument("-o", "--out")
        parser.add_argument("--json", action="store_true")
        parser.set_defaults(handler=run_m2ctx)
    elif command == "m2c":
        parser.add_argument("function", nargs="?")
        parser.add_argument("--void", action="store_true")
        parser.add_argument("-o", "--out")
        parser.add_argument("-c", "--context", action="append", default=[])
        parser.set_defaults(handler=run_m2c)
    elif command in {"asm-diff", "byte-match"}:
        parser.add_argument("function", nargs="?")
        parser.add_argument("--json", action="store_true")
        parser.set_defaults(
            handler=run_asm_diff if command == "asm-diff" else run_byte_match
        )
    elif command == "promote":
        parser.add_argument("function", nargs="?")
        parser.add_argument("candidate", nargs="?")
        parser.add_argument("--json", action="store_true")
        parser.set_defaults(handler=run_promote)
    else:
        raise ValueError(f"unknown lift command: {command}")
    args = parser.parse_args(argv)
    if args.example:
        print(_example(command))
        return 0
    if not getattr(args, "function", None):
        parser.error("TARGET@0xADDRESS is required")
    if command == "promote" and not args.candidate:
        parser.error("candidate.c is required")
    try:
        return args.handler(args)
    except (FileNotFoundError, RuntimeError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
