"""Single-function mission brief composition from indexed reverse evidence."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from ..domain import load_target_manifests, parse_function_id
from ..domain.claims import resolve_manifest_source_for_address
from ..domain.layout import parse_splat_layout
from ..domain.symbols import load_map, load_target_symbols, sdk_map_path
from .graph import enrich_graph, function_metrics
from .index import connect, rows


def mission_brief(root: Path, function_selector: str) -> dict[str, Any]:
    """Compose a single-function lifting brief from indexed evidence."""
    function = parse_function_id(function_selector)
    target = function.target.value
    address = function.address
    function_id = str(function)

    manifests = load_target_manifests(root)
    if target not in manifests:
        raise ValueError(f"unknown target: {target}")
    manifest = manifests[target]
    space = manifest.psyq_space

    connection = connect(root)
    try:
        metrics = function_metrics(connection, target)
        enrich_graph(connection, metrics)
        row = next((item for item in metrics if item["id"] == function_id), None)
        if row is None:
            raise ValueError(f"function not in reverse index: {function_id}")
        callers = rows(
            connection,
            "SELECT caller, printf('0x%08X', callsite) AS callsite "
            "FROM calls WHERE callee = ? ORDER BY caller, callsite",
            (function_id,),
        )
        callees = rows(
            connection,
            "SELECT callee, printf('0x%08X', callsite) AS callsite "
            "FROM calls WHERE caller = ? ORDER BY callsite",
            (function_id,),
        )
        unresolved = rows(
            connection,
            "SELECT printf('0x%08X', target_address) AS target_address, "
            "printf('0x%08X', callsite) AS callsite, kind "
            "FROM unresolved_calls WHERE caller = ? ORDER BY callsite",
            (function_id,),
        )
        duplicate_group: list[str] = []
        if row["duplicate_members"] > 1:
            duplicate_group = [
                member_id
                for (member_id,) in connection.execute(
                    "SELECT function_id FROM duplicate_members WHERE hash = ? "
                    "ORDER BY function_id",
                    (row["exact_sha256"],),
                )
            ]
    finally:
        connection.close()
    sdk_by_address = {
        symbol.address: symbol.canonical_name
        for symbol in load_map(sdk_map_path(root, space))
    }
    sdk_callees = []
    for callee in callees:
        callee_address = int(str(callee["callee"]).rsplit("@", 1)[1], 16)
        name = sdk_by_address.get(callee_address)
        if name is not None:
            sdk_callees.append({"address": f"0x{callee_address:08X}", "name": name})
    sdk_unresolved = []
    for call in unresolved:
        unresolved_address = int(str(call["target_address"]), 16)
        name = sdk_by_address.get(unresolved_address)
        if name is not None:
            sdk_unresolved.append(
                {"address": f"0x{unresolved_address:08X}", "name": name}
            )

    resolved = resolve_manifest_source_for_address(root, manifest, address)
    source = resolved.relative_to(root) if resolved is not None else None
    layout = parse_splat_layout(root / manifest.splat, manifest.load_address)
    boundary = layout.find_boundary_at(address)
    splat_asm = None
    if boundary is not None and boundary.name:
        candidate = Path("out") / "splat" / target / "asm" / f"{boundary.name}.s"
        if (root / candidate).is_file():
            splat_asm = candidate
    if splat_asm is None:
        for symbol in load_target_symbols(root, target):
            if symbol.address == address:
                named = Path("out") / "splat" / target / "asm" / f"{symbol.name}.s"
                if (root / named).is_file():
                    splat_asm = named
                break
    # Concrete required-work graph, generated by the tool from indexed
    # callers/callees/unresolved accesses: agents close or route items,
    # they never claim exhaustion themselves.
    required_work: list[dict[str, str]] = []
    for call in callers:
        required_work.append(
            {
                "id": f"caller:{call['caller']}",
                "profile": "caller_context",
                "description": f"resolve caller {call['caller']}",
            }
        )
    for call in callees:
        required_work.append(
            {
                "id": f"callee:{call['callee']}",
                "profile": "callee_body",
                "description": f"resolve callee {call['callee']}",
            }
        )
    for call in unresolved:
        required_work.append(
            {
                "id": f"unresolved:{call['target_address']}",
                "profile": "unresolved_call",
                "description": f"resolve target 0x{call['target_address']}",
            }
        )
    if duplicate_group:
        required_work.append(
            {
                "id": "duplicate:group",
                "profile": "duplicate_member",
                "description": f"inspect {len(duplicate_group)} duplicate members",
            }
        )
    required_work.sort(key=lambda item: item["id"])

    return {
        "schema": "bof3.mission/v1",
        "function": function_id,
        "target": target,
        "address": f"0x{address:08X}",
        "psyq_space": space,
        "source": None if source is None else str(source),
        "source_exists": source is not None and (root / source).is_file(),
        "lifted": row["lifted"],
        "splat_asm": None if splat_asm is None else str(splat_asm),
        "splat_asm_exists": splat_asm is not None and (root / splat_asm).is_file(),
        "metrics": {
            key: row[key]
            for key in (
                "size",
                "instruction_count",
                "basic_blocks",
                "cyclomatic_complexity",
                "loops",
                "unique_callers",
                "unique_callees",
                "leaf_status",
                "duplicate_leverage",
                "metric_missing",
                "confidence_band",
            )
        },
        "risk": {
            "unresolved_calls": row["unresolved_calls"],
            "metric_missing": row["metric_missing"],
            "confidence_band": row["confidence_band"],
        },
        "callers": callers,
        "callees": callees,
        "unresolved_calls": unresolved,
        "sdk_callees": sdk_callees,
        "sdk_unresolved": sdk_unresolved,
        "duplicate_group": duplicate_group,
        "required_work": required_work,
    }
