"""Replay composition.

Owns generated/reviewed/shared replay paths, renders generated replay
from layout and source inventory, and builds one ordered analyzer
command plan used by both projects and snapshots.

Generated replay belongs at ``out/analysis/replay/<target>.r2``.
Reviewed replay belongs at ``config/analysis/<target>/reviewed.r2``.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

from ..domain.ids import TargetId
from ..domain.registry import ResolvedTarget
from ..layout import ReviewedLayout
from ..source_inventory import SourceInventory


@dataclass(frozen=True)
class ReplayInputs:
    """Every input that affects the analyzer command plan."""

    target_id: str
    manifest_sha256: str | None
    binary_sha256: str | None
    splat_sha256: str | None
    source_inventory_sha256: str | None
    generated_replay_sha256: str | None
    reviewed_replay_sha256: str | None
    shared_types_sha256: str | None
    shared_hwregs_sha256: str | None

    def composite_hash(self) -> str:
        pieces = [
            (self.manifest_sha256 or "").encode(),
            (self.binary_sha256 or "").encode(),
            (self.splat_sha256 or "").encode(),
            (self.source_inventory_sha256 or "").encode(),
            (self.generated_replay_sha256 or "").encode(),
            (self.reviewed_replay_sha256 or "").encode(),
            (self.shared_types_sha256 or "").encode(),
            (self.shared_hwregs_sha256 or "").encode(),
        ]
        return hashlib.sha256(b"\x00".join(pieces)).hexdigest()[:16]


@dataclass(frozen=True)
class ReplayPlan:
    """A complete analyzer command plan for one target."""

    inputs: ReplayInputs
    commands: tuple[str, ...]


def replay_output_path(root: Path, target_id: TargetId) -> Path:
    """Return the generated replay artifact path under ``out/analysis/replay``."""

    return root / "out" / "analysis" / "replay" / f"{target_id.value}.r2"


def reviewed_replay_path(root: Path, target_id: TargetId) -> Path:
    """Return the reviewed replay path under ``config/analysis``."""

    return root / "config" / "analysis" / target_id.value / "reviewed.r2"


def _sha256(path: Path) -> str | None:
    if not path.is_file():
        return None
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build_replay_inputs(
    root: Path, resolved: ResolvedTarget, inventory: SourceInventory
) -> ReplayInputs:
    """Collect all input hashes for the replay plan."""

    generated = replay_output_path(root, resolved.id)
    return ReplayInputs(
        target_id=resolved.id.value,
        manifest_sha256=_sha256(resolved.manifest_path),
        binary_sha256=_sha256(resolved.binary_path),
        splat_sha256=_sha256(resolved.splat_path),
        source_inventory_sha256=inventory.input_hash,
        generated_replay_sha256=_sha256(generated),
        reviewed_replay_sha256=_sha256(resolved.reviewed_replay_path),
        shared_types_sha256=_sha256(root / "config" / "analysis" / "shared" / "bof3_objects.h"),
        shared_hwregs_sha256=_sha256(root / "config" / "analysis" / "shared" / "hwregs.r2"),
    )


def render_generated_replay(
    *,
    layout: ReviewedLayout,
    inventory: SourceInventory,
    splat_path: Path,
    source_dir: Path,
) -> str:
    """Render the auto-generated analyzer replay for a single target.

    Function aliases come from the source inventory's function
    declarations; data aliases come from data declarations.  All
    PsyQ bindings are grouped under their owning library comment.
    """

    lines: list[str] = ["# Auto-generated by harness; do not edit", ""]

    # 1. Splat-reviewed function names.
    reviewed = layout.reviewed_function_addresses
    if reviewed:
        lines.append("fs functions")
        for address in reviewed:
            lines.append(f"afn func_{address:08x} @ 0x{address:08x}")
        lines.append("")

    # 2. Function bindings not already in the Splat layout.
    reviewed = set(layout.reviewed_function_addresses)
    extra_funcs = {
        f.address: f.semantic_name or f.name
        for f in inventory.functions
        if f.address not in reviewed
    }
    if extra_funcs:
        lines.append("fs functions")
        for address in sorted(extra_funcs):
            name = extra_funcs[address]
            lines.append(f"afn {name} @ 0x{address:08x}")
            if inventory.functions_by_address()[address].semantic_name:
                lines.append(f'CC "WEAK_SYMBOL_AT {name}" @ 0x{address:08x}')
        lines.append("")

    # 3. PsyQ bindings.
    if inventory.psyq:
        lines.append("fs psyq")
        current_library = ""
        for binding in inventory.psyq:
            if binding.library != current_library:
                lines.append(f"# {binding.library}")
                current_library = binding.library or ""
            lines.append(f"f psyq.{binding.name} 1 @ 0x{binding.address:08x}")
        lines.append("")

    # 4. Data declarations.
    if inventory.data:
        lines.append("fs data")
        for d in inventory.data:
            lines.append(f"f data.{d.name} 4 @ 0x{d.address:08x}")
        lines.append("")

    # 5. DAT_ references from decompiled C files.
    data_refs: set[int] = set()
    if source_dir.is_dir():
        for c_file in sorted(source_dir.glob("func_*.c")):
            for match in re.finditer(
                r"\bDAT_([0-9a-fA-F]{8})\b", c_file.read_text(encoding="utf-8")
            ):
                data_refs.add(int(match.group(1), 16))
    if data_refs:
        lines.append("fs data")
        for address in sorted(data_refs):
            lines.append(f"f data.DAT_{address:08x} 4 @ 0x{address:08x}")
        lines.append("")

    lines.append("fs functions")
    lines.append("")
    return "\n".join(lines)


def write_generated_replay(
    root: Path,
    resolved: ResolvedTarget,
    layout: ReviewedLayout,
    inventory: SourceInventory,
) -> Path:
    """Render and atomically write the generated replay under ``out/analysis/replay``."""

    import os
    import tempfile

    rendered = render_generated_replay(
        layout=layout,
        inventory=inventory,
        splat_path=resolved.splat_path,
        source_dir=resolved.source_dir,
    )
    output = replay_output_path(root, resolved.id)
    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temp_name = tempfile.mkstemp(
        dir=output.parent, prefix=f".{output.name}.", suffix=".tmp"
    )
    temp_path = Path(temp_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as f:
            f.write(rendered)
            f.flush()
            os.fsync(f.fileno())
        temp_path.replace(output)
    except BaseException:
        temp_path.unlink(missing_ok=True)
        raise
    return output


def build_replay_plan(
    root: Path,
    resolved: ResolvedTarget,
    layout: ReviewedLayout,
    inventory: SourceInventory,
    *,
    include_aar: bool = False,
) -> ReplayPlan:
    """Build the analyzer command plan for a target.

    Only function starts from reviewed layouts and source bindings are
    seeded.  Broad analysis (``aaa``/``aar``) is optional.
    """

    binary_end = resolved.load_address + resolved.binary_size
    addresses: list[int] = []
    for address in layout.reviewed_function_addresses:
        if resolved.load_address <= address < binary_end:
            addresses.append(address)
    for func in inventory.functions:
        if func.address not in addresses:
            if resolved.load_address <= func.address < binary_end:
                addresses.append(func.address)
    addresses = sorted(set(addresses))

    commands: list[str] = []
    for index, address in enumerate(addresses):
        commands.append(f"af @ 0x{address:08x}")
        if include_aar:
            next_address = addresses[index + 1] if index + 1 < len(addresses) else None
            next_boundary = binary_end if next_address is None else next_address
            span = min(max(next_boundary - address, 0), 0x1000)
            if span > 0:
                commands.append(f"aar 0x{span:x} @ 0x{address:08x}")

    # Shared analysis types.
    types = root / "config" / "analysis" / "shared" / "bof3_objects.h"
    if types.is_file():
        commands.append(f"to {types}")

    # Shared hardware-register flags.
    hwregs = root / "config" / "analysis" / "shared" / "hwregs.r2"
    if hwregs.is_file():
        commands.append(f". {hwregs}")

    # Generated replay.
    generated = replay_output_path(root, resolved.id)
    if generated.is_file():
        commands.append(f". {generated}")

    # Reviewed replay (loaded last so it overrides generated presentation).
    if resolved.reviewed_replay_path.is_file():
        commands.append(f". {resolved.reviewed_replay_path}")

    inputs = build_replay_inputs(root, resolved, inventory)
    return ReplayPlan(inputs=inputs, commands=tuple(commands))


__all__ = [
    "ReplayInputs",
    "ReplayPlan",
    "build_replay_inputs",
    "build_replay_plan",
    "render_generated_replay",
    "replay_output_path",
    "reviewed_replay_path",
    "write_generated_replay",
]
