name: world01_area060_13
sha1: f8798be3fac11a393a03e01a650b02ed368c4f66
options:
  platform: psx
  compiler: psyq
  basename: world01_area060_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world01/area060/13.bin
  asm_path: out/splat/emi/world01/area060/13/asm
  src_path: src/emi/world01/area060/13
  ld_script_path: out/splat/emi/world01/area060/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 0
        - asm
        - func_801F2C00
      - - 1672
        - asm
        - func_801F3288
  - - 0x888
