name: plchar_plp578_00
sha1: 63c398c3831ab9bfad347a9d640f1d9ef4344fa3
options:
  platform: psx
  compiler: psyq
  basename: plchar_plp578_00
  base_path: ../../../../../..
  target_path: out/binaries/emi/plchar/plp578/00.bin
  asm_path: out/splat/emi/plchar/plp578/00/asm
  src_path: src/emi/plchar/plp578/00
  ld_script_path: out/splat/emi/plchar/plp578/00/linker.ld
  undefined_funcs_auto_path: out/splat/emi/plchar/plp578/00/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/plchar/plp578/00/undefined_syms_auto.txt
  cache_path: out/splat/emi/plchar/plp578/00/.splache
  asset_path: out/splat/emi/plchar/plp578/00/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/plchar/plp578/00/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149377028
  subsegments:
  - - 4
    - asm
    - func_801CE404
  - - 72
    - asm
    - func_801CE448
  - - 276
    - asm
    - func_801CE514
  - - 528
    - asm
    - func_801CE610
  - - 596
    - asm
    - func_801CE654
  - - 1056
    - asm
    - func_801CE820
  - - 1324
    - asm
    - func_801CE92C
  - - 1536
    - asm
    - func_801CEA00
  - - 1604
    - asm
    - func_801CEA44
  - - 1848
    - asm
    - func_801CEB38
  - - 2100
    - asm
    - func_801CEC34
  - - 2168
    - asm
    - func_801CEC78
  - - 3012
    - asm
    - func_801CEFC4
  - - 3424
    - asm
    - func_801CF160
  - - 3660
    - asm
    - func_801CF24C
  - - 4164
    - asm
    - func_801CF444
  - - 4392
    - asm
    - func_801CF528
  - - 4700
    - asm
    - func_801CF65C
  - - 4768
    - asm
    - func_801CF6A0
  - - 4972
    - asm
    - func_801CF76C
  - - 5224
    - asm
    - func_801CF868
  - - 5292
    - asm
    - func_801CF8AC
  - - 5572
    - asm
    - func_801CF9C4
  - - 5680
    - asm
    - func_801CFA30
  - - 5748
    - asm
    - func_801CFA74
  - - 5816
    - asm
    - func_801CFAB8
- - 5908
