name: world00_area015_13
sha1: 054345f7693a7cc75475025cc784703a80b4977a
options:
  platform: psx
  compiler: psyq
  basename: world00_area015_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world00/area015/13.bin
  asm_path: out/splat/emi/world00/area015/13/asm
  src_path: src/emi/world00/area015/13
  ld_script_path: out/splat/emi/world00/area015/13/linker.ld
  undefined_funcs_auto_path: out/splat/emi/world00/area015/13/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/world00/area015/13/undefined_syms_auto.txt
  cache_path: out/splat/emi/world00/area015/13/.splache
  asset_path: out/splat/emi/world00/area015/13/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world00/area015/13/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149526532
  subsegments:
  - - 4
    - asm
    - func_801F2C04
  - - 184
    - asm
    - func_801F2CB8
  - - 248
    - c
    - setWorld00Area01513_801F2CF8
  - - 268
    - c
    - retreatCounter2By20World00Area01513_801F2D0C
  - - 308
    - c
    - advanceCounter2By20World00Area01513_801F2D34
  - - 348
    - c
    - setTwoWorld00Area01513_801F2D5C
  - - 376
    - asm
    - func_801F2D78
  - - 444
    - asm
    - func_801F2DBC
  - - 608
    - asm
    - func_801F2E60
  - - 744
    - asm
    - func_801F2EE8
  - - 812
    - asm
    - func_801F2F2C
- - 976
  - bin
  - tail
- - 5384
