schema = "harness.target/v2"
id = "emi/world00/area015/13"
disc_id = "BIN/WORLD00/AREA015.EMI#13"
kind = "emi"
source_dir = "src/emi/world00/area015/13"
binary = "out/binaries/emi/world00/area015/13.bin"
splat = "config/targets/emi/world00/area015/13/splat.yaml"
load_address = 0x801F2C00

sources = []
support_sources = [
    "src/bof3/world00/setWorld00Area01513_801F2CF8.c",
    "src/bof3/support/area015_13_psyq.c",
]
psyq_source = "src/bof3/support/area015_13_psyq.c"
