schema = "harness.target/v2"
id = "emi/boss/boss008/16"
disc_id = "BIN/BOSS/BOSS008.EMI#16"
kind = "emi"
source_dir = "src/emi/boss/boss008/16"
binary = "out/binaries/emi/boss/boss008/16.bin"
splat = "config/targets/emi/boss/boss008/16/splat.yaml"
load_address = 0x800C1800

sources = []
support_sources = [
    "src/bof3/boss/invokeHelperBossBoss00816_800C1C68.c",
    "src/bof3/boss/zeroResultBossBoss00816_800C22B8.c",
    "src/bof3/boss/zeroResultBossBoss00816_800C21BC.c",
    "src/bof3/boss/zeroResultBossBoss00816_800C20C0.c",
    "src/bof3/boss/zeroResultBossBoss00816_800C1FD4.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1F94.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1F8C.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1F84.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1EA8.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1EA0.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1E98.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1DBC.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1DB4.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1DAC.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1CD0.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1CC8.c",
    "src/bof3/boss/noopHandlerBossBoss00816_800C1CC0.c",
    "src/bof3/support/boss008_16_psyq.c",
]
psyq_source = "src/bof3/support/boss008_16_psyq.c"
