name: etc_shop_00
sha1: 3325ceebfcf11eab5cc062fbe24900730b60c644
options:
  platform: psx
  compiler: psyq
  basename: etc_shop_00
  base_path: ../../../../..
  target_path: out/binaries/emi/etc/shop/00.bin
  asm_path: out/splat/emi/etc/shop/00/asm
  src_path: src/emi/etc/shop/00
  ld_script_path: out/splat/emi/etc/shop/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - [0x0, bin]
  - [0x1566C]
