name: bmagic_magic091_03
sha1: f92002801aba138f918b75f5583ada397c85c797
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic091_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic091/03.bin
  asm_path: out/splat/emi/bmagic/magic091/03/asm
  src_path: src/emi/bmagic/magic091/03
  ld_script_path: out/splat/emi/bmagic/magic091/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic091/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic091/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic091/03/.splache
  asset_path: out/splat/emi/bmagic/magic091/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic091/03/symbols.txt
segments:
- - 0
  - bin
  - header
- - 4
  - bin
  - tabledata
- name: main
  type: code
  start: 16
  vram: 2149510160
  subsegments:
  - - 16
    - asm
    - func_801EEC10
  - - 204
    - asm
    - func_801EECCC
  - - 572
    - asm
    - func_801EEE3C
  - - 680
    - asm
    - func_801EEEA8
  - - 884
    - asm
    - func_801EEF74
  - - 1020
    - asm
    - func_801EEFFC
  - - 1180
    - asm
    - func_801EF09C
  - - 1316
    - asm
    - func_801EF124
  - - 1464
    - asm
    - func_801EF1B8
  - - 1600
    - asm
    - func_801EF240
  - - 2816
    - asm
    - func_801EF700
  - - 2992
    - asm
    - func_801EF7B0
  - - 3556
    - asm
    - func_801EF9E4
  - - 4196
    - asm
    - func_801EFC64
- - 4212
