name: world01_area058_13
sha1: 2d62db8fcf0247036a037b7897f8aa08af61906b
options:
  platform: psx
  compiler: psyq
  basename: world01_area058_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world01/area058/13.bin
  asm_path: out/splat/emi/world01/area058/13/asm
  src_path: src/emi/world01/area058/13
  ld_script_path: out/splat/emi/world01/area058/13/linker.ld
  undefined_funcs_auto_path: out/splat/emi/world01/area058/13/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/world01/area058/13/undefined_syms_auto.txt
  cache_path: out/splat/emi/world01/area058/13/.splache
  asset_path: out/splat/emi/world01/area058/13/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world01/area058/13/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149526532
  subsegments:
  - - 4
    - asm
    - func_801F2C04
  - - 116
    - asm
    - func_801F2C74
- - 3916
