name: world01_area042_13
sha1: 07a9d63a8bd99809af5499235fabe5cfb771cb56
options:
  platform: psx
  compiler: psyq
  basename: world01_area042_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world01/area042/13.bin
  asm_path: out/splat/emi/world01/area042/13/asm
  src_path: src/emi/world01/area042/13
  ld_script_path: out/splat/emi/world01/area042/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 452
        - asm
        - func_801F2DC4
      - - 632
        - asm
        - func_801F2E78
      - - 1216
        - asm
        - func_801F30C0
      - - 1664
        - asm
        - func_801F3280
      - - 2984
        - asm
        - func_801F37A8
      - - 4376
        - asm
        - func_801F3D18
      - - 5512
        - asm
        - func_801F4188
      - - 7948
        - asm
        - func_801F4B0C
  - - 0x2afc
