name: world02_area098_13
sha1: de06ce51ae4037781cf74840c6331c2a28d5c01d
options:
  platform: psx
  compiler: psyq
  basename: world02_area098_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world02/area098/13.bin
  asm_path: out/splat/emi/world02/area098/13/asm
  src_path: src/emi/world02/area098/13
  ld_script_path: out/splat/emi/world02/area098/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 5284
        - asm
        - func_801F40A4
      - - 5328
        - asm
        - func_801F40D0
      - - 5664
        - asm
        - func_801F4220
      - - 5864
        - asm
        - func_801F42E8
      - - 6288
        - asm
        - func_801F4490
      - - 6892
        - asm
        - func_801F46EC
      - - 7400
        - asm
        - func_801F48E8
      - - 8128
        - asm
        - func_801F4BC0
      - - 8516
        - asm
        - func_801F4D44
      - - 8576
        - asm
        - func_801F4D80
      - - 8636
        - asm
        - func_801F4DBC
      - - 8828
        - asm
        - func_801F4E7C
      - - 9296
        - asm
        - func_801F5050
      - - 9792
        - asm
        - func_801F5240
      - - 9836
        - asm
        - func_801F526C
      - - 9992
        - asm
        - func_801F5308
      - - 10172
        - asm
        - func_801F53BC
      - - 10624
        - asm
        - func_801F5580
      - - 11296
        - asm
        - func_801F5820
      - - 11584
        - asm
        - func_801F5940
  - - 0x3924
