name: world00_area008_13
sha1: 36803dffa90dc5de61bc195aa2f7465051fabbad
options:
  platform: psx
  compiler: psyq
  base_path: .
  target_path: out/extracted/BIN/WORLD00/AREA008/13.bin
  asm_path: out/splat/world00/area008/13/asm
  src_path: src/emi/world00/area008/13
  ld_script_path: out/splat/world00/area008/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - [0x0, bin]
