name: world00_area008_13
sha1: 36803dffa90dc5de61bc195aa2f7465051fabbad
options:
  platform: psx
  compiler: psyq
  base_path: .
  target_path: out/binaries/emi/world00/area008/13.bin
  asm_path: out/splat/emi/world00/area008/13/asm
  src_path: src/emi/world00/area008/13
  ld_script_path: out/splat/emi/world00/area008/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - [0x0, bin, header]
  - name: main
    type: code
    start: 0x14
    vram: 0x801f2c14
    subsegments:
      - [0x14, asm, func_801f2c14]
      - [0x5c, asm, func_801f2c5c]
      - [0x88, asm, func_801f2c88]
      - [0x124, asm, func_801f2d24]
      - [0x21c, asm, func_801f2e1c]
      - [0x324, asm, func_801f2f24]
      - [0x378, asm, func_801f2f78]
      - [0x410, asm, func_801f3010]
      - [0x4b8, asm, func_801f30b8]
      - [0x57c, asm, func_801f317c]
      - [0x5d0, asm, func_801f31d0]
      - [0x688, asm, func_801f3288]
      - [0x6ac, asm, func_801f32ac]
      - [0x744, asm, func_801f3344]
      - [0x7f0, asm, func_801f33f0]
      - [0x8fc, asm, func_801f34fc]
      - [0x97c, asm, func_801f357c]
      - [0xa54, asm, func_801f3654]
      - [0xa5c, asm, func_801f365c]
      - [0xadc, asm, func_801f36dc]
      - [0xbb4, asm, func_801f37b4]
      - [0xbbc, asm, func_801f37bc]
      - [0xc5c, asm, func_801f385c]
      - [0xcdc, asm, func_801f38dc]
      - [0xdb4, asm, func_801f39b4]
      - [0xdbc, asm, func_801f39bc]
      - [0xea8, asm, func_801f3aa8]
      - [0xee8, asm, func_801f3ae8]
      - [0xfb4, asm, func_801f3bb4]
      - [0x102c, c, func_801f3c2c]
      - [0x1118, c, func_801f3d18]
      - [0x1188, c, func_801f3d88]
      - [0x16d4, asm, func_801f42d4]
      - [0x1734, asm, func_801f4334]
      - [0x177c, asm, func_801f437c]
      - [0x17c8, asm, func_801f43c8]
      - [0x1824, asm, func_801f4424]
      - [0x190c, asm, func_801f450c]
      - [0x1934, asm, func_801f4534]
      - [0x1960, asm, func_801f4560]
      - [0x1978, asm, func_801f4578]
      - [0x19a0, asm, func_801f45a0]
      - [0x19cc, asm, func_801f45cc]
      - [0x19e4, asm, func_801f45e4]
      - [0x1a00, asm, func_801f4600]
      - [0x1a1c, asm, func_801f461c]
  - [0x1a74, bin, data]
  - [0x27f8]
