name: world00_area008_13
sha1: 36803dffa90dc5de61bc195aa2f7465051fabbad
options:
  platform: psx
  compiler: psyq
  basename: world00_area008_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world00/area008/13.bin
  asm_path: out/splat/emi/world00/area008/13/asm
  src_path: src/emi/world00/area008/13
  ld_script_path: out/splat/emi/world00/area008/13/linker.ld
  symbol_addrs_path:
  - config/symbols/emi/world00/area008/13.txt
segments:
- - 0
  - bin
  - header
- - 20
  - bin
  - entry_header
- name: main
  type: code
  start: 24
  vram: 2149526552
  subsegments:
  - - 24
    - c
    - func_801f2c18
  - - 92
    - c
    - func_801f2c5c
  - - 136
    - c
    - func_801f2c88
  - - 292
    - asm
    - func_801f2d24
  - - 540
    - asm
    - func_801f2e1c
  - - 804
    - asm
    - func_801f2f24
  - - 888
    - asm
    - func_801f2f78
  - - 1040
    - asm
    - func_801f3010
  - - 1208
    - asm
    - func_801f30b8
  - - 1404
    - asm
    - func_801f317c
  - - 1488
    - asm
    - func_801f31d0
  - - 1604
    - asm
    - func_801f3244
  - - 1672
    - asm
    - func_801f3288
  - - 1708
    - asm
    - func_801f32ac
  - - 1860
    - asm
    - func_801f3344
  - - 2032
    - asm
    - func_801f33f0
  - - 2300
    - asm
    - func_801f34fc
  - - 2428
    - asm
    - func_801f357c
  - - 2644
    - asm
    - func_801f3654
  - - 2652
    - asm
    - func_801f365c
  - - 2780
    - asm
    - func_801f36dc
  - - 2996
    - asm
    - func_801f37b4
  - - 3004
    - asm
    - func_801f37bc
  - - 3164
    - asm
    - func_801f385c
  - - 3292
    - asm
    - func_801f38dc
  - - 3508
    - asm
    - func_801f39b4
  - - 3516
    - asm
    - func_801f39bc
  - - 3684
    - asm
    - func_801f3a64
  - - 3752
    - asm
    - func_801f3aa8
  - - 3816
    - asm
    - func_801f3ae8
  - - 4020
    - asm
    - func_801f3bb4
  - - 4140
    - c
    - func_801f3c2c
  - - 4376
    - c
    - func_801f3d18
  - - 4488
    - c
    - func_801f3d88
  - - 5844
    - asm
    - func_801f42d4
  - - 5940
    - asm
    - func_801f4334
  - - 6012
    - asm
    - func_801f437c
  - - 6088
    - asm
    - func_801f43c8
  - - 6180
    - asm
    - func_801f4424
  - - 6412
    - asm
    - func_801f450c
  - - 6452
    - asm
    - func_801f4534
  - - 6492
    - asm
    - func_801f455c
  - - 6496
    - asm
    - func_801f4560
  - - 6520
    - asm
    - func_801f4578
  - - 6560
    - asm
    - func_801f45a0
  - - 6600
    - asm
    - func_801f45c8
  - - 6604
    - asm
    - func_801f45cc
  - - 6628
    - asm
    - func_801f45e4
  - - 6656
    - asm
    - func_801f4600
  - - 6684
    - asm
    - func_801f461c
- - 6772
  - bin
  - data
- - 10232
