name: bmagic_magic173_03
sha1: 259154c12caa4bcba3b8712ad7e044f4a10fcbb6
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic173_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic173/03.bin
  asm_path: out/splat/emi/bmagic/magic173/03/asm
  src_path: src/emi/bmagic/magic173/03
  ld_script_path: out/splat/emi/bmagic/magic173/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 2284
        - asm
        - func_801EF4EC
      - - 3636
        - asm
        - func_801EFA34
      - - 5808
        - asm
        - func_801F02B0
      - - 6048
        - asm
        - func_801F03A0
      - - 7004
        - asm
        - func_801F075C
  - - 0x1eb0
