name: world03_area151_13
sha1: 9558d851e8d7371eb41fbfbd1946940c91f194d9
options:
  platform: psx
  compiler: psyq
  basename: world03_area151_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world03/area151/13.bin
  asm_path: out/splat/emi/world03/area151/13/asm
  src_path: src/emi/world03/area151/13
  ld_script_path: out/splat/emi/world03/area151/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 1904
        - asm
        - func_801F3370
      - - 2104
        - asm
        - func_801F3438
      - - 2344
        - asm
        - func_801F3528
      - - 2556
        - asm
        - func_801F35FC
      - - 3400
        - asm
        - func_801F3948
      - - 3696
        - asm
        - func_801F3A70
      - - 4668
        - asm
        - func_801F3E3C
      - - 5172
        - asm
        - func_801F4034
  - - 0x290e
