name: bmagic_magic144_03
sha1: ee0b0e3e5e013ca292d46af26087f2b35298f288
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic144_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic144/03.bin
  asm_path: out/splat/emi/bmagic/magic144/03/asm
  src_path: src/emi/bmagic/magic144/03
  ld_script_path: out/splat/emi/bmagic/magic144/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic144/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic144/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic144/03/.splache
  asset_path: out/splat/emi/bmagic/magic144/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic144/03/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149510148
  subsegments:
  - - 4
    - asm
    - func_801EEC04
  - - 260
    - asm
    - func_801EED04
  - - 592
    - asm
    - func_801EEE50
  - - 668
    - asm
    - func_801EEE9C
  - - 736
    - asm
    - func_801EEEE0
  - - 872
    - asm
    - func_801EEF68
  - - 1144
    - asm
    - func_801EF078
  - - 1308
    - asm
    - func_801EF11C
  - - 1364
    - asm
    - func_801EF154
  - - 1508
    - asm
    - func_801EF1E4
  - - 1684
    - asm
    - func_801EF294
  - - 2320
    - asm
    - func_801EF510
  - - 2388
    - asm
    - func_801EF554
  - - 2516
    - asm
    - func_801EF5D4
  - - 2644
    - asm
    - func_801EF654
  - - 2724
    - asm
    - func_801EF6A4
  - - 2872
    - asm
    - func_801EF738
  - - 3096
    - asm
    - func_801EF818
  - - 4980
    - asm
    - func_801EFF74
  - - 5172
    - asm
    - func_801F0034
  - - 5280
    - asm
    - func_801F00A0
  - - 5360
    - asm
    - func_801F00F0
  - - 5428
    - asm
    - func_801F0134
  - - 5584
    - asm
    - func_801F01D0
  - - 6252
    - asm
    - func_801F046C
  - - 6352
    - asm
    - func_801F04D0
- - 12172
