name: world03_area129_04
sha1: 82eb9a2b88b06bb760bbff7227caea315360467d
options:
  platform: psx
  compiler: psyq
  basename: world03_area129_04
  base_path: ../../../../..
  target_path: out/binaries/emi/world03/area129/04.bin
  asm_path: out/splat/emi/world03/area129/04/asm
  src_path: src/emi/world03/area129/04
  ld_script_path: out/splat/emi/world03/area129/04/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149387264
    subsegments:
      - - 1472
        - asm
        - func_801D11C0
      - - 2460
        - asm
        - func_801D159C
      - - 2884
        - asm
        - func_801D1744
      - - 3096
        - asm
        - func_801D1818
      - - 3276
        - asm
        - func_801D18CC
      - - 3420
        - asm
        - func_801D195C
      - - 3976
        - asm
        - func_801D1B88
      - - 5172
        - asm
        - func_801D2034
      - - 7904
        - asm
        - func_801D2AE0
      - - 8244
        - asm
        - func_801D2C34
      - - 9796
        - asm
        - func_801D3244
      - - 11576
        - asm
        - func_801D3938
      - - 24108
        - asm
        - func_801D6A2C
      - - 24360
        - asm
        - func_801D6B28
      - - 26340
        - asm
        - func_801D72E4
      - - 27524
        - asm
        - func_801D7784
      - - 28060
        - asm
        - func_801D799C
      - - 28516
        - asm
        - func_801D7B64
      - - 28688
        - asm
        - func_801D7C10
      - - 29032
        - asm
        - func_801D7D68
      - - 29360
        - asm
        - func_801D7EB0
      - - 30280
        - asm
        - func_801D8248
      - - 30564
        - asm
        - func_801D8364
      - - 31968
        - asm
        - func_801D88E0
      - - 33136
        - asm
        - func_801D8D70
      - - 34044
        - asm
        - func_801D90FC
      - - 34636
        - asm
        - func_801D934C
      - - 35124
        - asm
        - func_801D9534
      - - 35268
        - asm
        - func_801D95C4
      - - 35648
        - asm
        - func_801D9740
      - - 42060
        - asm
        - func_801DB04C
      - - 42156
        - asm
        - func_801DB0AC
      - - 53580
        - asm
        - func_801DDD4C
      - - 53692
        - asm
        - func_801DDDBC
      - - 53804
        - asm
        - func_801DDE2C
      - - 53908
        - asm
        - func_801DDE94
      - - 53996
        - asm
        - func_801DDEEC
      - - 54140
        - asm
        - func_801DDF7C
      - - 54228
        - asm
        - func_801DDFD4
      - - 54296
        - asm
        - func_801DE018
      - - 55468
        - asm
        - func_801DE4AC
      - - 63084
        - asm
        - func_801E026C
      - - 63188
        - asm
        - func_801E02D4
      - - 63380
        - asm
        - func_801E0394
      - - 63480
        - asm
        - func_801E03F8
      - - 64128
        - asm
        - func_801E0680
      - - 64368
        - asm
        - func_801E0770
      - - 64588
        - asm
        - func_801E084C
      - - 64948
        - asm
        - func_801E09B4
      - - 65072
        - asm
        - func_801E0A30
      - - 65212
        - asm
        - func_801E0ABC
      - - 65388
        - asm
        - func_801E0B6C
      - - 65664
        - asm
        - func_801E0C80
      - - 65996
        - asm
        - func_801E0DCC
      - - 66256
        - asm
        - func_801E0ED0
      - - 66380
        - asm
        - func_801E0F4C
      - - 66564
        - asm
        - func_801E1004
      - - 67360
        - asm
        - func_801E1320
      - - 68140
        - asm
        - func_801E162C
      - - 68316
        - asm
        - func_801E16DC
      - - 68440
        - asm
        - func_801E1758
      - - 69068
        - asm
        - func_801E19CC
      - - 69648
        - asm
        - func_801E1C10
      - - 69756
        - asm
        - func_801E1C7C
  - - 0x12615
