name: world03_area129_05
sha1: c76601b7d2978bb39511537394b2e32a26f7b4fe
options:
  platform: psx
  compiler: psyq
  basename: world03_area129_05
  base_path: ../../../../..
  target_path: out/binaries/emi/world03/area129/05.bin
  asm_path: out/splat/emi/world03/area129/05/asm
  src_path: src/emi/world03/area129/05
  ld_script_path: out/splat/emi/world03/area129/05/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2148487168
    subsegments:
      - - 3652
        - asm
        - func_800F5E44
      - - 4204
        - asm
        - func_800F606C
      - - 5068
        - asm
        - func_800F63CC
      - - 5544
        - asm
        - func_800F65A8
      - - 5844
        - asm
        - func_800F66D4
      - - 5936
        - asm
        - func_800F6730
      - - 6788
        - asm
        - func_800F6A84
      - - 7260
        - asm
        - func_800F6C5C
      - - 7904
        - asm
        - func_800F6EE0
      - - 8340
        - asm
        - func_800F7094
      - - 8448
        - asm
        - func_800F7100
  - - 0x2250
