name: bmagic_magic058_03
sha1: fcaccc33ce65dac27be8044f696713e396ddb794
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic058_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic058/03.bin
  asm_path: out/splat/emi/bmagic/magic058/03/asm
  src_path: src/emi/bmagic/magic058/03
  ld_script_path: out/splat/emi/bmagic/magic058/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1900
        - asm
        - func_801EF36C
      - - 2716
        - asm
        - func_801EF69C
      - - 2892
        - asm
        - func_801EF74C
      - - 3704
        - asm
        - func_801EFA78
      - - 4564
        - asm
        - func_801EFDD4
      - - 4664
        - asm
        - func_801EFE38
      - - 4764
        - asm
        - func_801EFE9C
  - - 0x23e0
