name: battle_battle_15
sha1: 57a0526249697fe71692cf73d7abcf17f2396f14
options:
  platform: psx
  compiler: psyq
  base_path: .
  target_path: out/binaries/emi/battle/battle/15.bin
  asm_path: out/splat/emi/battle/battle/15/asm
  src_path: src/emi/battle/battle/15
  ld_script_path: out/splat/emi/battle/battle/15/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - [0x0, bin]
