name: bmagic_magic227_03
sha1: dce397eed8c7b7e82895c7c45a163daab459a9f7
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic227_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic227/03.bin
  asm_path: out/splat/emi/bmagic/magic227/03/asm
  src_path: src/emi/bmagic/magic227/03
  ld_script_path: out/splat/emi/bmagic/magic227/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 2908
        - asm
        - func_801EF75C
      - - 3092
        - asm
        - func_801EF814
      - - 3684
        - asm
        - func_801EFA64
      - - 4484
        - asm
        - func_801EFD84
      - - 5560
        - asm
        - func_801F01B8
      - - 6948
        - asm
        - func_801F0724
      - - 7124
        - asm
        - func_801F07D4
      - - 8076
        - asm
        - func_801F0B8C
      - - 8176
        - asm
        - func_801F0BF0
  - - 0x3710
