#!/usr/bin/env python3
"""Convert reviewed CSV/JSON symbols into a Rizin command script."""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from pathlib import Path
from typing import Any, Iterable

FUNCTION_KINDS = {"function", "overlay_entry", "callback", "bios", "psyq"}


def parse_int(value: Any, default: int = 0) -> int:
    if value in (None, ""):
        return default
    if isinstance(value, int):
        return value
    return int(str(value), 0)


def clean_name(name: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_.$]", "_", name.strip())
    value = re.sub(r"_+", "_", value)
    if not value:
        raise ValueError("empty symbol name")
    if value[0].isdigit():
        value = "sym_" + value
    return value


def quoted_comment(value: str) -> str:
    # fC consumes the remainder as comment; remove newlines/control separators.
    return value.replace("\r", " ").replace("\n", " ").replace(";", ",").strip()


def load_rows(path: Path) -> Iterable[dict[str, Any]]:
    if path.suffix.lower() == ".json":
        value = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(value, dict):
            value = value.get("symbols", [])
        if not isinstance(value, list):
            raise ValueError("JSON must be a list or an object containing a symbols list")
        for row in value:
            if not isinstance(row, dict):
                raise ValueError("every JSON symbol must be an object")
            yield row
        return

    with path.open("r", encoding="utf-8-sig", newline="") as stream:
        reader = csv.DictReader(stream)
        required = {"name", "address"}
        if reader.fieldnames is None or not required.issubset(reader.fieldnames):
            raise ValueError("CSV requires at least name,address columns")
        yield from reader


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path)
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument("--flagspace", default="symbols")
    args = parser.parse_args()

    commands = [
        "# Generated by symbols_to_rizin.py; review before applying.",
        f"fs {clean_name(args.flagspace)}",
    ]
    seen: set[tuple[str, int]] = set()
    try:
        for index, row in enumerate(load_rows(args.input), start=2):
            original = str(row.get("name", "")).strip()
            name = clean_name(original)
            address = parse_int(row.get("address"))
            size = max(0, parse_int(row.get("size"), 0))
            kind = str(row.get("kind", "label")).strip().lower()
            key = (name, address)
            if key in seen:
                continue
            seen.add(key)

            if size:
                commands.append(f"f {name} {size} @ 0x{address:x}")
            else:
                commands.append(f"f {name} @ 0x{address:x}")

            if kind in FUNCTION_KINDS:
                commands.append(f"af @ 0x{address:x}")
                commands.append(f"afn {name} @ 0x{address:x}")

            context = []
            for field in ("source", "confidence", "comment"):
                value = str(row.get(field, "")).strip()
                if value:
                    context.append(f"{field}={value}")
            if original != name:
                context.insert(0, f"original_name={original}")
            if context:
                commands.append(f"fC {name} {quoted_comment(' | '.join(context))}")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(commands) + "\n", encoding="utf-8")
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
