name: bmagic_magic105_03
sha1: ab297652753a50b7f32a18fda7de825138ebf222
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic105_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic105/03.bin
  asm_path: out/splat/emi/bmagic/magic105/03/asm
  src_path: src/emi/bmagic/magic105/03
  ld_script_path: out/splat/emi/bmagic/magic105/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1776
        - asm
        - func_801EF2F0
      - - 1952
        - asm
        - func_801EF3A0
      - - 3200
        - asm
        - func_801EF880
      - - 4236
        - asm
        - func_801EFC8C
      - - 4336
        - asm
        - func_801EFCF0
  - - 0x32a0
