name: world00_area027_13
sha1: 01a5283eecec11937760e912e76b32a702d7d66b
options:
  platform: psx
  compiler: psyq
  basename: world00_area027_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world00/area027/13.bin
  asm_path: out/splat/emi/world00/area027/13/asm
  src_path: src/emi/world00/area027/13
  ld_script_path: out/splat/emi/world00/area027/13/linker.ld
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world00/area027/13/symbols.txt
segments:
- name: main
  type: code
  start: 0
  vram: 2149526528
  subsegments:
  - - 0
    - rodata
    - T_801F2C00
  - - 48
    - c
    - func_801F2C30
    - '@source: src/bof3/world/func_801F2C30.c'
    - '@behavior: Dispatches scratch mode byte 1 through the local handler table.'
  - - 116
    - asm
    - func_801F2C74
  - - 348
    - asm
    - func_801F2D5C
  - - 572
    - asm
    - func_801F2E3C
  - - 780
    - c
    - emitTrailStrip
    - '@source: src/bof3/world/emitTrailStrip.c'
    - '@behavior: Emits a 31-segment Gouraud line strip across the projected trail.'
  - - 1100
    - asm
    - func_801F304C
  - - 1312
    - c
    - func_801F3120
    - '@source: src/bof3/world/func_801F3120.c'
    - '@behavior: Dispatches scratch mode byte 2 through the local handler table.'
  - - 1380
    - asm
    - func_801F3164
  - - 1484
    - c
    - emitMarkerPair
    - '@source: src/bof3/world/emitMarkerPair.c'
    - '@behavior: Advances local scratch state and emits two fixed world markers.'
  - - 1712
    - asm
    - func_801F32B0
  - - 1960
    - asm
    - func_801F33A8
  - - 2176
    - asm
    - emitMarkerQuad
    - '@source: src/bof3/world/emitMarkerQuad.c'
    - '@behavior: Projects a fixed textured quad and fills its texture state.'
  - - 2528
    - c
    - func_801F35E0
    - '@source: src/bof3/world/func_801F35E0.c'
    - '@behavior: Resets a state value and conditionally enables a pair of flags.'
  - - 2584
    - c
    - func_801F3618
    - '@source: src/bof3/world/func_801F3618.c'
    - '@behavior: Resets area state and conditionally arms two flags.'
  - - 2640
    - asm
    - func_801F3650
  - - 2704
    - asm
    - func_801F3690
  - - 2768
    - asm
    - func_801F36D0
  - - 2832
    - asm
    - func_801F3710
  - - 2924
    - asm
    - func_801F376C
  - - 3044
    - asm
    - func_801F37E4
  - - 3404
    - asm
    - func_801F394C
  - - 3764
    - asm
    - T_801F3AB4
- - 8548
