name: world02_area095_13
sha1: 95ef8cc15d0e4d87d3be2324f049284725929e55
options:
  platform: psx
  compiler: psyq
  basename: world02_area095_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world02/area095/13.bin
  asm_path: out/splat/emi/world02/area095/13/asm
  src_path: src/emi/world02/area095/13
  ld_script_path: out/splat/emi/world02/area095/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 828
        - asm
        - func_801F2F3C
      - - 2128
        - asm
        - func_801F3450
  - - 0x129c
