name: scenario_scena16_00
sha1: 2285180d11a5d091bc750b19b786b7045a2cf144
options:
  platform: psx
  compiler: psyq
  basename: scenario_scena16_00
  base_path: ../../../../..
  target_path: out/binaries/emi/scenario/scena16/00.bin
  asm_path: out/splat/emi/scenario/scena16/00/asm
  src_path: src/emi/scenario/scena16/00
  ld_script_path: out/splat/emi/scenario/scena16/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - [0x0, bin]
  - [0x1978]
