name: scenario_scena16_00
sha1: 2285180d11a5d091bc750b19b786b7045a2cf144
options:
  platform: psx
  compiler: psyq
  basename: scenario_scena16_00
  base_path: ../../../../..
  target_path: out/binaries/emi/scenario/scena16/00.bin
  asm_path: out/splat/emi/scenario/scena16/00/asm
  src_path: src/emi/scenario/scena16/00
  ld_script_path: out/splat/emi/scenario/scena16/00/linker.ld
  symbol_addrs_path:
  - config/symbols/emi/scenario/scena16/00.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 2108
  vram: 2149545020
  subsegments:
  - - 2108
    - asm
    - func_801F743C
  - - 2960
    - asm
    - func_801F7790
  - - 4292
    - asm
    - func_801F7CC4
  - - 5976
    - asm
    - func_801F8358
  - - 6040
    - asm
    - func_801F8398
  - - 6048
    - asm
    - func_801F83A0
  - - 6056
    - asm
    - func_801F83A8
  - - 6064
    - asm
    - func_801F83B0
  - - 6236
    - asm
    - func_801F845C
  - - 6316
    - asm
    - func_801F84AC
  - - 6448
    - asm
    - func_801F8530
  - - 6456
    - asm
    - func_801F8538
- - 6520
  - bin
  - data
- - 6520
