name: bmagic_magic120_03
sha1: 4f8640570369abff35c4b3ecb1941c2e1b2526c5
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic120_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic120/03.bin
  asm_path: out/splat/emi/bmagic/magic120/03/asm
  src_path: src/emi/bmagic/magic120/03
  ld_script_path: out/splat/emi/bmagic/magic120/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 2124
        - asm
        - func_801EF44C
      - - 5748
        - asm
        - func_801F0274
      - - 6320
        - asm
        - func_801F04B0
      - - 7052
        - asm
        - func_801F078C
      - - 7340
        - asm
        - func_801F08AC
      - - 7540
        - asm
        - func_801F0974
      - - 8184
        - asm
        - func_801F0BF8
  - - 0x2114
