name: bmagic_magic073_03
sha1: 78d6681ebc4675de624c8101ca47176d8e5c5d04
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic073_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic073/03.bin
  asm_path: out/splat/emi/bmagic/magic073/03/asm
  src_path: src/emi/bmagic/magic073/03
  ld_script_path: out/splat/emi/bmagic/magic073/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 0
        - asm
        - func_801EEC00
      - - 2852
        - asm
        - func_801EF724
      - - 4088
        - asm
        - func_801EFBF8
      - - 4652
        - asm
        - func_801EFE2C
      - - 5316
        - asm
        - func_801F00C4
      - - 6120
        - asm
        - func_801F03E8
      - - 6228
        - asm
        - func_801F0454
      - - 6308
        - asm
        - func_801F04A4
  - - 0x35f4
