name: bmagic_magic071_03
sha1: e2ba32963a4e29244ab7a0627ee2b9fde1745aee
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic071_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic071/03.bin
  asm_path: out/splat/emi/bmagic/magic071/03/asm
  src_path: src/emi/bmagic/magic071/03
  ld_script_path: out/splat/emi/bmagic/magic071/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1852
        - asm
        - func_801EF33C
      - - 3088
        - asm
        - func_801EF810
      - - 3652
        - asm
        - func_801EFA44
      - - 4316
        - asm
        - func_801EFCDC
      - - 5120
        - asm
        - func_801F0000
      - - 5228
        - asm
        - func_801F006C
  - - 0x2bb8
