schema = "harness.target/v2"
id = "emi/plchar/plp678/00"
disc_id = "BIN/PLCHAR/PLP678.EMI#0"
kind = "emi"
source_dir = "src/emi/plchar/plp678/00"
binary = "out/binaries/emi/plchar/plp678/00.bin"
splat = "config/splat/emi/plchar/plp678/00.yaml"
load_address = 0x801ce400
profile = "compat/capcom97"
