name: bmagic_magic073_03
sha1: 78d6681ebc4675de624c8101ca47176d8e5c5d04
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic073_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic073/03.bin
  asm_path: out/splat/emi/bmagic/magic073/03/asm
  src_path: src/emi/bmagic/magic073/03
  ld_script_path: out/splat/emi/bmagic/magic073/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic073/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic073/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic073/03/.splache
  asset_path: out/splat/emi/bmagic/magic073/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic073/03/symbols.txt
segments:
- - 0
  - bin
  - header
- - 4
  - bin
  - tabledata
- name: main
  type: code
  start: 40
  vram: 2149510184
  subsegments:
  - - 40
    - asm
    - func_801EEC28
  - - 280
    - asm
    - func_801EED18
  - - 848
    - asm
    - func_801EEF50
  - - 944
    - asm
    - func_801EEFB0
  - - 1012
    - asm
    - func_801EEFF4
  - - 1132
    - asm
    - func_801EF06C
  - - 1756
    - asm
    - func_801EF2DC
  - - 2004
    - asm
    - func_801EF3D4
  - - 2276
    - asm
    - func_801EF4E4
  - - 2348
    - asm
    - func_801EF52C
  - - 2744
    - asm
    - func_801EF6B8
  - - 2852
    - asm
    - func_801EF724
  - - 2920
    - asm
    - func_801EF768
  - - 3172
    - asm
    - func_801EF864
  - - 3684
    - asm
    - func_801EFA64
  - - 3860
    - asm
    - func_801EFB14
  - - 4088
    - asm
    - func_801EFBF8
  - - 4652
    - asm
    - func_801EFE2C
  - - 5316
    - asm
    - func_801F00C4
  - - 6120
    - asm
    - func_801F03E8
  - - 6228
    - asm
    - func_801F0454
  - - 6308
    - asm
    - func_801F04A4
  - - 6564
    - asm
    - D_801F05A4
- - 13812
