name: plchar_plp026_00
sha1: 28f822aa9cf6e7223850439d0821b506620b208a
options:
  platform: psx
  compiler: psyq
  basename: plchar_plp026_00
  base_path: ../../../../..
  target_path: out/binaries/emi/plchar/plp026/00.bin
  asm_path: out/splat/emi/plchar/plp026/00/asm
  src_path: src/emi/plchar/plp026/00
  ld_script_path: out/splat/emi/plchar/plp026/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149377024
    subsegments:
      - - 0
        - asm
        - func_801CE400
      - - 2332
        - asm
        - func_801CED1C
      - - 2836
        - asm
        - func_801CEF14
      - - 3064
        - asm
        - func_801CEFF8
      - - 4564
        - asm
        - func_801CF5D4
      - - 4920
        - asm
        - func_801CF738
      - - 5128
        - asm
        - func_801CF808
      - - 7496
        - asm
        - func_801D0148
      - - 8020
        - asm
        - func_801D0354
      - - 8900
        - asm
        - func_801D06C4
      - - 9320
        - asm
        - func_801D0868
  - - 0x26cc
