name: world00_area028_13
sha1: 86f4d6a7a62372374e6a6c297d6a242ec02274e6
options:
  platform: psx
  compiler: psyq
  basename: world00_area028_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world00/area028/13.bin
  asm_path: out/splat/emi/world00/area028/13/asm
  src_path: src/emi/world00/area028/13
  ld_script_path: out/splat/emi/world00/area028/13/linker.ld
  symbol_addrs_path:
  - config/targets/emi/world00/area028/13/symbols.txt
segments:
- name: main
  type: code
  start: 0
  vram: 2149526528
  subsegments:
  - - 0
    - asm
    - T_801F2C00
  - - 72
    - asm
    - func_801F2C48
  - - 128
    - asm
    - func_801F2C80
  - - 284
    - c
    - func_801F2D1C
  - - 316
    - asm
    - func_801F2D3C
  - - 860
    - asm
    - func_801F2F5C
  - - 944
    - asm
    - func_801F2FB0
  - - 1028
    - asm
    - func_801F3004
  - - 1120
    - asm
    - func_801F3060
  - - 1420
    - asm
    - func_801F318C
  - - 2068
    - asm
    - func_801F3414
  - - 2076
    - asm
    - func_801F341C
  - - 2084
    - asm
    - func_801F3424
  - - 2216
    - asm
    - T_801F34A8
- - 4612
  - bin
  - data
- - 4612
