name: bmagic_magic062_03
sha1: 55a6120535050524ea235ee5f2b2200b306d48d6
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic062_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic062/03.bin
  asm_path: out/splat/emi/bmagic/magic062/03/asm
  src_path: src/emi/bmagic/magic062/03
  ld_script_path: out/splat/emi/bmagic/magic062/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1776
        - asm
        - func_801EF2F0
      - - 2068
        - asm
        - func_801EF414
      - - 2680
        - asm
        - func_801EF678
      - - 3380
        - asm
        - func_801EF934
      - - 5740
        - asm
        - func_801F026C
      - - 7440
        - asm
        - func_801F0910
  - - 0x203c
