name: bmagic_magic112_00
sha1: 65b68a97b029cd8f4c93c1721597a5701a81d018
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic112_00
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic112/00.bin
  asm_path: out/splat/emi/bmagic/magic112/00/asm
  src_path: src/emi/bmagic/magic112/00
  ld_script_path: out/splat/emi/bmagic/magic112/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 404
        - asm
        - func_801EED94
      - - 860
        - asm
        - func_801EEF5C
  - - 0x558
