schema = "harness.target/v2"
id = "emi/scenario/scena07/00"
disc_id = "BIN/SCENARIO/SCENA07.EMI#0"
kind = "emi"
source_dir = "src/emi/scenario/scena07/00"
binary = "out/binaries/emi/scenario/scena07/00.bin"
splat = "config/targets/emi/scenario/scena07/00/splat.yaml"
load_address = 0x801F6C00

sources = []
support_sources = [
    "src/bof3/scenario/noopHandlerScenarioScena0700_801FAA68.c",
    "src/bof3/support/scena07_00_psyq.c",
]
psyq_source = "src/bof3/support/scena07_00_psyq.c"
