schema = "harness.target/v2"
id = "emi/scenario/scena05/00"
disc_id = "BIN/SCENARIO/SCENA05.EMI#0"
kind = "emi"
source_dir = "src/emi/scenario/scena05/00"
binary = "out/binaries/emi/scenario/scena05/00.bin"
splat = "config/targets/emi/scenario/scena05/00/splat.yaml"
load_address = 0x801F6C00

sources = []
support_sources = [
    "src/bof3/scenario/invokeZeroArgScenarioScena0500_801FD36C.c",
    "src/bof3/scenario/invokeHelperArgScenarioScena0500_801FD440.c",
    "src/bof3/scenario/invokeHelperArgScenarioScena0500_801FD34C.c",
    "src/bof3/scenario/invokeHelperArgScenarioScena0500_801FD32C.c",
    "src/bof3/scenario/invokeHelperArgScenarioScena0500_801FD30C.c",
    "src/bof3/scenario/invokeHelperScenarioScena0500_801F7640.c",
    "src/bof3/scenario/invokeHelperScenarioScena0500_801F74CC.c",
    "src/bof3/scenario/setScenarioScena0500_801F7AB4.c",
    "src/bof3/scenario/zeroResultScenarioScena0500_801FCD60.c",
    "src/bof3/scenario/noopHandlerScenarioScena0500_801FCA98.c",
    "src/bof3/scenario/noopHandlerScenarioScena0500_801F989C.c",
    "src/bof3/scenario/noopHandlerScenarioScena0500_801F937C.c",
    "src/bof3/scenario/noopHandlerScenarioScena0500_801F855C.c",
    "src/bof3/scenario/noopHandlerScenarioScena0500_801F8554.c",
    "src/bof3/scenario/noopHandlerScenarioScena0500_801F8428.c",
    "src/bof3/scenario/invokeHelperArgThenHelperScenarioScena0500_801FD508.c",
    "src/bof3/scenario/incrementWorkByte1SetCounterScenarioScena0500_801F7530.c",
    "src/bof3/support/scena05_00_psyq.c",
    "src/bof3/scenario/incrementWorkByte1ClearCounterScenarioScena0500_801F743C.c",
    "src/bof3/scenario/invokeHelperArgThenHelperScenarioScena0500_801FD530.c",
    "src/bof3/scenario/invokeHelperArgThenHelperScenarioScena0500_801FD558.c",
    "src/bof3/scenario/invokeHelperArgThenHelperScenarioScena0500_801FD580.c",
    "src/bof3/scenario/invokeHelperTwiceThenHelperScenarioScena0500_801FD4D8.c",
    "src/bof3/scenario/dispatchScenarioStateHandlerScenarioScena0500_801F7A78.c",
    "src/bof3/scenario/dispatchPrimaryStateHandlerScenarioScena0500_801F83EC.c",
    "src/bof3/scenario/armEffectGroupThenInvokeTwoHelpersScenarioScena0500_801FD38C.c",
    "src/bof3/scenario/armEffectGroupThenInvokeTwoHelpersScenarioScena0500_801FD3C8.c",
]
psyq_source = "src/bof3/support/scena05_00_psyq.c"
