name: bmagic_magic129_03
sha1: 803c4def2c58245b652bb369c37bed6790cca3cf
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic129_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic129/03.bin
  asm_path: out/splat/emi/bmagic/magic129/03/asm
  src_path: src/emi/bmagic/magic129/03
  ld_script_path: out/splat/emi/bmagic/magic129/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 2380
        - asm
        - func_801EF54C
      - - 4928
        - asm
        - func_801EFF40
      - - 5900
        - asm
        - func_801F030C
      - - 6400
        - asm
        - func_801F0500
      - - 6500
        - asm
        - func_801F0564
  - - 0x37d8
