name: bmagic_magic114_03
sha1: 59ff8c4390f5dcf8447c493578693af58b226732
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic114_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic114/03.bin
  asm_path: out/splat/emi/bmagic/magic114/03/asm
  src_path: src/emi/bmagic/magic114/03
  ld_script_path: out/splat/emi/bmagic/magic114/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic114/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic114/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic114/03/.splache
  asset_path: out/splat/emi/bmagic/magic114/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic114/03/symbols.txt
segments:
- - 0
  - bin
  - header
- - 4
  - bin
  - tabledata
- name: main
  type: code
  start: 68
  vram: 2149510212
  subsegments:
  - - 68
    - asm
    - func_801EEC44
  - - 416
    - asm
    - func_801EEDA0
  - - 644
    - asm
    - func_801EEE84
  - - 740
    - asm
    - func_801EEEE4
  - - 836
    - asm
    - func_801EEF44
  - - 1020
    - asm
    - func_801EEFFC
  - - 1120
    - asm
    - func_801EF060
  - - 1212
    - asm
    - func_801EF0BC
  - - 1320
    - asm
    - func_801EF128
  - - 1664
    - asm
    - func_801EF280
  - - 2728
    - asm
    - func_801EF6A8
  - - 2932
    - asm
    - func_801EF774
  - - 3000
    - asm
    - func_801EF7B8
  - - 3068
    - asm
    - func_801EF7FC
  - - 3264
    - asm
    - func_801EF8C0
  - - 3712
    - asm
    - func_801EFA80
  - - 4568
    - asm
    - func_801EFDD8
  - - 4720
    - asm
    - func_801EFE70
  - - 4892
    - asm
    - func_801EFF1C
  - - 5040
    - asm
    - func_801EFFB0
  - - 5124
    - asm
    - func_801F0004
  - - 6356
    - asm
    - func_801F04D4
  - - 7484
    - asm
    - func_801F093C
  - - 8456
    - asm
    - func_801F0D08
  - - 8556
    - asm
    - func_801F0D6C
  - - 8780
    - asm
    - func_801F0E4C
  - - 8848
    - asm
    - func_801F0E90
  - - 9148
    - asm
    - func_801F0FBC
  - - 9716
    - asm
    - func_801F11F4
- - 9796
