"""Generate sorted CMake source registration from target manifests."""

from __future__ import annotations

from pathlib import Path
import re

from ..domain import load_target_manifests


def _cmake_name(target_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", target_id).strip("_").upper()


def generate_build_manifest(root: Path, output: Path | None = None) -> Path:
    root = root.resolve()
    output = output or root / "out" / "build" / "sources.cmake"
    manifests = load_target_manifests(root)
    lines = [
        "# Generated by harness registry; do not edit.",
        "# Source ownership comes from config/targets/*.toml.",
        "",
    ]
    for target_id, manifest in sorted(manifests.items()):
        source_root = root / manifest.source_dir
        files = sorted(
            path
            for directory in (source_root, source_root / "symbols")
            for pattern in ("*.c", "*.s")
            for path in directory.glob(pattern)
            if path.is_file()
        )
        variable = f"HARNESS_TARGET_{_cmake_name(target_id)}_SOURCES"
        lines.append(f"set({variable}")
        lines.extend(f"    {path.relative_to(root).as_posix()}" for path in files)
        lines.append(")")
        lines.append("")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    return output
