"""Generate sorted CMake source and target registration from target manifests."""

from __future__ import annotations

from pathlib import Path
import re

from ..domain import load_target_manifests


def _cmake_name(target_id: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", target_id).strip("_").upper()


def _emi_program_name(entry_index: int) -> str:
    """Return zero-padded two-digit program name from the canonical slot index."""
    return f"{entry_index:02d}.bin"


def _raw_binary_size(root: Path, binary_path: str) -> int | None:
    path = root / binary_path
    if path.is_file():
        return path.stat().st_size
    return None


def generate_build_manifest(root: Path, output: Path | None = None) -> Path:
    root = root.resolve()
    output = output or root / "out" / "build" / "sources.cmake"
    manifests = load_target_manifests(root)
    lines = [
        "# Generated by harness registry; do not edit.",
        "# Source ownership comes from config/targets/*.toml.",
        "",
    ]
    for target_id, manifest in sorted(manifests.items()):
        if manifest.status != "active":
            continue
        source_root = root / manifest.source_dir
        files = sorted(
            path
            for directory in (source_root, source_root / "symbols")
            for pattern in ("*.c", "*.s")
            for path in directory.glob(pattern)
            if path.is_file()
        )
        variable = f"HARNESS_TARGET_{_cmake_name(target_id)}_SOURCES"
        lines.append(f"set({variable}")
        lines.extend(f"    {path.relative_to(root).as_posix()}" for path in files)
        lines.append(")")
        lines.append("")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    return output


def generate_target_manifest(root: Path, output: Path | None = None) -> Path:
    """Generate harness_add_artifact calls from target manifests."""
    root = root.resolve()
    output = output or root / "out" / "build" / "targets.cmake"
    manifests = load_target_manifests(root)

    # Hard-coded exceptions discovered during repository review.
    PLACEHOLDERS = {
        "emi/etc/shop/00",
        "emi/etc/sisyou/00",
        "emi/battle/battle/15",
        "emi/scenario/scena00/00",
    }
    RAW_BINARY = "emi/battle/battle/03"

    lines = [
        "# Generated by harness registry; do not edit.",
        "# Artifact registration comes from config/targets/*.toml.",
        "",
    ]

    for target_id, manifest in sorted(manifests.items()):
        if manifest.status != "active":
            continue
        cmake_var = _cmake_name(target_id)
        if target_id.startswith("exe/"):
            target_name = target_id[4:].replace("/", "_")
        else:
            target_name = target_id.replace("/", "_")
        disc_id = manifest.disc_id

        # Derive DISC_FOLDER, PROGRAM_NAME, PROGRAM_PATH from disc_id.
        emi_match = re.search(r"\.EMI#(\d+)$", disc_id)
        if emi_match:
            # EMI archive entry
            disc_folder = disc_id[: disc_id.rfind(".EMI#")]
            entry_index = int(emi_match.group(1))
            program_name = _emi_program_name(entry_index)
            program_path = f"/bins/{disc_folder}/{program_name}"
        else:
            # PS-X executable
            if "/" in disc_id:
                disc_folder, program_name = disc_id.rsplit("/", 1)
            else:
                disc_folder = ""
                program_name = disc_id
            if disc_folder:
                program_path = f"/boot/{disc_folder}/{program_name}"
            else:
                program_path = f"/boot/{program_name}"

        cmake_disc_folder = disc_folder or "/"

        source_hint = f"${{HARNESS_EXTRACTED_DIR}}/{disc_id}"

        # Derive KIND from target identity.
        if target_id == "exe/slus_004_22":
            kind = "boot"
        elif target_id == "exe/logo":
            kind = "logo"
        else:
            kind = "module"

        # Derive DECLARED_SOURCES.
        if target_id == "exe/slus_004_22":
            declared_sources = "${HARNESS_CORE_SOURCES}"
        else:
            declared_sources = f"${{HARNESS_TARGET_{cmake_var}_SOURCES}}"

        # Assemble harness_add_artifact arguments.
        args: list[str] = [
            f"    {target_name}",
            f'    DISC_FOLDER "{cmake_disc_folder}"',
            f'    PROGRAM_NAME "{program_name}"',
            f'    PROGRAM_PATH "{program_path}"',
            f'    SOURCE_HINT "{source_hint}"',
            f'    KIND "{kind}"',
            f'    DECLARED_SOURCES {declared_sources}',
        ]

        if target_id == RAW_BINARY:
            args.insert(1, "    RAW_BINARY")
            args.append(f'    LOAD_ADDRESS "0x{manifest.load_address:08x}"')
            raw_size = _raw_binary_size(root, manifest.binary)
            if raw_size is not None:
                args.append(f'    RAW_SIZE "{raw_size}"')

        if target_id in PLACEHOLDERS:
            args.insert(1, "    PLACEHOLDER")

        lines.append("harness_add_artifact(")
        lines.extend(args)
        lines.append(")")
        lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    return output
