name: bmagic_magic122_03
sha1: cdd00387e7da0c04a6a77101e7ee1e84698d2307
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic122_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic122/03.bin
  asm_path: out/splat/emi/bmagic/magic122/03/asm
  src_path: src/emi/bmagic/magic122/03
  ld_script_path: out/splat/emi/bmagic/magic122/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic122/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic122/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic122/03/.splache
  asset_path: out/splat/emi/bmagic/magic122/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic122/03/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149510148
  subsegments:
  - - 4
    - asm
    - func_801EEC04
  - - 92
    - asm
    - func_801EEC5C
  - - 508
    - asm
    - func_801EEDFC
  - - 604
    - asm
    - func_801EEE5C
  - - 672
    - asm
    - func_801EEEA0
  - - 812
    - asm
    - func_801EEF2C
  - - 1368
    - asm
    - func_801EF158
  - - 1476
    - asm
    - func_801EF1C4
  - - 1612
    - asm
    - func_801EF24C
  - - 1692
    - asm
    - func_801EF29C
  - - 1828
    - asm
    - func_801EF324
  - - 4008
    - asm
    - func_801EFBA8
  - - 5836
    - asm
    - func_801F02CC
- - 5860
