name: bmagic_magic042_03
sha1: f5adb502b2ff940d198228928f20db21ba41e4e9
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic042_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic042/03.bin
  asm_path: out/splat/emi/bmagic/magic042/03/asm
  src_path: src/emi/bmagic/magic042/03
  ld_script_path: out/splat/emi/bmagic/magic042/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1456
        - asm
        - func_801EF1B0
      - - 1920
        - asm
        - func_801EF380
      - - 2844
        - asm
        - func_801EF71C
      - - 3360
        - asm
        - func_801EF920
  - - 0x103d
