name: logo
sha1: d8a873d947e386bbdb18767b74d52d9975437250
options:
  platform: psx
  compiler: psyq
  basename: logo
  base_path: ../../..
  target_path: out/binaries/exe/logo.bin
  asm_path: out/splat/exe/logo/asm
  src_path: src/exe/logo
  ld_script_path: out/splat/exe/logo/linker.ld
  symbol_addrs_path:
    - config/symbols/exe/logo.txt
segments:
  - [0x0, bin, pre_runtime_stub]
  - name: runtime_stub
    type: code
    start: 0x758
    vram: 0x801ce758
    subsegments:
      - [0x758, c, func_801ce758]
  - [0x760, bin, pre_main]
  - name: main
    type: code
    start: 0xdfc
    vram: 0x801cedfc
    subsegments:
      - [0xdfc, c, func_801cedfc]
  - [0xe7c, bin, post_main]
  - [0x1d800]
