name: logo
sha1: d8a873d947e386bbdb18767b74d52d9975437250
options:
  platform: psx
  compiler: psyq
  base_path: .
  target_path: out/binaries/exe/logo.bin
  asm_path: out/splat/exe/logo/asm
  src_path: src/exe/logo
  ld_script_path: out/splat/exe/logo/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - [0x0, bin]
