name: scenario_sce10eff_00
sha1: dd7b26475dc7e5968b9f4e4b4011167a3e664b3e
options:
  platform: psx
  compiler: psyq
  basename: scenario_sce10eff_00
  base_path: ../../../../../..
  target_path: out/binaries/emi/scenario/sce10eff/00.bin
  asm_path: out/splat/emi/scenario/sce10eff/00/asm
  src_path: src/emi/scenario/sce10eff/00
  ld_script_path: out/splat/emi/scenario/sce10eff/00/linker.ld
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/scenario/sce10eff/00/symbols.txt
segments:
- name: main
  type: code
  start: 0
  vram: 2149387264
  subsegments:
  - - 0
    - asm
    - T_801D0C00
  - - 112
    - asm
    - func_801D0C70
  - - 612
    - asm
    - func_801D0E64
  - - 668
    - c
    - func_801D0E9C
  - - 736
    - asm
    - func_801D0EE0
  - - 940
    - asm
    - func_801D0FAC
  - - 1076
    - asm
    - func_801D1034
  - - 1224
    - asm
    - func_801D10C8
  - - 1336
    - asm
    - func_801D1138
  - - 1440
    - asm
    - func_801D11A0
  - - 1560
    - asm
    - func_801D1218
  - - 1704
    - asm
    - func_801D12A8
  - - 1984
    - asm
    - func_801D13C0
  - - 2096
    - asm
    - func_801D1430
  - - 2372
    - asm
    - func_801D1544
  - - 2652
    - asm
    - func_801D165C
  - - 4440
    - asm
    - func_801D1D58
  - - 4576
    - asm
    - func_801D1DE0
  - - 4860
    - asm
    - func_801D1EFC
  - - 4944
    - asm
    - func_801D1F50
  - - 5220
    - asm
    - func_801D2064
  - - 5516
    - asm
    - func_801D218C
  - - 6156
    - asm
    - func_801D240C
  - - 6744
    - asm
    - func_801D2658
  - - 6920
    - rodata
    - T_801D2708
- - 6984
