name: plchar_plp27a_00
sha1: 5fd3de592d9ecd55cbd72c0f5b0efcba1b73d1be
options:
  platform: psx
  compiler: psyq
  basename: plchar_plp27a_00
  base_path: ../../../../..
  target_path: out/binaries/emi/plchar/plp27a/00.bin
  asm_path: out/splat/emi/plchar/plp27a/00/asm
  src_path: src/emi/plchar/plp27a/00
  ld_script_path: out/splat/emi/plchar/plp27a/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149377024
    subsegments:
      - - 1196
        - asm
        - func_801CE8AC
      - - 1552
        - asm
        - func_801CEA10
      - - 1760
        - asm
        - func_801CEAE0
      - - 4168
        - asm
        - func_801CF448
      - - 4672
        - asm
        - func_801CF640
      - - 4900
        - asm
        - func_801CF724
  - - 0x1544
