name: plchar_plp247_00
sha1: 3a836648b47e49091ab45d03e5143c33329f7b3f
options:
  platform: psx
  compiler: psyq
  basename: plchar_plp247_00
  base_path: ../../../../..
  target_path: out/binaries/emi/plchar/plp247/00.bin
  asm_path: out/splat/emi/plchar/plp247/00/asm
  src_path: src/emi/plchar/plp247/00
  ld_script_path: out/splat/emi/plchar/plp247/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149377024
    subsegments:
      - - 1196
        - asm
        - func_801CE8AC
      - - 1552
        - asm
        - func_801CEA10
      - - 1760
        - asm
        - func_801CEAE0
      - - 4708
        - asm
        - func_801CF664
      - - 5212
        - asm
        - func_801CF85C
      - - 5440
        - asm
        - func_801CF940
  - - 0x174c
