"""Tests for target-qualified deterministic macro indexing."""

from __future__ import annotations

import sqlite3
from pathlib import Path
from types import SimpleNamespace

from harness.analysis.macro_index import (
    insert_macro_registry,
    macro_input_digest,
    macro_input_rows,
)
from harness.analysis.schema import create_schema
from harness.domain.ids import normalize_target_id

TARGET = "exe/test"


def _manifest(root: Path):
    header = root / "include/private.h"
    source = root / "src/test/wrapper.c"
    psyq = root / "src/test/test_psyq.c"
    template = root / "src/shared/ui/task.inc"
    symbols = root / "include/bof3/symbols.h"
    for path in (header, source, psyq, template, symbols):
        path.parent.mkdir(parents=True, exist_ok=True)
    header.write_text(
        "#if MODE\n#define VALUE 7\n#else\n#define VALUE 8\n#endif\n",
        encoding="utf-8",
    )
    source.write_text(
        '#include "shared/ui/task.inc"\nEMIT_TASK(run_task, VALUE)\n',
        encoding="utf-8",
    )
    psyq.write_text(
        "/* Generated by bin/symbols; do not edit. */\n"
        '#include "bof3/symbols.h"\nWEAK_SYMBOL_AT(Api, 0x80100000);\n',
        encoding="utf-8",
    )
    template.write_text(
        "#define EMIT_TASK(name, value) void name(void) { use(value); }\n",
        encoding="utf-8",
    )
    symbols.write_text(
        '#define WEAK_SYMBOL_AT(name, addr) asm(".weak " #name)\n',
        encoding="utf-8",
    )
    return SimpleNamespace(
        id=normalize_target_id(TARGET),
        headers=("include/private.h",),
        sources=("src/test/wrapper.c",),
        support_sources=("src/test/test_psyq.c",),
        psyq_source="src/test/test_psyq.c",
        has_explicit_sources=True,
    )


def _connection() -> sqlite3.Connection:
    connection = sqlite3.connect(":memory:")
    create_schema(connection)
    connection.execute(
        "INSERT INTO targets VALUES (?, 'b', 'h', 0, 'rizin', 'v', 's', 'sh')",
        (TARGET,),
    )
    return connection


def _rows(
    connection: sqlite3.Connection,
) -> tuple[list[tuple], list[tuple], list[tuple]]:
    definitions = connection.execute(
        "SELECT owner_target, name, source_path, source_line, conditional_context, "
        "classification, generated, candidate_status, restrictions "
        "FROM macro_definitions ORDER BY owner_target, name, source_path, source_line"
    ).fetchall()
    uses = connection.execute(
        "SELECT target_id, name, source_path, source_line, use_context, generated, "
        "candidate_status, restrictions FROM macro_uses "
        "ORDER BY target_id, name, source_path, source_line"
    ).fetchall()
    templates = connection.execute(
        "SELECT owner_target, source_path, name, template_kind, wrapper_contract "
        "FROM macro_templates ORDER BY owner_target, source_path, name"
    ).fetchall()
    return definitions, uses, templates


def test_registry_indexes_claims_templates_and_generated_psyq(tmp_path: Path) -> None:
    manifest = _manifest(tmp_path)
    connection = _connection()

    insert_macro_registry(connection, tmp_path, TARGET, manifest)
    definitions, uses, templates = _rows(connection)

    assert [row[4] for row in definitions if row[1] == "VALUE"] == [
        '["MODE"]',
        '["else"]',
    ]
    assert any(
        row[:4] == ("__shared__", "EMIT_TASK", "src/shared/ui/task.inc", 1)
        and row[5] == "body_emitting_template"
        for row in definitions
    )
    weak_use = next(row for row in uses if row[1] == "WEAK_SYMBOL_AT")
    assert weak_use[5:7] == (1, "noncandidate")
    assert "generator_owned" in weak_use[7]
    assert templates == [
        (
            "__shared__",
            "src/shared/ui/task.inc",
            "EMIT_TASK",
            "body_emitting_inc",
            "target_local_wrapper_required",
        )
    ]


def test_registry_rows_and_fingerprints_are_deterministic_and_stale_safe(
    tmp_path: Path,
) -> None:
    manifest = _manifest(tmp_path)
    first = _connection()
    insert_macro_registry(first, tmp_path, TARGET, manifest)
    first_rows = _rows(first)
    inputs = macro_input_rows(tmp_path, TARGET, manifest)
    assert inputs == sorted(inputs)

    second = _connection()
    insert_macro_registry(second, tmp_path, TARGET, manifest)

    assert _rows(second) == first_rows
    assert macro_input_digest(inputs) == macro_input_digest(
        macro_input_rows(tmp_path, TARGET, manifest)
    )
    (tmp_path / "src/test/wrapper.c").write_text("EMIT_TASK(run_task, 9)\n")
    assert macro_input_rows(tmp_path, TARGET, manifest) != inputs
