"""Tests for lexical C preprocessor macro facts."""

from __future__ import annotations

from harness.domain.macro_facts import (
    parse_macro_definitions,
    parse_macro_file,
    parse_macro_uses,
)


def test_parser_preserves_conditional_definitions_and_multiline_body() -> None:
    macros = parse_macro_definitions(
        """#if defined(__GNUC__)
#define PICK(value) ((value) + \\
                     1)
#else
#define PICK(value) 0
#endif
#define LIMIT 17
#define EMPTY()
""",
        source="include/example.h",
    )

    assert [(macro.name, macro.conditions) for macro in macros] == [
        ("PICK", ("defined(__GNUC__)",)),
        ("PICK", ("else",)),
        ("LIMIT", ()),
        ("EMPTY", ()),
    ]
    assert macros[0].parameters == ("value",)
    assert macros[0].body == "((value) +\n                     1)"
    assert macros[0].source_line == 2
    assert macros[1].body == "0"
    assert macros[2].parameters is None
    assert macros[2].classification == "object_like"
    assert macros[3].parameters == ()
    assert macros[3].classification == "function_like"


def test_directives_inside_comments_and_strings_are_ignored() -> None:
    macros = parse_macro_definitions(
        """/* #define COMMENTED 1 */
const char *text = "#define STRING 2";
#define REAL(value) "/* literal */" value // #define TRAILING 3
"""
    )

    assert [macro.name for macro in macros] == ["REAL"]
    assert macros[0].body == '"/* literal */" value // #define TRAILING 3'


def test_nested_condition_context_is_retained() -> None:
    macros = parse_macro_definitions(
        """#ifdef OUTER
#if INNER
#define VALUE 1
#elif OTHER
#define VALUE 2
#endif
#endif
"""
    )

    assert [macro.conditions for macro in macros] == [
        ("defined(OUTER)", "INNER"),
        ("defined(OUTER)", "OTHER"),
    ]


def test_generated_helpers_restrictions_and_inc_templates() -> None:
    macros = parse_macro_definitions(
        """/* Generated by tool; do not edit. */
#define REGISTER_PIN(type, name, reg) register type name asm(reg)
#define INCLUDE_ASM(folder, name) __asm__(name)
#define PANEL_TASK(func, limit) \\
void func(void) { \\
    step(limit); \\
}
""",
        source="src/shared/ui/panel_task.inc",
    )
    by_name = {macro.name: macro for macro in macros}

    assert by_name["REGISTER_PIN"].classification == "matching_helper"
    assert by_name["REGISTER_PIN"].restrictions == (
        "allocator_constraint",
        "generator_owned",
    )
    assert by_name["INCLUDE_ASM"].restrictions == (
        "inline_assembly",
        "generator_owned",
    )
    assert by_name["PANEL_TASK"].classification == "body_emitting_template"
    assert all(macro.generated for macro in macros)


def test_malformed_final_continuation_has_diagnostic() -> None:
    (macro,) = parse_macro_definitions("#define BROKEN(value) value + \\")

    assert macro.body == "value +"
    assert macro.diagnostic == "unterminated macro continuation"


def test_parse_macro_file_uses_path_for_inc_classification(tmp_path) -> None:
    source = tmp_path / "template.inc"
    source.write_text("#define EMIT(name) void name(void) {}\n", encoding="utf-8")

    (macro,) = parse_macro_file(source)

    assert macro.classification == "body_emitting_template"
    assert macro.source_line == 1


def test_macro_uses_ignore_comments_literals_and_definition_names() -> None:
    uses = parse_macro_uses(
        """#if ENABLED
#define WRAP(value) HELPER(value)
WRAP(HELPER(1))
#endif
/* WRAP(2) */
const char *text = "HELPER(3)";
""",
        {"WRAP", "HELPER"},
    )

    assert [(use.name, use.context, use.source_line) for use in uses] == [
        ("HELPER", "definition_body", 2),
        ("WRAP", "expansion", 3),
        ("HELPER", "expansion", 3),
    ]
    assert uses[0].conditions == ("ENABLED",)
    assert uses[1].arguments == "HELPER(1)"
