name: plchar_plp467_00
sha1: bed2979edbf4f540cd075e6d15d8358e5a25763e
options:
  platform: psx
  compiler: psyq
  basename: plchar_plp467_00
  base_path: ../../../../..
  target_path: out/binaries/emi/plchar/plp467/00.bin
  asm_path: out/splat/emi/plchar/plp467/00/asm
  src_path: src/emi/plchar/plp467/00
  ld_script_path: out/splat/emi/plchar/plp467/00/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149377024
    subsegments:
      - - 2628
        - asm
        - func_801CEE44
      - - 3152
        - asm
        - func_801CF050
      - - 4032
        - asm
        - func_801CF3C0
      - - 4452
        - asm
        - func_801CF564
      - - 6932
        - asm
        - func_801CFF14
      - - 7436
        - asm
        - func_801D010C
      - - 7664
        - asm
        - func_801D01F0
  - - 0x201c
