schema = "harness.target/v2"
id = "emi/boss/boss001/13"
disc_id = "BIN/BOSS/BOSS001.EMI#13"
kind = "emi"
source_dir = "src/emi/boss/boss001/13"
binary = "out/binaries/emi/boss/boss001/13.bin"
splat = "config/targets/emi/boss/boss001/13/splat.yaml"
load_address = 0x800C1800

sources = []
support_sources = [
    "src/bof3/boss/noopHandlerBossBoss00113_800C1E48.c",
    "src/bof3/boss/noopHandlerBossBoss00113_800C1E40.c",
    "src/bof3/boss/noopHandlerBossBoss00113_800C1E38.c",
    "src/bof3/boss/noopHandlerBossBoss00113_800C1B38.c",
    "src/bof3/boss/noopHandlerBossBoss00113_800C1B30.c",
    "src/bof3/boss/noopHandlerBossBoss00113_800C1B28.c",
    "src/bof3/support/boss001_13_psyq.c",
]
psyq_source = "src/bof3/support/boss001_13_psyq.c"
