name: bmagic_magic088_03
sha1: 04d394c9b7affb680316de8970fa199ee9e5dec9
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic088_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic088/03.bin
  asm_path: out/splat/emi/bmagic/magic088/03/asm
  src_path: src/emi/bmagic/magic088/03
  ld_script_path: out/splat/emi/bmagic/magic088/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1868
        - asm
        - func_801EF34C
      - - 2096
        - asm
        - func_801EF430
      - - 2700
        - asm
        - func_801EF68C
      - - 3816
        - asm
        - func_801EFAE8
      - - 3892
        - asm
        - func_801EFB34
  - - 0x146c
