name: bmagic_magic053_03
sha1: 52b2337cb386ed9d866101e01c432586623984c2
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic053_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic053/03.bin
  asm_path: out/splat/emi/bmagic/magic053/03/asm
  src_path: src/emi/bmagic/magic053/03
  ld_script_path: out/splat/emi/bmagic/magic053/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic053/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic053/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic053/03/.splache
  asset_path: out/splat/emi/bmagic/magic053/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic053/03/symbols.txt
segments:
- - 0
  - bin
  - header
- - 4
  - bin
  - tabledata
- name: main
  type: code
  start: 16
  vram: 2149510160
  subsegments:
  - - 16
    - asm
    - func_801EEC10
  - - 280
    - asm
    - func_801EED18
  - - 924
    - asm
    - func_801EEF9C
  - - 1028
    - asm
    - func_801EF004
  - - 1124
    - asm
    - func_801EF064
  - - 1192
    - asm
    - func_801EF0A8
  - - 1396
    - asm
    - func_801EF174
  - - 2080
    - asm
    - func_801EF420
  - - 2496
    - asm
    - func_801EF5C0
  - - 2676
    - asm
    - func_801EF674
  - - 2776
    - asm
    - func_801EF6D8
  - - 2856
    - asm
    - func_801EF728
  - - 3040
    - asm
    - func_801EF7E0
  - - 3632
    - asm
    - func_801EFA30
  - - 4432
    - asm
    - func_801EFD50
  - - 4500
    - asm
    - func_801EFD94
  - - 4636
    - asm
    - func_801EFE1C
  - - 4900
    - asm
    - func_801EFF24
  - - 5144
    - asm
    - func_801F0018
  - - 5392
    - asm
    - func_801F0110
  - - 5568
    - asm
    - func_801F01C0
  - - 6292
    - asm
    - func_801F0494
  - - 6392
    - asm
    - func_801F04F8
  - - 6472
    - asm
    - D_801F0548
- - 10360
