name: boss_boss007_16
sha1: a238e50a49770a678263390d0d4069080bfcd986
options:
  platform: psx
  compiler: psyq
  basename: boss_boss007_16
  base_path: ../../../../../..
  target_path: out/binaries/emi/boss/boss007/16.bin
  asm_path: out/splat/emi/boss/boss007/16/asm
  src_path: src/emi/boss/boss007/16
  ld_script_path: out/splat/emi/boss/boss007/16/linker.ld
  undefined_funcs_auto_path: out/splat/emi/boss/boss007/16/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/boss/boss007/16/undefined_syms_auto.txt
  cache_path: out/splat/emi/boss/boss007/16/.splache
  asset_path: out/splat/emi/boss/boss007/16/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/boss/boss007/16/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2148276228
  subsegments:
  - - 4
    - asm
    - func_800C1804
  - - 100
    - asm
    - func_800C1864
  - - 188
    - asm
    - func_800C18BC
  - - 244
    - c
    - noopHandlerBossBoss00716_800C18F4
  - - 252
    - c
    - noopHandlerBossBoss00716_800C18FC
  - - 260
    - c
    - noopHandlerBossBoss00716_800C1904
  - - 268
    - asm
    - func_800C190C
  - - 336
    - asm
    - func_800C1950
  - - 436
    - asm
    - func_800C19B4
  - - 492
    - c
    - noopHandlerBossBoss00716_800C19EC
  - - 500
    - c
    - clearRecordHalfwordFourBossBoss00716_800C19F4
  - - 516
    - c
    - noopHandlerBossBoss00716_800C1A04
  - - 524
    - asm
    - func_800C1A0C
  - - 580
    - asm
    - func_800C1A44
  - - 1204
    - asm
    - func_800C1CB4
  - - 1360
    - c
    - invokeHelperArgZeroThenOneBossBoss00716_800C1D50
  - - 1400
    - asm
    - D_800C1D78
- - 1560
