schema = "harness.target/v2"
id = "emi/boss/boss007/16"
disc_id = "BIN/BOSS/BOSS007.EMI#16"
kind = "emi"
source_dir = "src/emi/boss/boss007/16"
binary = "out/binaries/emi/boss/boss007/16.bin"
splat = "config/targets/emi/boss/boss007/16/splat.yaml"
load_address = 0x800C1800

sources = []
support_sources = [
    "src/bof3/boss/clearRecordHalfwordFourBossBoss00716_800C19F4.c",
    "src/bof3/boss/invokeHelperArgZeroThenOneBossBoss00716_800C1D50.c",
    "src/bof3/boss/noopHandlerBossBoss00716_800C1A04.c",
    "src/bof3/boss/noopHandlerBossBoss00716_800C19EC.c",
    "src/bof3/boss/noopHandlerBossBoss00716_800C1904.c",
    "src/bof3/boss/noopHandlerBossBoss00716_800C18FC.c",
    "src/bof3/boss/noopHandlerBossBoss00716_800C18F4.c",
    "src/bof3/support/boss007_16_psyq.c",
]
psyq_source = "src/bof3/support/boss007_16_psyq.c"
