name: bmagic_magic126_03
sha1: 28db1ba303b924bc41ac6fc04ba79842247273bc
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic126_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic126/03.bin
  asm_path: out/splat/emi/bmagic/magic126/03/asm
  src_path: src/emi/bmagic/magic126/03
  ld_script_path: out/splat/emi/bmagic/magic126/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1304
        - asm
        - func_801EF118
      - - 1480
        - asm
        - func_801EF1C8
      - - 2104
        - asm
        - func_801EF438
      - - 2980
        - asm
        - func_801EF7A4
      - - 4444
        - asm
        - func_801EFD5C
      - - 6828
        - asm
        - func_801F06AC
      - - 7452
        - asm
        - func_801F091C
      - - 8912
        - asm
        - func_801F0ED0
      - - 9488
        - asm
        - func_801F1110
      - - 9580
        - asm
        - func_801F116C
      - - 9644
        - asm
        - func_801F11AC
  - - 0x36c0
