bof3_add_artifact(
    bof3_bate_03
    DISC_FOLDER "BIN/ETC/BATE"
    PROGRAM_NAME "3.bin"
    PROGRAM_PATH "/bins/BIN/ETC/BATE/3.bin"
    SOURCE_HINT "${BOF3_EXTRACTED_DIR}/BIN/ETC/BATE.EMI#3"
    DECLARED_SOURCES ${BOF3_MODULE_BATE_03_SOURCES}
)
