harness_add_artifact(
    emi_etc_bate_03
    DISC_FOLDER "BIN/ETC/BATE"
    PROGRAM_NAME "3.bin"
    PROGRAM_PATH "/bins/BIN/ETC/BATE/3.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/ETC/BATE.EMI#3"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_ETC_BATE_03_SOURCES}
)
