harness_add_artifact(
    emi_battle_batl_re2_01
    DISC_FOLDER "BIN/BATTLE/BATL_RE2"
    PROGRAM_NAME "01.bin"
    PROGRAM_PATH "/bins/BIN/BATTLE/BATL_RE2/01.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/BATTLE/BATL_RE2.EMI#1"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_BATTLE_BATL_RE2_01_SOURCES}
)

harness_add_artifact(
    emi_battle_battle_03
    RAW_BINARY
    DISC_FOLDER "BIN/BATTLE/BATTLE"
    PROGRAM_NAME "03.bin"
    PROGRAM_PATH "/bins/BIN/BATTLE/BATTLE/03.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/BATTLE/BATTLE.EMI#3"
    LOAD_ADDRESS "0x801d0c00"
    RAW_SIZE "118224"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_BATTLE_BATTLE_03_SOURCES}
)

harness_add_artifact(
    emi_battle_battle_15
    PLACEHOLDER
    DISC_FOLDER "BIN/BATTLE/BATTLE"
    PROGRAM_NAME "15.bin"
    PROGRAM_PATH "/bins/BIN/BATTLE/BATTLE/15.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/BATTLE/BATTLE.EMI#15"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_BATTLE_BATTLE_15_SOURCES}
)
