harness_add_artifact(
    emi_etc_commu00_00
    DISC_FOLDER "BIN/ETC/COMMU00"
    PROGRAM_NAME "00.bin"
    PROGRAM_PATH "/bins/BIN/ETC/COMMU00/00.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/ETC/COMMU00.EMI#0"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_ETC_COMMU00_00_SOURCES}
)
