bof3_define_module_artifact(
    bof3_commu00_00_raw
    DISC_FOLDER "BIN/ETC/COMMU00"
    PROGRAM_NAME "00.bin"
    PROGRAM_PATH "/bins/BIN/ETC/COMMU00/00.bin"
    SOURCE_HINT "${BOF3_EXTRACTED_DIR}/BIN/ETC/COMMU00.EMI#0"
    DECLARED_SOURCES ${BOF3_MODULE_COMMU00_00_SOURCES}
)
