harness_add_artifact(
    emi_etc_shop_00
    PLACEHOLDER
    DISC_FOLDER "BIN/ETC/SHOP"
    PROGRAM_NAME "00.bin"
    PROGRAM_PATH "/bins/BIN/ETC/SHOP/00.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/ETC/SHOP.EMI#0"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_ETC_SHOP_00_SOURCES}
)

harness_add_artifact(
    emi_etc_sisyou_00
    PLACEHOLDER
    DISC_FOLDER "BIN/ETC/SISYOU"
    PROGRAM_NAME "00.bin"
    PROGRAM_PATH "/bins/BIN/ETC/SISYOU/00.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/ETC/SISYOU.EMI#0"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_ETC_SISYOU_00_SOURCES}
)
