bof3_define_module_artifact(
    bof3_game_00_raw
    DISC_FOLDER "BIN/ETC/GAME"
    PROGRAM_NAME "00.bin"
    PROGRAM_PATH "/bins/BIN/ETC/GAME/00.bin"
    SOURCE_HINT "${BOF3_EXTRACTED_DIR}/BIN/ETC/GAME.EMI#0"
    DECLARED_SOURCES ${BOF3_MODULE_GAME_00_SOURCES}
)

bof3_define_module_artifact(
    bof3_game_01_raw
    DISC_FOLDER "BIN/ETC/GAME"
    PROGRAM_NAME "01.bin"
    PROGRAM_PATH "/bins/BIN/ETC/GAME/01.bin"
    SOURCE_HINT "${BOF3_EXTRACTED_DIR}/BIN/ETC/GAME.EMI#1"
    DECLARED_SOURCES ${BOF3_MODULE_GAME_01_SOURCES}
)
