harness_add_artifact(
    emi_etc_game_00
    DISC_FOLDER "BIN/ETC/GAME"
    PROGRAM_NAME "00.bin"
    PROGRAM_PATH "/bins/BIN/ETC/GAME/00.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/ETC/GAME.EMI#0"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_ETC_GAME_00_SOURCES}
)

harness_add_artifact(
    emi_etc_game_01
    DISC_FOLDER "BIN/ETC/GAME"
    PROGRAM_NAME "01.bin"
    PROGRAM_PATH "/bins/BIN/ETC/GAME/01.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/ETC/GAME.EMI#1"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_ETC_GAME_01_SOURCES}
)
