harness_add_artifact(
    emi_etc_scena16_00
    DISC_FOLDER "BIN/ETC/SCENA16"
    PROGRAM_NAME "00.bin"
    PROGRAM_PATH "/bins/BIN/ETC/SCENA16/00.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/ETC/SCENA16.EMI#0"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_ETC_SCENA16_00_SOURCES}
)
