harness_add_artifact(
    emi_scenario_sce10eff_00
    DISC_FOLDER "BIN/SCENARIO/SCE10EFF"
    PROGRAM_NAME "0.bin"
    PROGRAM_PATH "/bins/BIN/SCENARIO/SCE10EFF/0.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/SCENARIO/SCE10EFF.EMI#0"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_SCENARIO_SCE10EFF_00_SOURCES}
)

harness_add_artifact(
    emi_scenario_scena00_00
    PLACEHOLDER
    DISC_FOLDER "BIN/SCENARIO/SCENA00"
    PROGRAM_NAME "00.bin"
    PROGRAM_PATH "/bins/BIN/SCENARIO/SCENA00/00.bin"
    SOURCE_HINT "${HARNESS_EXTRACTED_DIR}/BIN/SCENARIO/SCENA00.EMI#0"
    DECLARED_SOURCES ${HARNESS_TARGET_EMI_SCENARIO_SCENA00_00_SOURCES}
)
