name: bmagic_magic059_03
sha1: 5394ff5b2315a6f12f7ede00c229fb278b6def24
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic059_03
  base_path: ../../../../../..
  target_path: out/binaries/emi/bmagic/magic059/03.bin
  asm_path: out/splat/emi/bmagic/magic059/03/asm
  src_path: src/emi/bmagic/magic059/03
  ld_script_path: out/splat/emi/bmagic/magic059/03/linker.ld
  undefined_funcs_auto_path: out/splat/emi/bmagic/magic059/03/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/bmagic/magic059/03/undefined_syms_auto.txt
  cache_path: out/splat/emi/bmagic/magic059/03/.splache
  asset_path: out/splat/emi/bmagic/magic059/03/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/bmagic/magic059/03/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149510148
  subsegments:
  - - 4
    - asm
    - func_801EEC04
  - - 268
    - asm
    - func_801EED0C
  - - 1304
    - asm
    - func_801EF118
  - - 1504
    - asm
    - func_801EF1E0
  - - 1572
    - asm
    - func_801EF224
  - - 2244
    - asm
    - func_801EF4C4
  - - 2308
    - asm
    - func_801EF504
  - - 2416
    - asm
    - func_801EF570
  - - 2496
    - asm
    - func_801EF5C0
  - - 2616
    - asm
    - func_801EF638
  - - 2828
    - asm
    - func_801EF70C
  - - 4680
    - asm
    - func_801EFE48
  - - 4748
    - asm
    - func_801EFE8C
  - - 5144
    - asm
    - func_801F0018
  - - 5232
    - asm
    - func_801F0070
  - - 5340
    - asm
    - func_801F00DC
  - - 5420
    - asm
    - func_801F012C
  - - 5540
    - asm
    - func_801F01A4
  - - 6288
    - asm
    - func_801F0490
  - - 6388
    - asm
    - func_801F04F4
  - - 6468
    - asm
    - func_801F0544
  - - 6748
    - asm
    - func_801F065C
- - 9684
