name: logo
sha1: d8a873d947e386bbdb18767b74d52d9975437250
options:
  platform: psx
  compiler: psyq
  basename: logo
  base_path: ../../..
  target_path: out/binaries/exe/logo.bin
  asm_path: out/splat/exe/logo/asm
  src_path: src/exe/logo
  ld_script_path: out/splat/exe/logo/linker.ld
  symbol_addrs_path:
    - config/targets/exe/logo/symbols.txt
segments:
  - [0x0, bin, pre_runtime_stub]
  - name: runtime_stub
    type: code
    start: 0x758
    vram: 0x801ce758
    subsegments:
      - [0x758, c, func_801CE758]
  - name: pre_main
    type: code
    start: 0x760
    vram: 0x801ce760
    subsegments:
      - [0x760, c, func_801CE760]
      - [0x7f4, asm, func_801CE7F4]
      - [0x930, asm, func_801CE930]
      - [0xa98, asm, func_801CEA98]
      - [0xbfc, asm, func_801CEBFC]
      - [0xd48, asm, func_801CED48]
      - [0xda4, asm, func_801CEDA4]
  - name: main
    type: code
    start: 0xdfc
    vram: 0x801cedfc
    subsegments:
      - [0xdfc, c, func_801CEDFC]
  - [0xe7c, bin, post_main]
  - [0x1d800]
