name: world01_area038_13
sha1: a69c768ba2b2625fdc4efb07e856bff389e17234
options:
  platform: psx
  compiler: psyq
  basename: world01_area038_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world01/area038/13.bin
  asm_path: out/splat/emi/world01/area038/13/asm
  src_path: src/emi/world01/area038/13
  ld_script_path: out/splat/emi/world01/area038/13/linker.ld
  undefined_funcs_auto_path: out/splat/emi/world01/area038/13/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/world01/area038/13/undefined_syms_auto.txt
  cache_path: out/splat/emi/world01/area038/13/.splache
  asset_path: out/splat/emi/world01/area038/13/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world01/area038/13/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149526532
  subsegments:
  - - 4
    - asm
    - func_801F2C04
  - - 76
    - asm
    - func_801F2C4C
  - - 148
    - asm
    - func_801F2C94
  - - 608
    - asm
    - func_801F2E60
  - - 1068
    - asm
    - D_801F302C
- - 4492
