name: world01_area045_13
sha1: 0e94027d28be23ec6af5dfdbc7824c39e7f5d322
options:
  platform: psx
  compiler: psyq
  basename: world01_area045_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world01/area045/13.bin
  asm_path: out/splat/emi/world01/area045/13/asm
  src_path: src/emi/world01/area045/13
  ld_script_path: out/splat/emi/world01/area045/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 2048
        - asm
        - func_801F3400
      - - 2248
        - asm
        - func_801F34C8
      - - 2488
        - asm
        - func_801F35B8
      - - 2700
        - asm
        - func_801F368C
      - - 3544
        - asm
        - func_801F39D8
      - - 3840
        - asm
        - func_801F3B00
      - - 4812
        - asm
        - func_801F3ECC
      - - 5316
        - asm
        - func_801F40C4
  - - 0x281a
