schema = "harness.target/v2"
id = "emi/scenario/sce15ef1/00"
disc_id = "BIN/SCENARIO/SCE15EF1.EMI#0"
kind = "emi"
source_dir = "src/emi/scenario/sce15ef1/00"
binary = "out/binaries/emi/scenario/sce15ef1/00.bin"
splat = "config/targets/emi/scenario/sce15ef1/00/splat.yaml"
load_address = 0x801D0C00

sources = []
support_sources = [
    "src/bof3/scenario/invokeHelperScenarioSce15ef100_801D369C.c",
    "src/bof3/scenario/invokeHelperScenarioSce15ef100_801D2B44.c",
    "src/bof3/support/sce15ef1_00_psyq.c",
]
psyq_source = "src/bof3/support/sce15ef1_00_psyq.c"
