name: bmagic_magic158_03
sha1: 588b6b0740617efb65a96692044bd21b609850cf
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic158_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic158/03.bin
  asm_path: out/splat/emi/bmagic/magic158/03/asm
  src_path: src/emi/bmagic/magic158/03
  ld_script_path: out/splat/emi/bmagic/magic158/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 752
        - asm
        - func_801EEEF0
      - - 1776
        - asm
        - func_801EF2F0
      - - 2028
        - asm
        - func_801EF3EC
      - - 2824
        - asm
        - func_801EF708
  - - 0x2994
