bof3_artifact_register_built(
    bof3_exe
    FOLDER ""
    PROGRAM_NAME "SLUS_004.22"
    PROGRAM_PATH "/boot/SLUS_004.22"
    SOURCE_HINT "${BOF3_EXTRACTED_DIR}/SLUS_004.22"
    KIND "boot"
    BUILT_OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/bof3.exe"
    DECLARED_SOURCES ${BOF3_CORE_SOURCES}
)
