name: etc_sisyou_00
sha1: 4b2966f7fb129ed097fad383f3930175afa7260c
options:
  platform: psx
  compiler: psyq
  basename: etc_sisyou_00
  base_path: ../../../../../..
  target_path: out/binaries/emi/etc/sisyou/00.bin
  asm_path: out/splat/emi/etc/sisyou/00/asm
  src_path: src/emi/etc/sisyou/00
  ld_script_path: out/splat/emi/etc/sisyou/00/linker.ld
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/etc/sisyou/00/symbols.txt
segments:
- name: main
  type: code
  start: 0
  vram: 2149387264
  subsegments:
  - - 0
    - asm
    - T_801D0C00
  - - 72
    - asm
    - func_801D0C48
  - - 136
    - asm
    - func_801D0C88
  - - 468
    - asm
    - func_801D0DD4
  - - 1196
    - asm
    - func_801D10AC
  - - 1788
    - asm
    - func_801D12FC
  - - 2116
    - asm
    - func_801D1444
  - - 2940
    - asm
    - func_801D177C
  - - 3880
    - asm
    - func_801D1B28
  - - 4164
    - asm
    - func_801D1C44
  - - 4288
    - asm
    - func_801D1CC0
  - - 4692
    - asm
    - func_801D1E54
  - - 6048
    - asm
    - func_801D23A0
  - - 6432
    - c
    - func_801D2520
  - - 6616
    - asm
    - func_801D25D8
  - - 6676
    - asm
    - func_801D2614
  - - 6792
    - asm
    - func_801D2688
  - - 6852
    - asm
    - func_801D26C4
  - - 6968
    - asm
    - func_801D2738
  - - 7052
    - asm
    - func_801D278C
  - - 7112
    - asm
    - func_801D27C8
  - - 7212
    - asm
    - func_801D282C
  - - 7344
    - asm
    - func_801D28B0
  - - 7624
    - asm
    - func_801D29C8
  - - 7756
    - asm
    - func_801D2A4C
  - - 8036
    - asm
    - func_801D2B64
  - - 8168
    - asm
    - func_801D2BE8
  - - 8228
    - asm
    - func_801D2C24
  - - 8292
    - asm
    - func_801D2C64
  - - 8356
    - asm
    - func_801D2CA4
  - - 9412
    - asm
    - func_801D30C4
  - - 9544
    - asm
    - func_801D3148
  - - 9816
    - asm
    - func_801D3258
  - - 9940
    - asm
    - func_801D32D4
  - - 10000
    - asm
    - func_801D3310
  - - 10064
    - asm
    - func_801D3350
  - - 10128
    - asm
    - func_801D3390
  - - 11028
    - asm
    - func_801D3714
  - - 11160
    - asm
    - func_801D3798
  - - 11432
    - asm
    - func_801D38A8
  - - 11556
    - asm
    - func_801D3924
  - - 11616
    - asm
    - func_801D3960
  - - 11724
    - asm
    - func_801D39CC
  - - 11812
    - asm
    - func_801D3A24
  - - 12912
    - asm
    - func_801D3E70
  - - 13008
    - asm
    - func_801D3ED0
  - - 13148
    - asm
    - T_801D3F5C
- - 13960
  - bin
  - data
- - 13963
