name: world00_area026_13
sha1: 46d12af918a938368b06a5091400871e192f140a
options:
  platform: psx
  compiler: psyq
  basename: world00_area026_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world00/area026/13.bin
  asm_path: out/splat/emi/world00/area026/13/asm
  src_path: src/emi/world00/area026/13
  ld_script_path: out/splat/emi/world00/area026/13/linker.ld
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world00/area026/13/symbols.txt
segments:
- name: main
  type: code
  start: 0
  vram: 2149526528
  subsegments:
  - - 0
    - asm
    - T_801F2C00
  - - 72
    - asm
    - func_801F2C48
  - - 148
    - asm
    - func_801F2C94
  - - 284
    - c
    - resetWorkareaSelectMode2
  - - 316
    - c
    - resetWorkareaSelectMode3
  - - 348
    - asm
    - func_801F2D5C
  - - 516
    - asm
    - func_801F2E04
  - - 1036
    - asm
    - func_801F300C
  - - 1116
    - asm
    - func_801F305C
  - - 1180
    - c
    - setScenarioFlagBit29ClearBit28
  - - 1236
    - c
    - clearScenarioFlagBit29
  - - 1276
    - c
    - setScenarioFlagBit28
  - - 1316
    - c
    - clearScenarioFlagBit28
  - - 1356
    - c
    - setScenarioFlagBit2B
  - - 1396
    - c
    - clearScenarioFlagBit2B
  - - 1436
    - c
    - setScenarioFlagBit2C
  - - 1476
    - c
    - clearScenarioFlagBit2C
  - - 1516
    - asm
    - func_801F31EC
  - - 1584
    - c
    - retreatCounter
  - - 1624
    - c
    - advanceCounter
  - - 1664
    - c
    - resetCounter
  - - 1720
    - asm
    - func_801F32B8
  - - 1848
    - c
    - setScenarioFlagBit2E
  - - 1888
    - asm
    - func_801F3360
  - - 2028
    - asm
    - T_801F33EC
- - 8420
  - bin
  - data
- - 8421
