name: world03_area144_13
sha1: da1dc4e91fece3b723e1d2655e888ed93296c105
options:
  platform: psx
  compiler: psyq
  basename: world03_area144_13
  base_path: ../../../../..
  target_path: out/binaries/emi/world03/area144/13.bin
  asm_path: out/splat/emi/world03/area144/13/asm
  src_path: src/emi/world03/area144/13
  ld_script_path: out/splat/emi/world03/area144/13/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149526528
    subsegments:
      - - 536
        - asm
        - func_801F2E18
      - - 1228
        - asm
        - func_801F30CC
      - - 1316
        - asm
        - func_801F3124
      - - 2300
        - asm
        - func_801F34FC
      - - 2924
        - asm
        - func_801F376C
  - - 0x1d64
