name: world04_area180_13
sha1: 1f748fbd35acba10593cc2a5b8eaae24edc122dd
options:
  platform: psx
  compiler: psyq
  basename: world04_area180_13
  base_path: ../../../../../..
  target_path: out/binaries/emi/world04/area180/13.bin
  asm_path: out/splat/emi/world04/area180/13/asm
  src_path: src/emi/world04/area180/13
  ld_script_path: out/splat/emi/world04/area180/13/linker.ld
  undefined_funcs_auto_path: out/splat/emi/world04/area180/13/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/world04/area180/13/undefined_syms_auto.txt
  cache_path: out/splat/emi/world04/area180/13/.splache
  asset_path: out/splat/emi/world04/area180/13/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/world04/area180/13/symbols.txt
segments:
- - 0
  - bin
  - header
- - 4
  - bin
  - tabledata
- name: main
  type: code
  start: 1752
  vram: 2149528280
  subsegments:
  - - 1752
    - asm
    - func_801F32D8
  - - 1832
    - c
    - invokeHelperArgWorld04Area18013_801F3328
  - - 1864
    - asm
    - func_801F3348
  - - 1912
    - asm
    - func_801F3378
  - - 2020
    - asm
    - func_801F33E4
  - - 2164
    - asm
    - D_801F3474
- - 3016
