bof3_define_module_artifact(
    bof3_shop_00_raw
    PLACEHOLDER
    DISC_FOLDER "BIN/ETC/SHOP"
    PROGRAM_NAME "00.bin"
    PROGRAM_PATH "/bins/BIN/ETC/SHOP/00.bin"
    SOURCE_HINT "${BOF3_EXTRACTED_DIR}/BIN/ETC/SHOP.EMI#0"
    DECLARED_SOURCES ${BOF3_MODULE_SHOP_00_SOURCES}
)

bof3_define_module_artifact(
    bof3_sisyou_00_raw
    PLACEHOLDER
    DISC_FOLDER "BIN/ETC/SISYOU"
    PROGRAM_NAME "00.bin"
    PROGRAM_PATH "/bins/BIN/ETC/SISYOU/00.bin"
    SOURCE_HINT "${BOF3_EXTRACTED_DIR}/BIN/ETC/SISYOU.EMI#0"
    DECLARED_SOURCES ${BOF3_MODULE_SISYOU_00_SOURCES}
)
