bof3_define_module_artifact(
    bof3_scena16_00_raw
    DISC_FOLDER "BIN/ETC/SCENA16"
    PROGRAM_NAME "00.bin"
    PROGRAM_PATH "/bins/BIN/ETC/SCENA16/00.bin"
    SOURCE_HINT "${BOF3_EXTRACTED_DIR}/BIN/ETC/SCENA16.EMI#0"
    DECLARED_SOURCES ${BOF3_MODULE_SCENA16_00_SOURCES}
)
