name: bmagic_magic097_03
sha1: 9f7331ce32d0316ab3659c76b306fe48a4e0feb6
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic097_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic097/03.bin
  asm_path: out/splat/emi/bmagic/magic097/03/asm
  src_path: src/emi/bmagic/magic097/03
  ld_script_path: out/splat/emi/bmagic/magic097/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 0
        - asm
        - func_801EEC00
      - - 2320
        - asm
        - func_801EF510
      - - 2500
        - asm
        - func_801EF5C4
      - - 6504
        - asm
        - func_801F0568
      - - 7228
        - asm
        - func_801F083C
  - - 0x1ed4
