name: bmagic_magic087_03
sha1: 3f41adacdb74aa29989eabd249c1c3a71c370923
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic087_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic087/03.bin
  asm_path: out/splat/emi/bmagic/magic087/03/asm
  src_path: src/emi/bmagic/magic087/03
  ld_script_path: out/splat/emi/bmagic/magic087/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 2432
        - asm
        - func_801EF580
      - - 3416
        - asm
        - func_801EF958
      - - 4944
        - asm
        - func_801EFF50
      - - 5140
        - asm
        - func_801F0014
      - - 6308
        - asm
        - func_801F04A4
  - - 0x3ecc
