name: battle_batl_ovr_00
sha1: e3c94ee01969e242b77482ec8c11e978c3c5d0f3
options:
  platform: psx
  compiler: psyq
  basename: battle_batl_ovr_00
  base_path: ../../../../../..
  target_path: out/binaries/emi/battle/batl_ovr/00.bin
  asm_path: out/splat/emi/battle/batl_ovr/00/asm
  src_path: src/emi/battle/batl_ovr/00
  ld_script_path: out/splat/emi/battle/batl_ovr/00/linker.ld
  undefined_funcs_auto_path: out/splat/emi/battle/batl_ovr/00/undefined_funcs_auto.txt
  undefined_syms_auto_path: out/splat/emi/battle/batl_ovr/00/undefined_syms_auto.txt
  cache_path: out/splat/emi/battle/batl_ovr/00/.splache
  asset_path: out/splat/emi/battle/batl_ovr/00/assets
  symbol_addrs_path:
  - config/targets/shared/symbols.txt
  - config/sdk/psyq-slus.txt
  - config/targets/emi/battle/batl_ovr/00/symbols.txt
segments:
- - 0
  - bin
  - header
- name: main
  type: code
  start: 4
  vram: 2149510148
  subsegments:
  - - 4
    - asm
    - func_801EEC04
  - - 64
    - asm
    - func_801EEC40
  - - 124
    - asm
    - func_801EEC7C
  - - 696
    - asm
    - func_801EEEB8
  - - 784
    - asm
    - func_801EEF10
  - - 1192
    - asm
    - func_801EF0A8
  - - 1408
    - asm
    - func_801EF180
  - - 1816
    - asm
    - func_801EF318
  - - 1972
    - asm
    - func_801EF3B4
  - - 2172
    - asm
    - func_801EF47C
  - - 2552
    - asm
    - D_801EF5F8
- - 2644
