name: bmagic_magic083_03
sha1: dbe4db9276d945e213d7ee9614052e0715e97ecf
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic083_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic083/03.bin
  asm_path: out/splat/emi/bmagic/magic083/03/asm
  src_path: src/emi/bmagic/magic083/03
  ld_script_path: out/splat/emi/bmagic/magic083/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1228
        - asm
        - func_801EF0CC
      - - 2964
        - asm
        - func_801EF794
      - - 3140
        - asm
        - func_801EF844
      - - 3876
        - asm
        - func_801EFB24
      - - 4692
        - asm
        - func_801EFE54
      - - 6412
        - asm
        - func_801F050C
      - - 8104
        - asm
        - func_801F0BA8
      - - 8640
        - asm
        - func_801F0DC0
      - - 8740
        - asm
        - func_801F0E24
  - - 0x2e5c
