name: bmagic_magic044_03
sha1: 4d86547e94f785f98dfbfc0b053ead660d590291
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic044_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic044/03.bin
  asm_path: out/splat/emi/bmagic/magic044/03/asm
  src_path: src/emi/bmagic/magic044/03
  ld_script_path: out/splat/emi/bmagic/magic044/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 2272
        - asm
        - func_801EF4E0
      - - 3660
        - asm
        - func_801EFA4C
      - - 5792
        - asm
        - func_801F02A0
      - - 6032
        - asm
        - func_801F0390
      - - 6872
        - asm
        - func_801F06D8
  - - 0x1f38
