name: bmagic_magic043_03
sha1: b6224bb1f71bdef008b4b677081e395feeee2ba0
options:
  platform: psx
  compiler: psyq
  basename: bmagic_magic043_03
  base_path: ../../../../..
  target_path: out/binaries/emi/bmagic/magic043/03.bin
  asm_path: out/splat/emi/bmagic/magic043/03/asm
  src_path: src/emi/bmagic/magic043/03
  ld_script_path: out/splat/emi/bmagic/magic043/03/linker.ld
  symbol_addrs_path:
    - config/symbols/psyq.txt
    - config/symbols/shared.txt
segments:
  - name: main
    type: code
    start: 0
    vram: 2149510144
    subsegments:
      - - 1888
        - asm
        - func_801EF360
      - - 2860
        - asm
        - func_801EF72C
      - - 3064
        - asm
        - func_801EF7F8
      - - 4132
        - asm
        - func_801EFC24
  - - 0x2ea4
